- content/develop/interact/programmability/_index.md
- content/glossary/_index.md
- content/operate/oss_and_stack/management/optimization/memory-optimization.md
Base Staging link: redis.io/docs/staging/relref-fixes/
> Fix relref errors

- layouts/partials/footer.html
- layouts/partials/header.html
- layouts/partials/header/company-dropdown.html
- layouts/partials/header/docs-dropdown.html
- layouts/partials/header/products-dropdown.html
- layouts/partials/header/solutions-dropdown.html
- layouts/partials/header/support-dropdown.html
Fixing links, text, and styling
> Docs footer fixes, links and text

- content/operate/rc/databases/configuration/clustering.md
Ticket: DOC-3555
Staging link: https://redis.io/docs/staging/DOC-3555/operate/rc/databases/configuration/clustering#memory-limit
> RC: Add note to memory limit section that search and query needs to be properly sized

- content/operate/rc/accounts/user-profile.md
Ticket: DOC-3616
Staging link: https://redis.io/docs/staging/DOC-3616/operate/rc/accounts/user-profile/#switch-redis-cloud-accounts
> RC: Include workaround for creating a new SM account with the same email

- content/operate/rs/release-notes/rs-7-2-4-releases/_index.md
DOC-3593
[Staged preview](https://redis.io/docs/staging/DOC-3593-reword/operate/rs/release-notes/rs-7-2-4-releases/#known-limitations) - the known limitation is the last one on the page
> RS: Rewording known limitation for RHEL clones

- content/operate/rs/release-notes/rs-7-4-2-releases/_index.md
- content/operate/rs/release-notes/rs-7-4-2-releases/rs-7-4-2-129.md
DOC-3642
[Staged preview](https://redis.io/docs/staging/release-rs-fuji-apr-fix/operate/rs/release-notes/rs-7-4-2-releases/rs-7-4-2-129/)
> RS: April Fuji 7.4.2 hotfix release notes

- content/integrate/redis-data-integration/data-transformation/examples/_index.md
- layouts/integration/list.html
Ticket: [DOC-3652](https://redislabs.atlassian.net/browse/DOC-3652)
Staging link:  https://redis.io/docs/staging/DOC-3652/integrate/redis-data-integration/data-transformation/examples/
> DOC-3652: fix for null description in front matter

- content/operate/rs/references/rest-api/objects/bdb/_index.md
DOC-3560
[Staged preview](https://redis.io/docs/staging/DOC-3560/operate/rs/references/rest-api/objects/bdb/)
> RS: Add missing fields to BDB REST API object

- content/operate/oss_and_stack/install/install-redis-insight/_index.md
- content/operate/oss_and_stack/install/install-redis-insight/install-on-docker.md
Ticket: [DOC-3671](https://redislabs.atlassian.net/browse/DOC-3671)
[Staged preview](https://redis.io/docs/staging/DOC-3671/operate/redisinsight) - should redirect to the Redis Insight installation page.
> DOC-3671: fix broken link and add alias for moved content

- content/operate/oss_and_stack/install/_index.md
- content/operate/redisinsight/_index.md
- content/operate/redisinsight/install/_index.md
- content/operate/redisinsight/install/env-variables.md
- content/operate/redisinsight/install/install-on-aws.md
- content/operate/redisinsight/install/install-on-docker.md
- content/operate/redisinsight/install/install-on-k8s.md
- layouts/home.html
Ticket: [DOC-3672](https://redislabs.atlassian.net/browse/DOC-3672)
[Staged preview](https://redis.io/docs/staging/DOC-3672/)
> DOC-3672: reverse RI changes

- content/commands/psync/index.md
Ticket: [DOC-3674](https://redislabs.atlassian.net/browse/DOC-3674)
[Staging link](https://redis.io/docs/staging/DOC-3674/commands/psync)
Fixes #128.
> DOC-3674: fixes broken link on PSYNC page

- content/operate/rs/clusters/remove-node.md
- content/operate/rs/references/rest-api/requests/nodes/actions.md
DOC-3490
- [Remove a node](https://redis.io/docs/staging/DOC-3490/operate/rs/clusters/remove-node/#remove-a-node)
- [Remove node REST API reference](https://redis.io/docs/staging/DOC-3490/operate/rs/references/rest-api/requests/nodes/actions/#post-node-action)
> RS: Add wait_for_persistence to remove node docs

- layouts/_default/baseof.html
> Revert "LRC-324 Add canonicals to prod layout"

- content/operate/rc/cloud-integrations/aws-cloud-accounts/subscription-whitelist.md
- content/operate/rc/security/cidr-whitelist.md
Ticket: DOC-2703
Staging link: 
https://redis.io/docs/staging/DOC-2703/operate/rc/security/cidr-whitelist/
https://redis.io/docs/staging/DOC-2703/operate/rc/cloud-integrations/aws-cloud-accounts/subscription-whitelist
> RC Security reorg: Split CIDR allow list into a Database CIDIR allow list and Subscription CIDR allow list

- layouts/partials/docs-nav-collapsed.html
- layouts/partials/docs-nav.html
> Documentation improvements

- content/develop/interact/search-and-query/deprecated/development.md
After changing the build proccess for redisearch module, update the developer docs
> Update developer docs for redisearch

- content/operate/rs/installing-upgrading/install/install-on-linux.md
dpkg-sig --verify  need to run on installation package (*.deb) which is only available after
```
sh tar vxf <tarfile name>
```
Fixes #157.
> Update the sequence of commands in install-on-linux.md

- content/operate/rs/release-notes/rs-6-4-2-releases/_index.md
- content/operate/rs/release-notes/rs-7-2-4-releases/_index.md
- content/operate/rs/release-notes/rs-7-4-2-releases/_index.md
DOC-3710
- [7.4.2 release notes](https://redis.io/docs/staging/DOC-3710/operate/rs/release-notes/rs-7-4-2-releases/#known-issues)
- [7.2.4 release notes](https://redis.io/docs/staging/DOC-3710/operate/rs/release-notes/rs-7-2-4-releases/#known-issues)
- [6.4.2 release notes](https://redis.io/docs/staging/DOC-3710/operate/rs/release-notes/rs-6-4-2-releases/#feature-limitations)
> RS: Add CRDT syncer known limitation to release notes

- content/operate/kubernetes/deployment/openshift/openshift-cli.md
- content/operate/kubernetes/deployment/openshift/openshift-operatorhub.md
- content/operate/kubernetes/deployment/quick-start.md
- content/operate/kubernetes/networking/_index.md
I added notes about the domain format and that the REC name can't be changed after creation. 
Jira: DOC-2347
Preview: https://redis.io/docs/staging/DOC-2347/operate/kubernetes/deployment/quick-start/
> K8s: REC naming notes

- content/develop/connect/insight/_index.md
- content/operate/redisinsight/_index.md
- content/operate/redisinsight/install/_index.md
- content/operate/redisinsight/install/env-variables.md
- content/operate/redisinsight/install/install-on-aws.md
- content/operate/redisinsight/install/install-on-desktop.md
- content/operate/redisinsight/install/install-on-k8s.md
Ticket: [DOC-3722](https://redislabs.atlassian.net/browse/DOC-3722)
https://redis.io/docs/staging/DOC-3722/operate/redisinsight/install/
https://redis.io/docs/staging/DOC-3722/operate/redisinsight/install/install-on-desktop/
> DEV: add new RI installation page, cross links, and change order

- content/glossary/_index.md
DOC-3667
[Staged preview](https://redis.io/docs/staging/DOC-3667/glossary/#letter-c)
> Fix CCS entry typos in glossary

- content/operate/kubernetes/active-active/_index.md
- content/operate/kubernetes/active-active/prepare-clusters.md
Preview: 
https://redis.io/docs/staging/DOC-3724/operate/kubernetes/active-active/prepare-clusters/
https://redis.io/docs/staging/DOC-3724/operate/kubernetes/active-active/
> K8s: code block bug - replace note with subsection

- layouts/home.html
- layouts/partials/docs-nav-collapsed.html
- layouts/partials/docs-nav.html
This also adds all menu items to each page for consistency.
Preview link: https://redis.io/docs/staging/update-nav/
> Update nav to put Commands and APIs at the top of menu on all pages

- content/develop/connect/insight/_index.md
- content/operate/redisinsight/install/configuration.md
Ticket: [DOC-3757](https://redislabs.atlassian.net/browse/DOC-3757)
- https://redis.io/docs/staging/DOC-3757/develop/connect/insight/#log-files
- https://redis.io/docs/staging/DOC-3757/operate/redisinsight/install/configuration/
> DEV: add logging and configuration info for Redis Insight

- content/operate/rc/security/_index.md
Staging link: https://redis.io/docs/staging/DOC-3763/operate/rc/security/#admin-console-security
> Add session expiration note

- content/operate/redisinsight/install/install-on-k8s.md
Ticket: DOC-3765
https://redis.io/docs/staging/DOC-3765/operate/redisinsight/install/install-on-k8s/
Fixes #176.
> DEV: fix issue #176

- content/develop/reference/protocol-spec.md
Correct spelling errors: changed "REdis Serialization Protocol (RESP)." to "Redis Serialization Protocol (RESP)."
> Update protocol-spec.md （Correct spelling errors）

- content/operate/rs/security/certificates/_index.md
[DOC-2386](https://redislabs.atlassian.net/browse/DOC-2386)
[Staged preview](https://redis.io/docs/staging/DOC-2386/operate/rs/security/certificates/)
> RS: Add ldap_client to certificates table

- content/develop/interact/search-and-query/advanced-concepts/vectors.md
existing: Currently, Redis don't support Hybrid Queries with...
change: Currently, Redis doesn't support Hybrid Queries with...
> small grammar update on vectors.md

- content/embeds/supported-platforms-embed.md
[DOC-1342](https://redislabs.atlassian.net/browse/DOC-1342)
[Staged preview](https://redis.io/docs/staging/DOC-1342/operate/rs/references/supported-platforms/#virtualization-platforms)
> RS: Add maintenance mode link to virtualization platforms checklist

- content/operate/rs/databases/configure/oss-cluster-api.md
[DOC-3794](https://redislabs.atlassian.net/browse/DOC-3794)
> RS: Fix typo in rladmin tune db oss_cluster example

- content/operate/rs/release-notes/rs-7-2-4-releases/rs-7-2-4-109.md
- content/operate/rs/release-notes/rs-7-2-4-releases/rs-7-2-4-tba.md
[DOC-3655](https://redislabs.atlassian.net/browse/DOC-3655)
- [Release notes](https://redis.io/docs/staging/DOC-3659/operate/rs/release-notes/rs-7-2-4-releases/rs-7-2-4-109/)
> RS: 7.2.4 May maintenance release

- content/operate/oss_and_stack/stack-with-enterprise/release-notes/redisearch/redisearch-2.8-release-notes.md
> Actualize latest version of Redis in release notes

- content/commands/topk.list/index.md
- content/develop/data-types/probabilistic/top-k.md
> Fix TOPK.LIST complexity

- content/operate/oss_and_stack/management/sentinel.md
Ticket: [DOC-3825](https://redislabs.atlassian.net/browse/DOC-3825)
[DOC-3825]: https://redislabs.atlassian.net/browse/DOC-3825?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DEV: fix bug in sentinel ACL docs

- data/resp2_replies.json
- data/resp3_replies.json
Ticket: [DOC-3823](https://redislabs.atlassian.net/browse/DOC-3823)
https://redis.io/docs/staging/DOC-3823/commands/sinter/
https://redis.io/docs/staging/DOC-3823/commands/smembers/
[DOC-3823]: https://redislabs.atlassian.net/browse/DOC-3823?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DEV: update RESP3 replies for SINTER and SMEMBERS

- content/operate/rc/databases/import-data.md
Found this while working on the Heroku docs.
> Remove instance of OSS from Import data article

- content/operate/oss_and_stack/stack-with-enterprise/release-notes/redisearch/redisearch-2.8-release-notes.md
- content/operate/rs/references/rest-api/requests/cluster/check.md
- content/operate/rs/references/rest-api/requests/nodes/check.md
> RS: Add REST API references for /cluster/check and /nodes/check

- content/operate/kubernetes/active-active/_index.md
> K8s: add reaadb migration limitation

- data/resp2_replies.json
- data/resp3_replies.json
Fixes #260.
[Staged preview.](https://redis.io/docs/staging/DOC-3842/commands/client-unblock)
> DEV: fix return values for CLIENT UNBLOCK command

- content/operate/rs/databases/configure/replica-ha.md
Fixes https://github.com/redis/docs/issues/173
> RS: Fix typo in replica HA doc

- content/operate/rs/databases/auto-tiering/_index.md
> RS: Fix RAM to flash ratio recommendations

- content/operate/rc/api/get-started/manage-tasks.md
> Remove duplicate starting sentence

- content/develop/data-types/sorted-sets.md
Ticket: [DOC-3636](https://redislabs.atlassian.net/browse/DOC-3636)
[DOC-3636]: https://redislabs.atlassian.net/browse/DOC-3636?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DEV: delete bad link from sorted set page

- content/commands/ts.add/index.md
- content/commands/ts.alter/index.md
- content/commands/ts.create/index.md
- content/commands/ts.decrby/index.md
- content/commands/ts.incrby/index.md
- content/commands/ts.madd/index.md
- content/develop/data-types/timeseries/configuration.md
Ticket: [DOC-3839](https://redislabs.atlassian.net/browse/DOC-3839)
Note to reviewers: There's currently a placeholder (@LIOR NEED) on the time series configuration page . I'll need this release number before these changes can go live.
[DOC-3839]: https://redislabs.atlassian.net/browse/DOC-3839?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DEV: time series changes for 7.4 RC1

- content/develop/connect/cli.md
- content/develop/reference/modules/modules-api-ref.md
- content/operate/oss_and_stack/management/config-file.md
- content/operate/oss_and_stack/management/config.md
Ticket: [DOC-3867](https://redislabs.atlassian.net/browse/DOC-3867)
Some last minute changes for 7.4 RC1. There may be one more commit needed here, just not sure about the timing.
[DOC-3867]: https://redislabs.atlassian.net/browse/DOC-3867?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DEV: last minute 7.4 RC1 updates

- content/operate/rs/networking/multi-ip-ipv6.md
> RS: Fix rlec_supervisor typo

- content/operate/oss_and_stack/install/install-stack/mac-os.md
> RS: Update mac-os.md grammatical error 

- content/integrate/redis-data-integration/ingest/reference/cli/redis-di-set-secret.md
> Fixed cli ref page for set-secret

- content/operate/rs/security/access-control/manage-users/default-user.md
> RS: Add link to Redis authentication from default user doc

- content/develop/get-started/rag.md
New quick start for retrieval augmented generation.
@mich-elle-luna has already reviewed.
> DEV: add new quick start guide for RAG

- layouts/home.html
Fixed the links in the home layout. Is there anything else I need to do here?
> DOC-3877 fixed RDI links on doc homepage

- content/operate/oss_and_stack/stack-with-enterprise/json/_index.md
Ticket: [DOC-3879](https://redislabs.atlassian.net/browse/DOC-3879)
[DOC-3879]: https://redislabs.atlassian.net/browse/DOC-3879?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DEV: update link in JSON section

- data/components/jedis.json
See https://github.com/redis/jedis/commit/f4fcc3628fcfcd29037e070071ea794669277679
> Pull Jedis doctests from the master

- content/operate/oss_and_stack/stack-with-enterprise/_index.md
> DEV: fix link on Redis Stack and Redis Enterprise page

- content/operate/oss_and_stack/stack-with-enterprise/search/commands.md
- content/operate/oss_and_stack/stack-with-enterprise/search/config.md
- content/operate/oss_and_stack/stack-with-enterprise/search/scalable-search.md
> Enable scalable Redis Query Engine in Redis Enterprise

- content/integrate/terraform-provider-for-redis-cloud/_index.md
> RC: Add new Data sources and resources to Terraform doc

- content/operate/rc/cloud-integrations/aws-marketplace/_index.md
> RC: Add private offer step to AWS marketplace docs

- content/develop/data-types/hashes.md
I've added some of the content [from this confluence page](https://docs.google.com/document/d/11mQ5UMveoCnpOf-8BJPch7kMHHA7Z1t3FWYObGiVmzk/edit#heading=h.hlsdppmuz0yq), written by the PMs, to the hash data structure page.
@mich-elle-luna: Please give this content an initial review. I'll then open it up to others. Thank you!
> DEV: add some PM content to the hash page

- content/commands/json.arrtrim/index.md
> chore: Initialize data using set

- content/develop/interact/search-and-query/advanced-concepts/scoring.md
Updated the Search Scoring doc to remove references to the deprecated FT.ADD command.
> Remove FT.ADD reference

- build/components/example.py
See https://github.com/redis/node-redis/issues/2780
> Convert step names in code examples to lowercase

- content/develop/use/keyspace-notifications.md
Small update to the keyspace notifications page.
> DEV: update keyspace notifications for HFE commands

- content/commands/hexpire/index.md
- content/commands/hexpireat/index.md
- content/commands/hexpiretime/index.md
- content/commands/hpersist/index.md
- content/commands/hpexpire/index.md
- content/commands/hpexpireat/index.md
- content/commands/hpexpiretime/index.md
- content/commands/hpttl/index.md
- content/commands/httl/index.md
Ticket: [DOC-3896](https://redislabs.atlassian.net/browse/DOC-3896).
[DOC-3896]: https://redislabs.atlassian.net/browse/DOC-3896?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DEV: modify return values for HFE commands

- content/develop/get-started/vector-database.md
This PR introduces recommended updates to the vector database quickstart guide to improve language, terminology, and readability.
Open to discussion and feedback!
Quick question:
- If we wanted to add RedisVL examples as another tab option, how could we accomplish that? (I couldn't exactly figure out how the `client-examples` callout was working.
- On a similar note, it seems like some code snippets call out to external code while others are hard coded. What all is needed to update them to use a consistent technique (and so I can add more)?
Thanks!
> Update vector db quickstart guide

- content/operate/rc/cloud-integrations/aws-marketplace/_index.md
- content/operate/rc/cloud-integrations/gcp-marketplace/_index.md
> AWS and GCP Marketplace integrations private offer fixes

- content/commands/ft.aliasadd/index.md
- content/develop/interact/search-and-query/advanced-concepts/vectors.md
One bug fix (command misspelling) and two changes to the use of "brute force". I'm open to others suggestions for the latter.
> DEV: fix two minor bugs in dev docs

- content/integrate/redis-data-integration/ingest/installation/_index.md
Minor changes suggested on the RDI Slack channel.
> Doc 3936 rdi installer doc fixes

- content/integrate/redis-data-integration/_index.md
[DOC-2766](https://redislabs.atlassian.net/browse/DOC-2766) asks if the data rate of 28K is correct but Yaron has asked for this section to be removed completely.
[DOC-2766]: https://redislabs.atlassian.net/browse/DOC-2766?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DOC-2766 removed Performance and Scalability section altogether

- content/commands/ft.create/index.md
- content/commands/ft.search/index.md
- content/develop/interact/search-and-query/advanced-concepts/dialects.md
- content/develop/interact/search-and-query/advanced-concepts/query_syntax.md
- content/develop/interact/search-and-query/advanced-concepts/vectors.md
- content/develop/interact/search-and-query/basic-constructs/configuration-parameters.md
[DOC-2055](https://redislabs.atlassian.net/browse/DOC-2055) makes several requests for improvements to the info about query dialects, all of which are implemented in this PR. The issue also requests a dedicated page for query dialects but this has already been added.
[DOC-2055]: https://redislabs.atlassian.net/browse/DOC-2055?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DOC-2055 added links/info about dialects based on feedback

- content/integrate/redis-data-integration/ingest/data-pipelines/data-pipelines.md
Details about how to set authentication secrets, based on a Slack message.
> Doc 3961 secret setting info

- content/develop/interact/search-and-query/query/exact-match.md
added more clarification on the feature
> clarified double quote usage for TAG

- content/develop/interact/search-and-query/indexing/_index.md
added example for the new missing/empty functionality.
> add content for INDEXMISSING and INDEXEMPTY

- content/develop/interact/search-and-query/advanced-concepts/dialects.md
- content/develop/interact/search-and-query/basic-constructs/field-and-type-options.md
the decision was made to not release dialect 5.  the functionality that was in dialect 5 has been folded into dialect 2.
> remove references to dialect 5

- layouts/partials/footer.html
Add the GitHub icon to our socials list.
> Add github icon to footer

- content/operate/kubernetes/re-databases/db-controller.md
Added link to multi-namespace page and adjusted heading levels.
> K8s: Create database edits

- content/operate/rc/subscriptions/_index.md
> RC: Update Subscriptions landing page

- content/develop/interact/search-and-query/administration/design.md
- content/develop/interact/search-and-query/administration/overview.md
- content/develop/interact/search-and-query/advanced-concepts/chinese.md
- content/develop/interact/search-and-query/deprecated/payloads.md
This PR removes occurrences of FT.ADD, replacing them with HSET as appropriate. N.B. references in releases notes are still there.
> DEV: remove occurrences of FT.ADD

- content/operate/rs/databases/import-export/export-data.md
- content/operate/rs/databases/import-export/import-data.md
- content/operate/rs/databases/import-export/schedule-backups.md
> RS: Add missing description of connecting to S3-compatible storage

- content/commands/client-kill/index.md
[DOC-3791](https://redislabs.atlassian.net/browse/DOC-3791): is this enough or do we need some further references to the version?
[DOC-3791]: https://redislabs.atlassian.net/browse/DOC-3791?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DOC-3791 added note about version MAXAGE was introduced

- content/operate/rc/_index.md
- content/operate/rs/_index.md
DOC-3808
@rrelledge - Feel free to suggest a different description for the RS page. 
You can see descriptions on the [top-level operate page](https://redis.io/docs/staging/DOC-3808/operate/)
> Add descriptions for RS and RC

- content/integrate/prometheus-with-redis-cloud/_index.md
- content/integrate/prometheus-with-redis-enterprise/_index.md
> Replaced links to grafana dashboards from grafana repo to observability repo

- data/resp2_replies.json
- data/resp3_replies.json
[DOC-3789](https://redislabs.atlassian.net/browse/DOC-3789) .
[DOC-3789]: https://redislabs.atlassian.net/browse/DOC-3789?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DEV: add NOVALUES flag to HSCAN reply information

- data/resp2_replies.json
- data/resp3_replies.json
[DOC-2579](https://redislabs.atlassian.net/browse/DOC-2579) Hoping this is the correct way to fix this issue! Also applies to SPUBLISH, not mentioned in the JIRA issue.
[DOC-2579]: https://redislabs.atlassian.net/browse/DOC-2579?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DOC-2579 fixed response descriptions

- layouts/partials/meta-links.html
Generated links will be like: https://github.com/redis/docs/issues/new?title=Feedback:%20ACL%20CAT&body=Page%20https://redis.io/docs/latest/commands/acl-cat
> Include link to page in issues form

- content/operate/rc/supported-regions.md
> RC: Add new Google Cloud regions

- content/operate/rc/resilient-apps.md
- content/operate/rc/subscriptions/maintenance/_index.md
- content/operate/rc/subscriptions/maintenance/set-maintenance-windows.md
> RC: Default maintenance windows for Essentials databases

- content/integrate/prometheus-with-redis-cloud/_index.md
- content/integrate/prometheus-with-redis-enterprise/_index.md
> Integrate: Add Active-Active grafana dashboards to grafana list for Software and Cloud

- content/operate/oss_and_stack/install/install-redis/install-redis-on-linux.md
- content/operate/oss_and_stack/install/install-redis/install-redis-on-mac-os.md
- content/operate/oss_and_stack/install/install-redis/install-redis-on-windows.md
- content/operate/oss_and_stack/install/install-stack/linux.md
- content/operate/oss_and_stack/install/install-stack/mac-os.md
[DOC-3704](https://redislabs.atlassian.net/browse/DOC-3704)
There was actually some inconsistency among all the platforms (they each had something useful that the others didn't) so I've tried to bring them into line.
[DOC-3704]: https://redislabs.atlassian.net/browse/DOC-3704?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DOC-3704 updated start/stop and next steps

- content/operate/rs/installing-upgrading/product-lifecycle.md
> RS: Update EOL policy by 6 months

- content/operate/rs/clusters/logging/log-security.md
> RS: Change title from Log security to Manage logs

- content/operate/rs/release-notes/rs-7-4-2-releases/_index.md
Copy product lifecycle updates from PR #399 to 7.4.2 release notes index.
> RS: Copy product lifecycle updates from PR #399 to 7.4.2 release notes index

- content/operate/rc/subscriptions/maintenance/_index.md
> RC: Moved link to resilient apps in the maintenance docs

- content/integrate/redis-data-integration/ingest/installation/_index.md
- content/integrate/redis-data-integration/ingest/quick-start-guide.md
[DOC-4011](https://redislabs.atlassian.net/browse/DOC-4011)
[DOC-4011]: https://redislabs.atlassian.net/browse/DOC-4011?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DOC-4011 added note about min RS version for RDI database

- content/operate/oss_and_stack/stack-with-enterprise/release-notes/redisbloom/redisbloom-2.6-release-notes.md
- content/operate/oss_and_stack/stack-with-enterprise/release-notes/redisbloom/redisbloom-2.8-release-notes.md
- content/operate/oss_and_stack/stack-with-enterprise/release-notes/redisearch/redisearch-2.10-release-notes.md
- content/operate/oss_and_stack/stack-with-enterprise/release-notes/redisearch/redisearch-2.6-release-notes.md
- content/operate/oss_and_stack/stack-with-enterprise/release-notes/redisearch/redisearch-2.8-release-notes.md
- content/operate/oss_and_stack/stack-with-enterprise/release-notes/redisgears/redisgears-1.2-release-notes.md
- content/operate/oss_and_stack/stack-with-enterprise/release-notes/redisjson/redisjson-2.8-release-notes.md
- content/operate/oss_and_stack/stack-with-enterprise/release-notes/redistimeseries/redistimeseries-1.12-release-notes.md
N.B. I didn't spend much time, if any, copy-editing content. I don't think it's necessary for release notes.
> OP: update module relnotes

- content/operate/rs/installing-upgrading/upgrading/upgrade-cluster.md
> RS: Add prereq to avoid cluster management operations during cluster upgrade

- .github/workflows/k8s_apis_sync.yaml
- content/operate/kubernetes/reference/kubernetes-api-reference-frontmatter.patch
- content/operate/kubernetes/reference/kubernetes-api-reference-template.tmpl
The workflow must be executed manually with the name of the release of interest
> DOC-3991 Add workflow that builds K8S api spec

- content/operate/rs/references/rest-api/objects/cm_settings.md
- content/operate/rs/references/rest-api/requests/cm_settings/_index.md
> RS: REST API reference to change CM UI time zone

- content/operate/rs/release-notes/rs-7-4-2-releases/_index.md
> RS: Change 7.4.2 to 7.4 on release notes index page

- content/embeds/supported-platforms-embed.md
EOL should match: https://redis.io/docs/latest/operate/rs/installing-upgrading/product-lifecycle/#endoflife-schedule
> RS: Update EOL in supported platforms table

- content/integrate/redisom-for-python/_index.md
- content/operate/oss_and_stack/stack-with-enterprise/gears-v1/jvm/classes/gearsbuilder/config-get.md
- content/operate/oss_and_stack/stack-with-enterprise/release-notes/redisbloom/redisbloom-2.0-release-notes.md
- content/operate/oss_and_stack/stack-with-enterprise/release-notes/redisbloom/redisbloom-2.2-release-notes.md
- content/operate/oss_and_stack/stack-with-enterprise/release-notes/redisearch/redisearch-1.4-release-notes.md
- content/operate/oss_and_stack/stack-with-enterprise/release-notes/redisearch/redisearch-1.6-release-notes.md
- content/operate/oss_and_stack/stack-with-enterprise/release-notes/redisearch/redisearch-2.0-release-notes.md
- content/operate/oss_and_stack/stack-with-enterprise/release-notes/redisearch/redisearch-2.2-release-notes.md
- content/operate/oss_and_stack/stack-with-enterprise/release-notes/redisearch/redisearch-2.4-release-notes.md
- content/operate/oss_and_stack/stack-with-enterprise/release-notes/redisgears/redisgears-1.0-release-notes.md
- content/operate/oss_and_stack/stack-with-enterprise/release-notes/redisgraph/redisgraph-1.2-release-notes.md
- content/operate/oss_and_stack/stack-with-enterprise/release-notes/redisgraph/redisgraph-2.0-release-notes.md
- content/operate/oss_and_stack/stack-with-enterprise/release-notes/redisgraph/redisgraph-2.2-release-notes.md
- content/operate/oss_and_stack/stack-with-enterprise/release-notes/redisgraph/redisgraph-2.4-release-notes.md
- content/operate/oss_and_stack/stack-with-enterprise/release-notes/redisgraph/redisgraph-2.8-release-notes.md
- content/operate/oss_and_stack/stack-with-enterprise/release-notes/redisjson/redisjson-1.0-release-notes.md
- content/operate/oss_and_stack/stack-with-enterprise/release-notes/redisjson/redisjson-2.0-release-notes.md
- content/operate/oss_and_stack/stack-with-enterprise/release-notes/redistimeseries/redistimeseries-1.0-release-notes.md
- content/operate/oss_and_stack/stack-with-enterprise/release-notes/redistimeseries/redistimeseries-1.2-release-notes.md
- content/operate/oss_and_stack/stack-with-enterprise/release-notes/redistimeseries/redistimeseries-1.4-release-notes.md
- content/operate/oss_and_stack/stack-with-enterprise/release-notes/redistimeseries/redistimeseries-1.6-release-notes.md
- content/operate/rs/new-features-redis-enterprise.md
- content/operate/rs/release-notes/legacy-release-notes/rs-5-4-6-july-2019.md
- content/operate/rs/release-notes/legacy-release-notes/rs-5-4-december-2018.md
> Remove remaining broken oss.redis*.com links from RS and module release notes

- content/integrate/redis-data-integration/ingest/_index.md
- content/integrate/redis-data-integration/ingest/architecture.md
- content/integrate/redis-data-integration/ingest/data-pipelines/data-pipelines.md
- content/integrate/redis-data-integration/ingest/faq.md
I thought the FAQ was the best place for this and there is also a note in the ingest lifecycle section.
> DOC-4067 added FAQ and note about harmless OOM message

- content/operate/rs/clusters/logging/log-security.md
> RS: Update log rotation default config to reduce filling disk space with logs

- content/operate/rs/release-notes/rs-7-4-2-releases/_index.md
- content/operate/rs/release-notes/rs-7-4-2-releases/rs-7-4-6-22.md
> RS: Clarify upgrade paths note in release notes

- content/operate/rs/networking/port-configurations.md
> RS: Add cluster_wd exporter port 3349 to reserved ports

- content/operate/kubernetes/release-notes/7-2-4-releases/7-2-4-12-08-2024.md
> K8s: Roosevelt maint 2 release notes

- content/operate/rs/references/cli-utilities/rladmin/tune.md
- content/operate/rs/references/rest-api/objects/cluster_settings.md
> RS: Add default_oss_sharding policy to REST API and rladmin references

- content/integrate/redis-data-integration/ingest/installation/_index.md
[DOC-4130](https://redislabs.atlassian.net/browse/DOC-4130)
[DOC-4130]: https://redislabs.atlassian.net/browse/DOC-4130?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DOC-4130 added warning about nm-cloud-setup.service to installer page

- .github/workflows/k8s_apis_sync.yaml
- content/operate/kubernetes/reference/kubernetes-api-reference-frontmatter.patch
- content/operate/kubernetes/reference/kubernetes-api-reference-template.tmpl
Contains fixes required as part of feedback on PR https://github.com/redis/docs/pull/523
> Fix k8s api docs generation

- content/integrate/redis-data-integration/ingest/release-notes/rdi-1-2-8.md
Copy of the notes recently added to the RDI repo.
> DOC-4140 add release notes for RDI v1.2.8

- content/integrate/terraform-provider-for-redis-cloud/_index.md
> RC: Add Transit Gateway attachment resource to Terraform

- content/develop/data-types/hashes.md
> DEV: fix typo in HFE example

- content/operate/rc/_index.md
> RC: Update first sentence of landing page to remove redundant text

- content/operate/rs/release-notes/rs-7-4-2-releases/rs-7-4-6-22.md
> RS: Copy LDAP URI validation change to version changes section of 7.4.6-22 release notes

- content/operate/rs/references/cli-utilities/rladmin/tune.md
- content/operate/rs/references/rest-api/objects/bdb/_index.md
> RS: Clarify master_persistence is in addition to replica persistence

- content/operate/rs/databases/import-export/export-data.md
- content/operate/rs/databases/import-export/import-data.md
> RS: Clarify export DB and import DB instructions

- content/integrate/redis-data-integration/ingest/installation/_index.md
[DOC-4222](https://redislabs.atlassian.net/browse/DOC-4222)
[DOC-4222]: https://redislabs.atlassian.net/browse/DOC-4222?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DOC-4222 added warning about previous RS installation

- content/operate/rc/subscriptions/view-essentials-subscription/essentials-plan-details.md
> RC: Add limitation sentence for essentials plans

- content/operate/rs/references/rest-api/objects/user.md
> RS: Fix role_uids description in user REST API reference

- content/operate/rc/security/cidr-whitelist.md
> Fix typo in cidr-whitelist.md

- content/develop/interact/search-and-query/query/exact-match.md
[DOC-4194](https://redislabs.atlassian.net/browse/DOC-4194)
[DOC-4194]: https://redislabs.atlassian.net/browse/DOC-4194?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DEV: add TCEs to query > exact match page

- .github/workflows/main-staging.yml
Every versioned folder will be built separately and synched to the right location on the bucket
> DOC-4273 Add support for versioned products in staging bucket

- content/operate/rc/supported-regions.md
> RC: Mark eu-west-1 as supported for essentials

- layouts/partials/tabs/wrapper.html
Fixes #659.
For example: https://redis.io/docs/staging/DOC-4289-tabs-error/develop/data-types/strings/
> DOC-4289 fix issues with TCE tabs

- build/components/markdown.py
- build/update_cmds.py
[DOC-3884](https://redislabs.atlassian.net/browse/DOC-3884)
Adding a new command called `build/update_cmds.py` that will make updates to command page front matter based on automated changes to `data/commands_core.json`. Also includes a necessary change to build/components/Markdown.py.
[DOC-3884]: https://redislabs.atlassian.net/browse/DOC-3884?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> INF: add new command to update command pages from commands_core.json

- content/commands/readwrite/index.md
#DOC-4215 fix typo in description & summary
> Update READWRITE index.md to fix typo

- content/integrate/uptrace-with-redis-enterprise/_index.md
#DOC-3920 remove duplicate description
> Update Uptrace _index.md

- content/develop/connect/clients/java/jedis.md
We released Jedis 5.2.0 GA https://github.com/redis/jedis/releases/tag/v5.2.0
> Update Jedis version to 5.2.0

- content/develop/connect/clients/client-side-caching.md
- content/develop/connect/clients/java/jedis.md
- content/develop/connect/clients/python/redis-py.md
[DOC-4314](https://redislabs.atlassian.net/browse/DOC-4314)
[DOC-4314]: https://redislabs.atlassian.net/browse/DOC-4314?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DOC-4314 added note about auto flush after disconnection

- content/operate/rs/clusters/maintenance-mode.md
#DOC-3362 add the word patching to the maint mode doc for search
> Update maintenance-mode.md with the word patching

- content/operate/rs/installing-upgrading/install/install-on-linux.md
#DOC-1622 make the filename clear for the rpm --checksig command step
> RS: clarify file for checksig command

- content/embeds/rc-tags-tag-module.md
> RC: Update tag minimum to 1 character

- content/integrate/terraform-provider-for-redis-cloud/_index.md
> RC: Add note to upgrade terraform provider to 1.8.1

- content/operate/rc/changelog/october-2024.md
> RC: CVE mention in changelog

- content/operate/rs/release-notes/rs-7-4-2-releases/rs-7-4-6-102.md
> RS 7.4.6-102 release notes

- content/operate/rs/release-notes/rs-6-4-2-releases/rs-6-4-2-115.md
> RS 6.4.2-115 release notes

- content/develop/data-types/bitfields.md
This fixes the issue https://github.com/redis/docs/issues/768
> fix typo in bitfields page

- content/operate/rs/installing-upgrading/quickstarts/docker-quickstart.md
Add an alias to fix a 404 from an old download center link.
> RS: Add alias to docker-quickstart.md

- content/operate/kubernetes/release-notes/6-4-2-releases/6-4-2-8-oct24.md
> K8s: 6.4.2-8 maint 3

- content/embeds/k8s-admission-webhook-cert.md
> K8s: fix admission controller bug

- content/operate/kubernetes/release-notes/7-4-6-releases/7-4-6-2-oct24.md
- content/operate/kubernetes/release-notes/7-4-6-releases/7-4-6-2-october24.md
> K8s: 7.4.6-2 unicorn maint release notes

- content/operate/kubernetes/release-notes/7-2-4-releases/7-2-4-12-10-24.md
> K8s: Roosevelt maint 3 release notes

- content/operate/kubernetes/release-notes/6-4-2-releases/6-4-2-8-oct24.md
- content/operate/kubernetes/release-notes/7-2-4-releases/7-2-4-12-10-24.md
> K8s: new csv numbers

- build/components/example.py
[DOC-4410](https://redislabs.atlassian.net/browse/DOC-4410)
Also added a comment type for PHP, which will soon be required.
[DOC-4410]: https://redislabs.atlassian.net/browse/DOC-4410?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DOC-4410 added SkipIfRedis test marker and PHP comment style

- content/commands/ft.config-set/index.md
> DEV: quick fix for incorrect link

- content/operate/oss_and_stack/stack-with-enterprise/release-notes/redisstack/_index.md
> OP: change version in Redis Stack relnotes heading

- content/glossary/_index.md
> Quick fix for LDAP link in glossary

- content/commands/ft.profile/index.md
[DOC-4346](https://redislabs.atlassian.net/browse/DOC-4346)
[DOC-4346]: https://redislabs.atlassian.net/browse/DOC-4346?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DEV: flesh out FT.PROFILE page

- static/images/rdi/ingest/ingest-config-folders.svg
[DOC-4519](https://redislabs.atlassian.net/browse/DOC-4519)
[DOC-4519]: https://redislabs.atlassian.net/browse/DOC-4519?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DOC-4519 fixed bugs in config folder diagram

- content/integrate/prometheus-with-redis-enterprise/prometheus-metrics-definitions.md
Cherry-picking @maayanagranat's commit from https://github.com/redis/docs/pull/861 to avoid merge conflicts.
> Add 'type' to endpoint Prometheus metrics

- content/develop/clients/client-side-caching.md
[DOC-4559](https://redislabs.atlassian.net/browse/DOC-4559)
[DOC-4559]: https://redislabs.atlassian.net/browse/DOC-4559?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DOC-4559 add list of CSC clients

- content/integrate/redis-data-integration/data-pipelines/transform-examples/redis-add-field-example.md
- content/integrate/redis-data-integration/data-pipelines/transform-examples/redis-remove-field-example.md
> DOC-4578 fixed broken links

- content/operate/rs/7.4/_index.md
[DOC-4573](https://redislabs.atlassian.net/browse/DOC-4573)
For staging links that correctly show the expected banner, see the comments in [DOC-4573](https://redislabs.atlassian.net/browse/DOC-4573).
[DOC-4573]: https://redislabs.atlassian.net/browse/DOC-4573?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DOC-4573]: https://redislabs.atlassian.net/browse/DOC-4573?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> RS: Add banner to RS 7.4 versioned docs

- content/operate/rs/references/cli-utilities/rladmin/status.md
> RS: Explain *node's meaning in rladmin status output

- content/develop/clients/php/_index.md
- content/develop/clients/php/connect.md
[DOC-4587](https://redislabs.atlassian.net/browse/DOC-4587)
[DOC-4587]: https://redislabs.atlassian.net/browse/DOC-4587?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DOC-4587 added PHP connection info to basic examples

- content/develop/whats-new/index.md
[DOC-4503](https://redislabs.atlassian.net/browse/DOC-4503)
I only went back to Q3CY2024. @andy-stark-redis: feel free to add anything you think I've missed.
[DOC-4503]: https://redislabs.atlassian.net/browse/DOC-4503?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DEV: add new what's new page

- content/develop/tools/insight/_index.md
[DOC-4589](https://redislabs.atlassian.net/browse/DOC-4589)
[DOC-4589]: https://redislabs.atlassian.net/browse/DOC-4589?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DEV: add db analysis caveat

- content/operate/rs/7.4/references/cli-utilities/crdb-cli/task/cancel.md
- content/operate/rs/references/cli-utilities/crdb-cli/task/cancel.md
> RS: Fix crdb-cli task cancel syntax

- content/operate/rs/release-notes/rs-7-8-releases/_index.md
- content/operate/rs/release-notes/rs-7-8-releases/rs-7-8-2-34.md
DOC-4593
1. [RS 7.8.2 index page's known issues](https://redis.io/docs/staging/DOC-4593/operate/rs/release-notes/rs-7-8-releases/#known-issues)
2. [RS 7.8.2-34 known issues](https://redis.io/docs/staging/DOC-4593/operate/rs/release-notes/rs-7-8-releases/rs-7-8-2-34/#known-issues)
> RS: Add Sentinel known issue to 7.8.2-34 release notes

- content/commands/json.arrtrim/index.md
"key" should be an array, not an array[array]
> "key" type error

- content/integrate/redis-data-integration/data-pipelines/deploy.md
[DOC-4598](https://redislabs.atlassian.net/browse/DOC-4598)
Updates based on feedback on an earlier PR after it was merged.
[DOC-4598]: https://redislabs.atlassian.net/browse/DOC-4598?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DOC-4598 updated K8s secrets commands based on feedback

- content/operate/kubernetes/7.4.6/_index.md
- content/operate/kubernetes/upgrade/_index.md
- content/operate/kubernetes/upgrade/openshift-cli.md
- content/operate/kubernetes/upgrade/upgrade-olm.md
- content/operate/kubernetes/upgrade/upgrade-redis-cluster.md
> K8s: fix broken links

- content/embeds/hardware-requirements-embed.md
DOC-4029
Staged preview: https://redis.io/docs/staging/DOC-4029/operate/rs/installing-upgrading/install/plan-deployment/hardware-requirements/
> RS: Add static IP requirement

- content/develop/use/patterns/distributed-locks.md
[DOC-4641](https://redislabs.atlassian.net/browse/DOC-4641)
Closes #947 
[DOC-4641]: https://redislabs.atlassian.net/browse/DOC-4641?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DOC-4641 added redlock implementation to the list

- content/operate/kubernetes/7.4.6/security/manage-rec-credentials.md
- content/operate/kubernetes/security/manage-rec-credentials.md
> K8s: Fix links pointing to old commit

- content/commands/client-list/index.md
- content/commands/info/index.md
- https://github.com/redis/redis/pull/13665
- https://github.com/redis/redis/pull/13703
> async io threads

- content/operate/kubernetes/release-notes/7-8-2-releases/7-8-2-6-jan25.md
Staging links:
https://redis.io/docs/staging/DOC-4625/operate/kubernetes/release-notes/7-8-2-releases/7-8-2-6-jan25
> K8s: Viking maint 1 release notes

- content/operate/rc/supported-regions.md
> RC: Update Essentials region availability

- content/operate/oss_and_stack/stack-with-enterprise/release-notes/redisjson/redisjson-2.4-release-notes.md
- content/operate/oss_and_stack/stack-with-enterprise/release-notes/redisjson/redisjson-2.6-release-notes.md
- content/operate/oss_and_stack/stack-with-enterprise/release-notes/redisjson/redisjson-2.8-release-notes.md
[DOC-4695](https://redislabs.atlassian.net/browse/DOC-4695)
[DOC-4695]: https://redislabs.atlassian.net/browse/DOC-4695?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OP: add RedisJSON release notes

- content/operate/oss_and_stack/stack-with-enterprise/release-notes/redisbloom/redisbloom-2.4-release-notes.md
- content/operate/oss_and_stack/stack-with-enterprise/release-notes/redisbloom/redisbloom-2.6-release-notes.md
- content/operate/oss_and_stack/stack-with-enterprise/release-notes/redisbloom/redisbloom-2.8-release-notes.md
- content/operate/oss_and_stack/stack-with-enterprise/release-notes/redisearch/redisearch-2.10-release-notes.md
- content/operate/oss_and_stack/stack-with-enterprise/release-notes/redisearch/redisearch-2.6-release-notes.md
- content/operate/oss_and_stack/stack-with-enterprise/release-notes/redisearch/redisearch-2.8-release-notes.md
- content/operate/oss_and_stack/stack-with-enterprise/release-notes/redistimeseries/redistimeseries-1.10-release-notes.md
- content/operate/oss_and_stack/stack-with-enterprise/release-notes/redistimeseries/redistimeseries-1.12-release-notes.md
- content/operate/oss_and_stack/stack-with-enterprise/release-notes/redistimeseries/redistimeseries-1.8-release-notes.md
[DOC-4698](https://redislabs.atlassian.net/browse/DOC-4698)
[DOC-4698]: https://redislabs.atlassian.net/browse/DOC-4698?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OP: add relnotes for search, bloom, and time series

- content/integrate/redis-data-integration/data-pipelines/deploy.md
[DOC-4609](https://redislabs.atlassian.net/browse/DOC-4609)
[DOC-4609]: https://redislabs.atlassian.net/browse/DOC-4609?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> INT: improve K8s secret setting page

- content/operate/rc/subscriptions/maintenance/set-maintenance-windows.md
> RC: Skip maintenance changes

- content/operate/oss_and_stack/stack-with-enterprise/search/scalable-query-best-practices.md
[DOC-4718](https://redislabs.atlassian.net/browse/DOC-4718)
[DOC-4718]: https://redislabs.atlassian.net/browse/DOC-4718?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> RS: Fix typo in search code example

- layouts/partials/footer.html
- layouts/partials/header/products-dropdown.html
- layouts/partials/header/products-mobile.html
- layouts/partials/header/resources-dropdown.html
- layouts/partials/header/resources-mobile.html
Missed the new footer font in the last PR for the footer. It should be sans-serif, not mono.
> fix: footer font is font-sans not font-mono

- content/commands/incrbyfloat/index.md
[DOC-4729](https://redislabs.atlassian.net/browse/DOC-4729)
[DOC-4729]: https://redislabs.atlassian.net/browse/DOC-4729?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DEV: fix code example on INCRBYFLOAT command page

- content/integrate/redis-data-integration/release-notes/rdi-1-4-4.md
[DOC-4737](https://redislabs.atlassian.net/browse/DOC-4737)
Just a copy of the release notes from the [RDI repo](https://github.com/RedisLabs/redis-data-integration/blob/main/release-notes.md).
[DOC-4737]: https://redislabs.atlassian.net/browse/DOC-4737?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DOC-4737 RDI release notes for v1.4.4

- content/integrate/datadog-with-redis-cloud/_index.md
- content/integrate/datadog-with-redis-enterprise/_index.md
- content/operate/rs/installing-upgrading/install/plan-deployment/supported-platforms.md
[DOC-4739](https://redislabs.atlassian.net/browse/DOC-4739). Fixes #1058.
[DOC-4739]: https://redislabs.atlassian.net/browse/DOC-4739?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> INT+RS: fix a few bugs

- content/integrate/redis-data-integration/data-pipelines/prepare-dbs/sql-server.md
[DOC-4744](https://redislabs.atlassian.net/browse/DOC-4744)
Basically just George's updates [from the RDI doc repo](https://github.com/loriotpiroloriol/docs/blob/main/content/integrate/redis-data-integration/data-pipelines/prepare-dbs/sql-server.md) with a couple of minor changes for our doc markup.
[DOC-4744]: https://redislabs.atlassian.net/browse/DOC-4744?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DOC-4744 added updated SQL Server prep instructions

- content/operate/rc/databases/configuration/clustering.md
[DOC-4778](https://redislabs.atlassian.net/browse/DOC-4778)
Fixes #1100.
[DOC-4778]: https://redislabs.atlassian.net/browse/DOC-4778?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> RC: Fix bug on Clustering Redis Databases page

- layouts/partials/footer.html
- layouts/partials/header/products-dropdown.html
- layouts/partials/header/resources-dropdown.html
> fix: top nav subnav spacing and footer overlay

- content/embeds/port-53.md
- content/operate/rs/7.4/installing-upgrading/install/prepare-install/port-availability.md
- content/operate/rs/7.4/installing-upgrading/quickstarts/redis-enterprise-software-quickstart.md
- content/operate/rs/7.4/networking/port-configurations.md
- content/operate/rs/installing-upgrading/install/prepare-install/port-availability.md
- content/operate/rs/installing-upgrading/quickstarts/redis-enterprise-software-quickstart.md
- content/operate/rs/networking/port-configurations.md
> RS: Port 53 must be available for RS installation on any OS

- content/operate/rs/installing-upgrading/upgrading/upgrade-os.md
> RS: Fix module prerequisites for OS upgrade

- content/operate/rs/networking/port-configurations.md
> RS: Removed port 36380 from reserved ports

- content/develop/clients/go/queryjson.md
Adapted from [this PR](https://github.com/redis/docs/pull/1125) contributed by a user.
> DOC-4809 Go query engine RESP2 note

- content/commands/info/index.md
[DOC-4823](https://redislabs.atlassian.net/browse/DOC-4823)
Fixes #1135.
[DOC-4823]: https://redislabs.atlassian.net/browse/DOC-4823?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DEV: fix memory stat description in the INFO command

- README.md
- content/develop/data-types/hashes.md
- content/integrate/redis-data-integration/_index.md
- content/operate/rs/7.4/databases/memory-performance/memory-limit.md
- content/operate/rs/databases/memory-performance/memory-limit.md
- layouts/commands/single.html
- layouts/develop/list.html
- layouts/develop/single.html
- layouts/glossary/list.html
- layouts/glossary/single.html
- layouts/integrate/single.html
- layouts/integration/list.html
- layouts/integration/single.html
- layouts/operate/list.html
- layouts/operate/single.html
- layouts/partials/css.html
- layouts/shortcodes/table-csv.html
These changes are necessary for us to use recent hugo versions (at some point one of the hugo releases introduced breaking changes).
> Update repo for compatibility with recent hugo versions

- .github/workflows/main-staging.yml
- .github/workflows/main.yml
- Makefile
Blocked by https://github.com/redis/docs/pull/1121
> Upgrade hugo version

- content/operate/oss_and_stack/stack-with-enterprise/release-notes/redisearch/redisearch-2.10-release-notes.md
- content/operate/oss_and_stack/stack-with-enterprise/release-notes/redisearch/redisearch-2.6-release-notes.md
- content/operate/oss_and_stack/stack-with-enterprise/release-notes/redisearch/redisearch-2.8-release-notes.md
[DOC-4828](https://redislabs.atlassian.net/browse/DOC-4828)
[DOC-4828]: https://redislabs.atlassian.net/browse/DOC-4828?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OP: add RediSearch v2.8.23, v2.10.12, and v2.6.26 release notes

- content/commands/smove/index.md
[DOC-4839](https://redislabs.atlassian.net/browse/DOC-4839)
Fixes #1151.
[DOC-4839]: https://redislabs.atlassian.net/browse/DOC-4839?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DEV: correct SMOVE return info

- content/embeds/rc-pro-use-cases-billing-units.md
- content/operate/rc/changelog/february-2025.md
> RC: Pico billing unit

- content/operate/rs/7.4/_index.md
- content/operate/rs/_index.md
> RS: Add archived docs links to RS index page

- content/integrate/prometheus-with-redis-enterprise/prometheus-metrics-definitions.md
- content/integrate/prometheus-with-redis-enterprise/prometheus-metrics-v1-to-v2.md
- content/integrate/prometheus-with-redis-enterprise/prometheus-metrics-v1.md
> Copy v1 Prometheus metrics to separate page

- content/develop/get-started/data-store.md
- content/develop/get-started/document-database.md
- content/develop/get-started/rag.md
- content/develop/get-started/redis-in-ai.md
- content/develop/get-started/vector-database.md
- content/operate/rc/databases/monitor-performance.md
- content/operate/rc/rc-quickstart.md
- content/operate/rc/security/_index.md
- content/operate/rc/security/aws-transit-gateway.md
- content/operate/rc/security/cidr-whitelist.md
- content/operate/rc/security/database-security/_index.md
- content/operate/rc/security/encryption-at-rest.md
- content/operate/rc/security/private-service-connect.md
- content/operate/rc/security/shared-responsibility-model.md
- content/operate/rc/security/vpc-peering.md
- content/operate/rs/_index.md
- content/operate/rs/databases/connect/_index.md
- content/operate/rs/databases/create.md
- content/operate/rs/databases/import-export/import-data.md
- content/operate/rs/installing-upgrading/quickstarts/redis-enterprise-software-quickstart.md
- layouts/shortcodes/university-links.html
- static/resources/redisuniversity.yaml
This makes it easier to batch edit links
> Simplify injection of Redis University links

- content/integrate/redis-data-integration/_index.md
[DOC-4858](https://redislabs.atlassian.net/browse/DOC-4858)
[DOC-4858]: https://redislabs.atlassian.net/browse/DOC-4858?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DOC-4858 fixed broken link to CRDB page

- content/commands/ft._list/index.md
- content/commands/ft.aliasadd/index.md
- content/commands/ft.aliasdel/index.md
- content/commands/ft.aliasupdate/index.md
- content/commands/ft.alter/index.md
- content/commands/ft.config-get/index.md
- content/commands/ft.config-help/index.md
- content/commands/ft.config-set/index.md
- content/commands/ft.create/index.md
- content/commands/ft.cursor-del/index.md
- content/commands/ft.cursor-read/index.md
- content/commands/ft.dictadd/index.md
- content/commands/ft.dictdel/index.md
- content/commands/ft.dictdump/index.md
- content/commands/ft.dropindex/index.md
- content/commands/ft.explain/index.md
- content/commands/ft.explaincli/index.md
- content/commands/ft.info/index.md
- content/commands/ft.profile/index.md
- content/commands/ft.search/index.md
- content/commands/ft.spellcheck/index.md
- content/commands/ft.sugadd/index.md
- content/commands/ft.sugdel/index.md
- content/commands/ft.sugget/index.md
- content/commands/ft.suglen/index.md
- content/commands/ft.syndump/index.md
- content/commands/ft.synupdate/index.md
- content/commands/ft.tagvals/index.md
[DOC-4853](https://redislabs.atlassian.net/browse/DOC-4853)
Hi @raz-mon. I've updated the ACL categories for all the search commands according to the [document you linked to me](https://redislabs.atlassian.net/wiki/x/lwVrJQE). Please take a look.
[DOC-4853]: https://redislabs.atlassian.net/browse/DOC-4853?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DEV: update ACL categories for search commands

- content/integrate/redis-data-integration/data-pipelines/data-pipelines.md
[DOC-4863](https://redislabs.atlassian.net/browse/DOC-4863)
[DOC-4863]: https://redislabs.atlassian.net/browse/DOC-4863?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DOC-4863 update config.yaml example

- content/operate/rs/7.4/references/rest-api/objects/services_configuration/_index.md
- content/operate/rs/7.4/references/rest-api/objects/services_configuration/alert_mgr.md
- content/operate/rs/references/rest-api/objects/services_configuration/_index.md
- content/operate/rs/references/rest-api/objects/services_configuration/alert_mgr.md
- content/operate/rs/references/rest-api/objects/services_configuration/entraid_agent_mgr.md
- content/operate/rs/references/rest-api/objects/services_configuration/ldap_agent_mgr.md
> RS: Add missing optional services to services config REST API object

- content/integrate/redis-data-integration/data-pipelines/prepare-dbs/aws-aur-pgsql.md
[DOC-4884](https://redislabs.atlassian.net/browse/DOC-4884)
[DOC-4884]: https://redislabs.atlassian.net/browse/DOC-4884?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DOC-4884 clarified step in AWS Aurora prep instructions

- content/integrate/redis-data-integration/data-pipelines/prepare-dbs/aws-aur-pgsql.md
[DOC-4884](https://redislabs.atlassian.net/browse/DOC-4884)
Deja vu :-) More detail was requested by the original reporter after the first attempt was merged.
[DOC-4884]: https://redislabs.atlassian.net/browse/DOC-4884?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DOC-4884 RDI: clarify Aurora AWS prep instructions

- content/operate/oss_and_stack/stack-with-enterprise/release-notes/redisbloom/redisbloom-2.4-release-notes.md
- content/operate/oss_and_stack/stack-with-enterprise/release-notes/redisbloom/redisbloom-2.6-release-notes.md
- content/operate/oss_and_stack/stack-with-enterprise/release-notes/redisearch/redisearch-2.10-release-notes.md
- content/operate/oss_and_stack/stack-with-enterprise/release-notes/redisearch/redisearch-2.6-release-notes.md
- content/operate/oss_and_stack/stack-with-enterprise/release-notes/redisearch/redisearch-2.8-release-notes.md
[DOC-4900](https://redislabs.atlassian.net/browse/DOC-4900)
[DOC-4900]: https://redislabs.atlassian.net/browse/DOC-4900?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OP: add new Bloom and Search release notes

- content/develop/clients/nodejs/transpipe.md
[DOC-4560](https://redislabs.atlassian.net/browse/DOC-4560)
[DOC-4560]: https://redislabs.atlassian.net/browse/DOC-4560?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DOC-4560 JavaScript transaction/pipeline page

- content/integrate/redis-data-integration/reference/api-reference/openapi.json
- content/integrate/redis-data-integration/reference/cli/redis-di-add-context.md
- content/integrate/redis-data-integration/reference/cli/redis-di-configure-rdi.md
- content/integrate/redis-data-integration/reference/cli/redis-di-create.md
- content/integrate/redis-data-integration/reference/cli/redis-di-delete-all-contexts.md
- content/integrate/redis-data-integration/reference/cli/redis-di-delete-context.md
- content/integrate/redis-data-integration/reference/cli/redis-di-deploy.md
- content/integrate/redis-data-integration/reference/cli/redis-di-describe-job.md
- content/integrate/redis-data-integration/reference/cli/redis-di-dump-support-package.md
- content/integrate/redis-data-integration/reference/cli/redis-di-get-rejected.md
- content/integrate/redis-data-integration/reference/cli/redis-di-install.md
- content/integrate/redis-data-integration/reference/cli/redis-di-list-contexts.md
- content/integrate/redis-data-integration/reference/cli/redis-di-list-jobs.md
- content/integrate/redis-data-integration/reference/cli/redis-di-monitor.md
- content/integrate/redis-data-integration/reference/cli/redis-di-reset.md
- content/integrate/redis-data-integration/reference/cli/redis-di-scaffold.md
- content/integrate/redis-data-integration/reference/cli/redis-di-set-context.md
- content/integrate/redis-data-integration/reference/cli/redis-di-set-secret.md
- content/integrate/redis-data-integration/reference/cli/redis-di-start.md
- content/integrate/redis-data-integration/reference/cli/redis-di-status.md
- content/integrate/redis-data-integration/reference/cli/redis-di-stop.md
- content/integrate/redis-data-integration/reference/cli/redis-di-trace.md
- content/integrate/redis-data-integration/reference/cli/redis-di-upgrade.md
- content/integrate/redis-data-integration/reference/cli/redis-di.md
This pull request updates the autogenerated docs.
> Remove duplicate descriptions from CLI commands

- content/commands/ft.sugadd/index.md
- content/commands/ft.sugget/index.md
[DOC-4919](https://redislabs.atlassian.net/browse/DOC-4919)
[DOC-4919]: https://redislabs.atlassian.net/browse/DOC-4919?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DEV: remove deprecation notice from FT.SUGADD and FT.SUGGET

- content/develop/clients/dotnet/vecsearch.md
[DOC-4836](https://redislabs.atlassian.net/browse/DOC-4836)
@mortensi I've emphasised the Microsoft.ML approach so that people don't assume they need an Azure account to play around with this, but let me know if you think Azure needs more coverage (or indeed if you have any other feedback about this).
[DOC-4836]: https://redislabs.atlassian.net/browse/DOC-4836?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DOC-4836 added C# vector index/query example

- content/operate/rs/release-notes/rs-7-2-4-releases/rs-7-2-4-122.md
- content/operate/rs/release-notes/rs-7-2-4-releases/rs-7-2-4-tba.md
DOC-4908
- [RS 7.2.4-122 release notes](https://redis.io/docs/staging/DOC-4908/operate/rs/release-notes/rs-7-2-4-releases/rs-7-2-4-122/)
> RS: 7.2.4 Feb/March maintenance release

- content/operate/rs/release-notes/rs-7-4-2-releases/rs-7-4-6-232.md
- content/operate/rs/release-notes/rs-7-4-2-releases/rs-7-4-6-tba.md
DOC-4907
- [RS 7.4.6-232 release notes](https://redis.io/docs/staging/DOC-4907/operate/rs/release-notes/rs-7-4-2-releases/rs-7-4-6-232/)
> RS: 7.4.6 Feb/March maintenance release

- content/operate/rc/databases/configuration/clustering.md
- content/operate/rc/databases/create-database/create-pro-database-existing.md
> RC: Selecting use external endpoint blocks private endpoint

- content/develop/clients/go/vecsearch.md
[DOC-4941](https://redislabs.atlassian.net/browse/DOC-4941)
[DOC-4941]: https://redislabs.atlassian.net/browse/DOC-4941?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DOC-4941 fixed link to Go landing page

- content/embeds/rc-pro-billing-units.md
> RC: Remove pricing link

- content/develop/get-started/vector-database.md
[DOC-4943](https://redislabs.atlassian.net/browse/DOC-4943)
[DOC-4943]: https://redislabs.atlassian.net/browse/DOC-4943?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DOC-4943 added links from quickstart to vector examples

- content/operate/kubernetes/release-notes/7-2-4-releases/7-2-4-12-mar25.md
DOC-4945
Still need OLM bundle version number
> K8s: Roosevelt maintenance release 5

- config.toml
- content/integrate/redis-data-integration/release-notes/rdi-1-6-1.md
[DOC-4944](https://redislabs.atlassian.net/browse/DOC-4944)
[DOC-4944]: https://redislabs.atlassian.net/browse/DOC-4944?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DOC-4944 added release notes for v1.6.1

- content/operate/kubernetes/release-notes/7-4-6-releases/7-4-6-2-oct24.md
- content/operate/kubernetes/release-notes/7-4-6-releases/7-4-6-2-october24.md
- content/operate/kubernetes/release-notes/7-4-6-releases/7-4-6-2.md
- content/operate/kubernetes/release-notes/7-4-6-releases/7-4-6-6-dec24.md
- content/operate/kubernetes/release-notes/7-4-6-releases/7-4-6-6-mar25.md
- content/operate/kubernetes/release-notes/7-4-6-releases/_index.md
Staged preview: https://redis.io/docs/staging/DOC-4946/operate/kubernetes/release-notes/7-4-6-releases/7-4-6-6-mar25
> K8s: 7.4.6-6 unicorn maint 3 release notes

- content/develop/data-types/probabilistic/bloom-filter.md
[DOC-4975](https://redislabs.atlassian.net/browse/DOC-4975)
Fixes #1278.
[DOC-4975]: https://redislabs.atlassian.net/browse/DOC-4975?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DEV: fix 404 error on Bloom filter page

- content/develop/interact/search-and-query/advanced-concepts/query_syntax.md
- content/develop/interact/search-and-query/advanced-concepts/stemming.md
- content/operate/oss_and_stack/stack-with-enterprise/deprecated-features/graph/graph-quickstart.md
- content/operate/oss_and_stack/stack-with-enterprise/deprecated-features/triggers-and-functions/Debugging.md
- content/operate/oss_and_stack/stack-with-enterprise/deprecated-features/triggers-and-functions/concepts/Cluster_Support.md
[DOC-4994](https://redislabs.atlassian.net/browse/DOC-4994). Fixes a few links warnings possibly caused by #1266.
[DOC-4994]: https://redislabs.atlassian.net/browse/DOC-4994?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DEV/OP: fix a few broken links (warnings)

- content/operate/oss_and_stack/install/_index.md
[DOC-5008](https://redislabs.atlassian.net/browse/DOC-5008)
[DOC-5008]: https://redislabs.atlassian.net/browse/DOC-5008?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OP: add 'about' links to main Redis CE/Stack installation page

- config.toml
- content/integrate/redis-data-integration/installation/install-k8s.md
- content/integrate/redis-data-integration/installation/install-vm.md
- content/integrate/redis-data-integration/installation/upgrade.md
- content/integrate/redis-data-integration/release-notes/rdi-1-6-3.md
[DOC-5040](https://redislabs.atlassian.net/browse/DOC-5040)
[DOC-5040]: https://redislabs.atlassian.net/browse/DOC-5040?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DOC-5040 add release notes for v1.6.3

- content/operate/oss_and_stack/stack-with-enterprise/search/query-performance-factor.md
adjusting to the new search parameters from 7.4 onwards
> new threads parameter for search

- content/integrate/terraform-provider-for-redis-cloud/_index.md
> RC Terraform: Include PSC

- content/operate/redisinsight/configuration.md
Adding information to presetup database connections in Redis Insight using env variables or from a file.
Please do not merge it yet - we are planning to deliver it with the next release.
> Adding information to presetup database connections in Redis Insight

- content/commands/sadd/index.md
[DOC-4999](https://redislabs.atlassian.net/browse/DOC-4999)
[DOC-4999]: https://redislabs.atlassian.net/browse/DOC-4999?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DEV: add multi-add example to SADD command page

- content/operate/kubernetes/release-notes/7-8-6-releases/7-8-6-1-april2025.md
> K8s: Wisconsin maintenance 1 release notes

- content/operate/rc/databases/create-database/create-pro-database-existing.md
- content/operate/rc/databases/monitor-performance.md
- content/operate/rc/databases/view-edit-database.md
> RC: Move alerts table and add default value and accepted range

- content/operate/rs/release-notes/rs-7-8-releases/rs-7-8-6-36.md
DOC-5054
- [RS 7.8.6-36 release notes](https://redis.io/docs/staging/DOC-5054/operate/rs/release-notes/rs-7-8-releases/rs-7-8-6-36/)
> RS 7.8.6-36 April maintenance release notes

- config.toml
- content/integrate/redis-data-integration/installation/install-k8s.md
- content/integrate/redis-data-integration/installation/install-vm.md
- content/integrate/redis-data-integration/installation/upgrade.md
- content/integrate/redis-data-integration/release-notes/rdi-1-6-5.md
[DOC-5083](https://redislabs.atlassian.net/browse/DOC-5083)
[DOC-5083]: https://redislabs.atlassian.net/browse/DOC-5083?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DOC-5083 added release notes for RDI v1.6.5

- content/develop/whats-new/8-0-rc-1.md
[DOC-5085](https://redislabs.atlassian.net/browse/DOC-5085)
[DOC-5085]: https://redislabs.atlassian.net/browse/DOC-5085?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DEV: some quick touch ups on the Redis 8.0-RC1 page

- .github/workflows/main-staging.yml
- .github/workflows/main.yml
- .github/workflows/test_gcs_access.yml
This pull request configures workflows to use Workload Identity Federation to authenticate with gcloud, which is the recommended approach.
> Change github actions authentication to use workload identity federation

- content/develop/ai/index.md
https://redis.slack.com/archives/C03SPBRDECU/p1744911174442489
> DEV: fix typo on AI page

- content/develop/data-types/json/ram.md
[DOC-5114](https://redislabs.atlassian.net/browse/DOC-5114)
[DOC-5114]: https://redislabs.atlassian.net/browse/DOC-5114?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DEV: add disclaimer to recently updated JSON memory usage page

- content/develop/tools/insight/release-notes/v2.8.0.md
- content/operate/kubernetes/7.8.6/kubernetes-archive.md
- content/operate/kubernetes/kubernetes-archive.md
[DOC-5115](https://redislabs.atlassian.net/browse/DOC-5115)
[DOC-5115]: https://redislabs.atlassian.net/browse/DOC-5115?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DEV+OP: fix a few bad links reported by the SEO team

- content/develop/data-types/lists.md
[DOC-5116](https://redislabs.atlassian.net/browse/DOC-5116)
Fixes #1435.
[DOC-5116]: https://redislabs.atlassian.net/browse/DOC-5116?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DEV: fix bug on list dt page

- content/operate/oss_and_stack/install/archive/install-redis/_index.md
add link to Redis Insight DOC-5006
> DOC-5006 add RI link to CE page

- layouts/partials/header.html
Staging link: https://redis.io/docs/staging/DOC-5086
> Add redis for AI button

- config.toml
- content/integrate/redis-data-integration/installation/install-k8s.md
- content/integrate/redis-data-integration/installation/install-vm.md
- content/integrate/redis-data-integration/installation/upgrade.md
- content/integrate/redis-data-integration/release-notes/rdi-1-6-6.md
[DOC-5129](https://redislabs.atlassian.net/browse/DOC-5129)
[DOC-5129]: https://redislabs.atlassian.net/browse/DOC-5129?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DOC-5129 added RDI release notes for v1.6.6

- content/operate/rc/cloud-integrations/_index.md
Dependent on #1327 (releasing 4/27).
> RC: Fix Marketplace account pages

- content/operate/rs/release-notes/rs-7-8-releases/rs-7-8-6-60.md
> RS: Added Ubuntu 22 checksum to 7.8.6 April maintenance release notes

- README.md
[DOC-5173](https://redislabs.atlassian.net/browse/DOC-5173)
[DOC-5173]: https://redislabs.atlassian.net/browse/DOC-5173?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SITE: remove licensing blurb from README.md

- content/develop/interact/search-and-query/_index.md
> Update RQE _index.md

- content/operate/rs/references/rest-api/objects/node.md
> RS: Added bigstore_enabled to node REST API reference

- layouts/develop/list.html
[DOC-5255](https://redislabs.atlassian.net/browse/DOC-5255)
[DOC-5255]: https://redislabs.atlassian.net/browse/DOC-5255?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DEV: isolate CLI widget to primary list page only

- content/develop/data-types/lists.md
[DOC-5268](https://redislabs.atlassian.net/browse/DOC-5268)
[DOC-5268]: https://redislabs.atlassian.net/browse/DOC-5268?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DEV: fix bug on list datatype page

- content/develop/ai/_index.md
- static/images/ai-LLM-memory.svg
- static/images/ai-brain-2.svg
- static/images/ai-brain.svg
- static/images/ai-cube.svg
- static/images/ai-lib.svg
- static/images/ai-model.svg
- static/images/ai-search.svg
- static/images/ai-semantic-routing.svg
DOC-5251 and this also removes duplicate links to notebooks and integrations blogs that are now in the child pages
> Replace PNG icons with high-resolution SVG icons and update AI page

- content/operate/oss_and_stack/install/_index.md
- content/operate/oss_and_stack/install/install-stack/_index.md
> DOC-5260: Add Redis Insight paragraph to installation pages

- content/operate/rs/7.4/databases/auto-tiering/_index.md
- content/operate/rs/7.8/databases/auto-tiering/_index.md
- content/operate/rs/databases/auto-tiering/_index.md
Fixes https://github.com/redis/docs/issues/1607
> RS: Fixed instances typo in auto tiering docs

- content/operate/rs/databases/import-export/flush.md
> DOC-430: Add instructions for flushing OSS Cluster API databases

- content/operate/rs/references/terminology.md
> DOC-1085: Add links to terminology page sections

- content/integrate/redis-data-integration/data-pipelines/transform-examples/redis-set-key-name.md
This PR adds examples of how to dynamically set the key name based on the input, for both the standard and full row formats.
Related ticket: https://redislabs.atlassian.net/browse/RDSC-3618
> RDSC-3618: How to set the key name in target

- content/integrate/redis-data-integration/data-pipelines/data-pipelines.md
- content/integrate/redis-data-integration/data-pipelines/transform-examples/redis-row-format.md
I have noticed some discrepancies between the documentation and the actual behavior and fixed them and added more detailed example.
> Improving documentation regarding full row format and operation codes

- content/operate/rs/release-notes/rs-7-8-releases/_index.md
- content/operate/rs/release-notes/rs-7-8-releases/rs-7-8-6-95.md
- content/operate/rs/release-notes/rs-7-8-releases/rs-7-8-6-tba.md
> RS 7.8.6 May maintenance release notes

- content/operate/rs/clusters/logging/diagnostic-logging.md
> RS: Fixed link anchor for diagnostic logging API reference

- content/operate/kubernetes/release-notes/7-22-0-releases/7-22-0-11-june2025.md
- content/operate/kubernetes/release-notes/7-22-0-releases/7-22-0-7-april2025.md
- content/operate/kubernetes/release-notes/7-22-0-releases/_index.md
> K8s: xwing maint release notes

- content/develop/clients/redis-py/transpipe.md
Fixed repetition in the _Watch keys for changes_ chapter
> repetition in transpipe documentation

- content/operate/kubernetes/release-notes/7-2-4-releases/7-2-4-12-june25.md
- content/operate/kubernetes/release-notes/7-2-4-releases/7-2-4-12-mar25.md
> K8s: 7.2.4-12 june maint

- content/operate/rs/release-notes/rs-7-4-2-releases/_index.md
- content/operate/rs/release-notes/rs-7-4-2-releases/rs-7-4-6-268.md
> RS: 7.4.6 June maintenance release notes

- content/operate/kubernetes/release-notes/7-4-6-releases/7-4-6-6-june25.md
- content/operate/kubernetes/release-notes/7-4-6-releases/7-4-6-6-mar25.md
> K8s: unicorn maint 5 release notes

- content/develop/clients/jedis/prob.md
- content/develop/clients/redis-py/prob.md
[DOC-5227](https://redislabs.atlassian.net/browse/DOC-5227)
Jedis version of [this page](https://redis.io/docs/latest/develop/clients/redis-py/prob/).
[DOC-5227]: https://redislabs.atlassian.net/browse/DOC-5227?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DOC-5227 Jedis probabilistic examples

- content/operate/rs/release-notes/rs-7-2-4-releases/rs-7-2-4-132.md
> RS 7.2.4 June maintenance release notes

- content/operate/rc/subscriptions/bring-your-own-cloud/iam-resources/aws-console.md
Just remove the expanders for now as folks are not finding the json policies behind the link.
> Update aws-console.md test

- content/commands/info.md
[DOC-5390](https://redislabs.atlassian.net/browse/DOC-5390)
[DOC-5390]: https://redislabs.atlassian.net/browse/DOC-5390?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DEV: update INFO command page with keysizes section info

- config.toml
- content/integrate/redis-data-integration/release-notes/rdi-1-12-1.md
[DOC-5397](https://redislabs.atlassian.net/browse/DOC-5397)
[DOC-5397]: https://redislabs.atlassian.net/browse/DOC-5397?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DOC-5397 added release notes for RDI v1.12.1

- content/operate/kubernetes/release-notes/7-8-6-releases/7-8-6-2-june2025.md
- content/operate/kubernetes/release-notes/7-8-6-releases/7-8-6-3-june2025.md
- content/operate/kubernetes/release-notes/7-8-6-releases/_index.md
> K8s: Wisconsin maint 4

- content/operate/kubernetes/re-clusters/multi-namespace.md
> K8s: alt role/rolebinding approach for multi-ns

- .github/workflows/redisvl_docs_sync.yaml
The workflow has to be updated following changes on the redisvl repo
> Update redisvl workflow

- content/operate/kubernetes/architecture/_index.md
> K8s: alias fix - add leading slash 

- content/operate/kubernetes/release-notes/7-22-0-releases/7-22-0-11-june2025.md
- content/operate/kubernetes/release-notes/7-22-0-releases/7-22-0-7-april2025.md
> K8s: add call home client to downloads

- content/commands/ts.range.md
[DOC-5476](https://redislabs.atlassian.net/browse/DOC-5476)
[DOC-5476]: https://redislabs.atlassian.net/browse/DOC-5476?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DEV: fix example bug on TS.RANGE page

- content/develop/clients/dotnet/prob.md
- content/develop/clients/dotnet/transpipe.md
- content/develop/clients/jedis/prob.md
- content/develop/clients/redis-py/prob.md
[DOC-5501](https://redislabs.atlassian.net/browse/DOC-5501)
This is required only for these single-language testable examples (the ones with a CLI example render without an error, even if some of the languages are missing). 
[DOC-5501]: https://redislabs.atlassian.net/browse/DOC-5501?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DOC-5501 temporary non-TCE examples

- content/operate/oss_and_stack/install/install-stack/apt.md
- content/operate/oss_and_stack/install/install-stack/rpm.md
People are confused by the downloads page in the on-page ratings feedback, and it isn't possible to update that Download button right now, so I think the best solution is to remove these links that are circular with the download button. 
Separately, I've requested the web team to make a text change to the download page to make it clear that no image will download when the button is clicked.
> 8.0 install update

- content/operate/oss_and_stack/stack-with-enterprise/release-notes/redisearch/redisearch-2.10-release-notes.md
[DOC-5521](https://redislabs.atlassian.net/browse/DOC-5521)
[DOC-5521]: https://redislabs.atlassian.net/browse/DOC-5521?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OP: update RediSearch release notes

- content/embeds/rs-prometheus-metrics-v2.md
- content/operate/rs/7.8/references/metrics/prometheus-metrics-v2.md
> Removed duplicate entry for redis_server_expired_keys metric

- content/commands/client-no-evict.md
- content/commands/client-no-touch.md
- content/commands/memory-malloc-stats.md
[DOC-5325](https://redislabs.atlassian.net/browse/DOC-5325)
[DOC-5325]: https://redislabs.atlassian.net/browse/DOC-5325?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DEV: add RESP2/3 return information to the remaining commands

- content/operate/kubernetes/release-notes/7-22-0-releases/7-22-0-11-june2025.md
- content/operate/kubernetes/release-notes/7-22-0-releases/7-22-0-15-july2025.md
- content/operate/kubernetes/release-notes/7-22-0-releases/7-22-0-16-august2025.md
- content/operate/kubernetes/release-notes/7-22-0-releases/_index.md
> K8s: yellow sub maint 1

- content/operate/rs/7.4/references/rest-api/objects/crdb/database_config.md
- content/operate/rs/7.8/references/rest-api/objects/crdb/database_config.md
- content/operate/rs/references/rest-api/objects/crdb/database_config.md
Fixes https://github.com/redis/docs/issues/1808
> RS: Added missing module_list field to CRDB REST API references

- content/develop/clients/jedis/_index.md
> DOC-5661 updated Jedis install version

- content/operate/kubernetes/reference/api/redis_enterprise_active_active_database_api.md
- content/operate/kubernetes/reference/api/redis_enterprise_cluster_api.md
- content/operate/kubernetes/reference/api/redis_enterprise_database_api.md
- content/operate/kubernetes/reference/api/redis_enterprise_remote_cluster_api.md
> K8s: api aliases

- local_examples/tmp/lettuce-async/JsonExample.java
- local_examples/tmp/lettuce-reactive/JsonExample.java
More temporary local copies of these files, since it might be a while until the originals are merged.
> DOC-5378 DOC-4758 Lettuce JSON examples
