redis/docs

- content/integrate/amazon-bedrock/_index.md
- content/integrate/amazon-bedrock/create-agent.md
- content/integrate/amazon-bedrock/create-knowledge-base.md
- content/integrate/amazon-bedrock/set-up-redis.md
Ticket: [DOC-3046](https://redislabs.atlassian.net/browse/DOC-3046)
Staging link: 
https://redis.io/docs/staging/DOC-3046/integrate/amazon-bedrock/
> RC: Amazon bedrock stage 3 changes

- content/develop/connect/_index.md
- content/develop/connect/clients/_index.md
- content/develop/connect/insight/_index.md
- content/develop/connect/insight/tutorials/insight-stream-consumer.md
- content/develop/interact/programmability/triggers-and-functions/Quick_Start_RI.md
- content/integrate/amazon-bedrock/set-up-redis.md
- content/integrate/redisom-for-java/_index.md
- content/integrate/redisom-for-node-js/_index.md
- content/integrate/redisom-for-python/_index.md
- content/integrate/redisvl/overview/install.md
- content/operate/oss_and_stack/install/install-stack/docker.md
- content/operate/oss_and_stack/install/install-stack/mac-os.md
- content/operate/oss_and_stack/stack-with-enterprise/deprecated-features/graph/graph-quickstart.md
- content/operate/oss_and_stack/stack-with-enterprise/stack-quickstart.md
- content/operate/rc/_index.md
- content/operate/rc/databases/flush-data.md
- content/operate/rc/databases/monitor-performance.md
- content/operate/rc/rc-quickstart.md
- content/operate/redisinsight/_index.md
- content/operate/redisinsight/install/_index.md
- content/operate/redisinsight/install/env-variables.md
- content/operate/redisinsight/install/install-on-aws.md
- content/operate/redisinsight/install/install-on-docker.md
- content/operate/redisinsight/install/install-on-k8s.md
- content/operate/rs/databases/connect/_index.md
- content/operate/rs/databases/connect/test-client-connectivity.md
- content/operate/rs/references/cli-utilities/redis-cli/_index.md
- content/operate/rs/security/access-control/ldap/migrate-to-role-based-ldap.md
Ticket: [DOC-3613](https://redislabs.atlassian.net/browse/DOC-3613)
Staging link: https://redis.io/docs/staging/DOC-3615/
N.B. there might be one or more refs to RedisInsight on the home page (etc.), but Greg has a PR to address the home page.
> DOC-3615: change RedisInsight to Redis Insight

- content/embeds/rc-acls-note.md
- content/integrate/amazon-bedrock/set-up-redis.md
- content/operate/rc/security/access-control/data-access-control/active-active-roles.md
- content/operate/rc/security/access-control/data-access-control/create-roles.md
Ticket: DOC-2274
Staging link: 
https://redis.io/docs/staging/DOC-2274/operate/rc/security/access-control/data-access-control/active-active-roles/
https://redis.io/docs/staging/DOC-2274/operate/rc/security/access-control/data-access-control/create-roles/
> RC: Document that shards are eventually consistently updated with ACL-s

- build/components/component.py
The build process was doing a lot of useless work and making unnecessary changes to lots of Markdown files. This PR fixes that.
> LRC-160: cleanup build process

- .gitignore
Ticket: [DOC-3623](https://redislabs.atlassian.net/browse/DOC-3623)
Staged preview: None
Hide `build/components/__pycache__/*` files so they're invisible post-build.
> DOC-3623: update .gitignore

- content/develop/use/patterns/distributed-locks.md
Update `distributed_locks.md`: add new Ruby Implementation for Distributed Locks
---
Added new ruby implementation of Redis Distributed Locks `redis_queued_locks` to the Implementations list.
The new implementation realizes "lock request queues" feature.
Repository: https://github.com/0exp/redis_queued_locks
(This PR is a clone of the PR to the old docs: https://github.com/redis/redis-doc/pull/2706)
> Update `distributed_locks.md`: add new Ruby Implementation for Distributed Locks

- content/commands/bgrewriteaof/index.md
- content/commands/bgsave/index.md
- content/commands/config-set/index.md
- content/commands/save/index.md
Ticket: [DOC-3640](https://redislabs.atlassian.net/browse/DOC-3640)
Staging links:
https://redis.io/docs/staging/DOC-3640/commands/bgsave/
https://redis.io/docs/staging/DOC-3640/commands/bgrewriteaof/
https://redis.io/docs/staging/DOC-3640/commands/save/
https://redis.io/docs/staging/DOC-3640/commands/config-set/
While I did modify the links a bit, I'm not 100% this will work correctly on the main site. There may be some mischievous redirects at play.
> DOC-3640: fix commands links to persistence page

- content/commands/client-setinfo/index.md
Moved from https://github.com/redis/redis-doc/pull/2537
> Document lib-name suffix format used by official clients

- content/operate/oss_and_stack/stack-with-enterprise/release-notes/redisbloom/redisbloom-2.4-release-notes.md
- content/operate/oss_and_stack/stack-with-enterprise/release-notes/redisbloom/redisbloom-2.6-release-notes.md
- content/operate/oss_and_stack/stack-with-enterprise/release-notes/redisearch/redisearch-2.6-release-notes.md
- content/operate/oss_and_stack/stack-with-enterprise/release-notes/redisearch/redisearch-2.8-release-notes.md
Copying Lior's March updates for module release notes from the old repo https://github.com/RedisLabs/redislabs-docs/pull/3239.
- [Bloom 2.4](https://redis.io/docs/staging/module-release-notes/operate/oss_and_stack/stack-with-enterprise/release-notes/redisbloom/redisbloom-2.4-release-notes/)
- [Bloom 2.6](https://redis.io/docs/staging/module-release-notes/operate/oss_and_stack/stack-with-enterprise/release-notes/redisbloom/redisbloom-2.6-release-notes/)
- [Search 2.6](https://redis.io/docs/staging/module-release-notes/operate/oss_and_stack/stack-with-enterprise/release-notes/redisearch/redisearch-2.6-release-notes/)
- [Search 2.8](https://redis.io/docs/staging/module-release-notes/operate/oss_and_stack/stack-with-enterprise/release-notes/redisearch/redisearch-2.8-release-no …
> March release notes for Bloom and Search

- content/commands/keys/index.md
link to `Redis sets` page results in 404 error at the end of warning section in [https://redis.io/docs/latest/commands/keys/](https://redis.io/docs/latest/commands/keys/)
> fix broken link

- layouts/_default/baseof.html
LRC-324
I tested this locally by temporarily adding the same `link rel="canonical"` tag to the production environment check's `else` statement. When I viewed the page source on different sections of the site, I did see the expected `href` generated for each canonical link in the HTML head.
> LRC-324 Add canonicals to prod layout

- content/operate/rs/references/rest-api/requests/users/_index.md
DOC-3670
[Staged preview](https://redis.io/docs/staging/DOC-3670/operate/rs/references/rest-api/requests/users/)
> RS: Add role_uids to users REST API examples, remove name from PUT example since it can't be updated

- content/operate/rc/databases/configuration/clustering.md
Found this while reviewing RED-124082 (changing docs links on Cloud).
Staging link: https://redis.io/docs/staging/link-fixes/operate/rc/databases/configuration/clustering#dataset-size
> Changed #dataset-size to link to the memory limit section

- content/develop/get-started/data-store.md
- layouts/_default/section.html
- layouts/_default/taxonomy.html
- layouts/_default/term.html
- layouts/commands/list.html
Ticket: [DOC-3723](https://redislabs.atlassian.net/browse/DOC-3723)
[Staging link](https://redis.io/docs/staging/DOC-3723/)
These changes suppress the warnings normally seen when running `hugo serve` locally. Warnings, in general, annoy me. :)
@rrelledge One of the changes seems innocuous, but if you could take a look and let me know if it's okay. I don't see any difference in produced output. The change is in `layouts/commands/list.html@122`. I'm not sure what that line is doing/accomplishing, but it does generate the following Hugo warning:
`WARN 2024/05/01 10:04:21 .File.UniqueID on zero object. Wrap it in if or with: {{ with .File }}{{ .UniqueID }}{{ end }}`
> DOC-3723: suppress hugo serve warnings

- content/commands/ft.search/index.md
align the messaging (FT.AGGREGATE and FT.SEARCH) and make it more clear when a key expires during a query execution, what should be the expected behaviour. So the key name it's still return, but the value should be nil
> expiration fixes

- content/commands/ts.alter/index.md
LABELS argument itself is optional. But label-value pairs under it are not.
TS.ALTER should have same syntax as [TS.CREATE](https://github.com/redis/docs/blob/edda9a5364a2a4998c16cdb7de327fe7ac9307f7/content/commands/ts.create/index.md?plain=1#L77) and [TS.ADD](https://github.com/redis/docs/blob/edda9a5364a2a4998c16cdb7de327fe7ac9307f7/content/commands/ts.add/index.md?plain=1#L81). My suggestion here for TS.ALTER reflects the current syntax in both the other mentioned commands.
> Fix TS.ALTER syntax

- content/operate/kubernetes/re-clusters/expand-pvc.md
Preview: 
https://redis.io/docs/staging/DOC-3664/operate/kubernetes/re-clusters/expand-pvc/
> K8s: expand PVC

- content/integrate/redis-data-integration/installation/install-k8s.md
A missing anchor (actually fixed by David - thanks!) and a few shortcodes incorrectly written as "<{{..." rather than "{{<...".
Staging: https://redis.io/docs/staging/DOC-3747-rdi-doc-bugs/integrate/redis-data-integration/installation/install-k8s/
> DOC-3747 RDI doc bug fixes

- layouts/home.html
- layouts/partials/docs-nav-collapsed.html
- layouts/partials/docs-nav.html
Reverts redis/docs#168
The nav menu changes to re-order the sections and make them consistent are making browsing more difficult.
https://redis.io/docs/staging/revert-168-update-nav/
> Revert "Update nav to put Commands and APIs at the top of menu on all pages"

- layouts/partials/docs-nav.html
DOC-3699
https://redis.io/docs/staging/nav-arrows/operate/rc/cloud-integrations/
This removes the arrows and padding around them which makes the nesting really confusing in the doc nav menu.
> remove nav arrows and padding

- content/operate/rs/networking/cluster-lba-setup.md
[DOC-2495](https://redislabs.atlassian.net/browse/DOC-2495) and some copy edits
[Staged preview](https://redis.io/docs/staging/DOC-2495/operate/rs/networking/cluster-lba-setup/#configure-cluster)
> RS: Add default_non_sharded_proxy_policy all-nodes to cluster load balancer setup

- content/operate/rs/references/cli-utilities/rladmin/cluster/config.md
[Staged preview](https://redis.io/docs/staging/DOC-193/operate/rs/references/cli-utilities/rladmin/cluster/config/)
> RS: Fix typo for cm_session_timeout_minutes in rladmin cluster config reference

- content/develop/use/pipelining/index.md
Maybe I'm missing something, but provided code example doesn't work as advertised, redis client is not magically turning itself to pipelined version, and benchmark proves it.
verified with gem redis 5.2.0 and redis-client 0.22.1
> Fix pipelining example code

- content/operate/oss_and_stack/stack-with-enterprise/release-notes/redisearch/redisearch-2.8-release-notes.md
Ticket: [DOC-3795](https://redislabs.atlassian.net/browse/DOC-3795)
- https://redis.io/docs/staging/DOC-3795/operate/oss_and_stack/stack-with-enterprise/release-notes/redisearch/redisearch-2.8-release-notes/
Fixes #212.
> OP: add search v2.8.13 rel. notes

- layouts/commands/list.html
- layouts/commands/single.html
- layouts/develop/list.html
- layouts/develop/single.html
- layouts/home.html
- layouts/integrate/list.html
- layouts/integrate/single.html
- layouts/integration/list.html
- layouts/integration/single.html
- layouts/operate/list.html
- layouts/operate/single.html
- layouts/partials/footer.html
Here's the website with 1440px max-width and 1920px max-width on my machine, which has 2560px width:
> Set 1920px as the max-width

- layouts/integrate/list.html
I was going to add this to the previous menu-text PR, but it was merged before I could do so.
Staged preview link:
- https://redis.io/docs/staging/menu-text-2/integrate/
> update libraries and tools search fields to align with recent menu changes

- .github/workflows/autocomment.yaml
Currently the bot generates a link even for deleted files, such as `https://redis.io/docs/staging/DOC-3785-ext-client-libs/develop/connect/clients/go` in https://github.com/redis/docs/pull/228
> Do not generate a preview link for deleted files

- content/get-started/_index.md
This updates the get started page to align it with the text of the Products -> Source available main nav menu item. This also moves the install links to the top of the page as folks have complained these are harder to find with the redesign.
> Get started update

- content/operate/rs/references/rest-api/objects/cluster_settings.md
Fixing another table where the descriptions overflowed and were partially blocked by the "Edit this page/Create an issue" sidebar on the right.
> RS: Fix format of cluster settings table

- content/develop/connect/clients/dotnet.md
- content/develop/connect/clients/java/jedis.md
- content/develop/connect/clients/java/lettuce.md
- content/develop/connect/clients/nodejs.md
- content/develop/connect/clients/python.md
The headings were a bit badly organised in the client library pages (eg, it gave the impression of missing content in some places). These pages will be changed quite a lot in the near future but it seems worthwhile to make them clearer while we're waiting for the new versions.
> DOC-3809 fixed headings on client lib pages

- content/commands/ts.add/index.md
- content/commands/ts.decrby/index.md
- content/commands/ts.incrby/index.md
DUPLICATE_POLICY is accepted by TS.ADD , TS.DECRBY and TS.INCRBY.
For TS.CREATE and TS.ADD, we documented ENCODING config. For TS.INCRBY and TS.DECRBY, we documented UNCOMPRESSED config which is a legacy config and was deprecated. We replaced it with ENCODING and did not update the documentation.
> Update time series documentation

- content/operate/kubernetes/re-clusters/expand-pvc.md
> K8s: troubleshooting cmds, weight change

- content/operate/oss_and_stack/stack-with-enterprise/deprecated-features/graph/_index.md
It looks like the old `bannerLink` front matter we sometimes used on the old Enterprise docs site doesn't work on the new site. It's easier to fix this by moving the link directly into the `bannerText` since that seems to work fine. I didn't see `bannerLink` used anywhere else in the current docs, so this one should be the only issue.
> Fix broken link in graph deprecation banner

- content/develop/data-types/lists.md
In the basic commands section of Redis lists, `LRANGE` is missing.
> Add LRANGE command to the lists docs

- content/operate/rs/databases/auto-tiering/quickstart.md
DOC-593
The missing quick  start step was originally included in the [Auto Tiering installation](https://redis.io/docs/staging/DOC-593/operate/rs/installing-upgrading/install/install-on-linux/#auto-tiering-installation) section of the general Redis Enterprise Software installation instructions.
> RS: Add step to prepare and format flash to Auto Tiering quick start

- content/develop/data-types/hashes.md
- content/develop/use/keyspace-notifications.md
- content/operate/rc/changelog/august-2023.md
- content/operate/rs/security/certificates/ocsp-stapling.md
> Sundry link fixes

- data/components/redis_py.json
There is now a doctests folder in the master branch of redis-py, so this updates redis_py.json to point to that. (Not deleting emb-examples yet, btw, until we're sure we don't need it.)
> DOC-3801 update redis_py.json to point to master branch

- data/resp3_replies.json
The docs for `SINTER` are already correct. I verified this on my local Redis 7.2.5 server.
```
> hello 3
...
3# "proto" => (integer) 3
...
> sadd foo a
(integer) 1
> sadd foo b
(integer) 1
> sadd bar a
(integer) 1
> sinter foo bar
1~ "a"
> sdiff foo bar
1~ "b"
> sunion foo bar
1~ "a"
2~ "b"
```
> SDIFF and SUNION return sets in RESP3

- data/resp3_replies.json
Removed the second "the" from the following sentence (twice) to match the same sentence elsewhere.
```
the number of the elements in the resulting intersection.
^^^
```
> Minor grammar fix

- content/operate/rs/security/audit-events.md
Fixes https://github.com/redis/docs/issues/319 and DOC-3888
> RS: Fix auth request status in audit events

- content/integrate/redis-data-integration/ingest/data-pipelines/data-pipelines.md
Advanced properties docs and sample, based on a Slack thread.
> DOC-3901 add advanced props section to config.yaml docs

- content/integrate/redis-data-integration/ingest/data-pipelines/data-pipelines.md
Added information about transformations that was present in the [old docs](https://github.com/redis/docs/blob/DOC-3755-csharp-client-intro/content/integrate/redis-data-integration/data-transformation/data-transformation-pipeline.md) but lost from the new ingest docs.
I've dropped old sections that referred to MongoDB and Cassandra, since I believe these aren't available as ingest sources currently. I've also assumed that Redis is the only available target database type for ingest.
> DOC-3907 added transform info lost from the old docs

- content/operate/rc/cloud-archive.md
- content/operate/rc/supported-regions.md
> RC: Supported Cloud providers regions

- layouts/commands/list.html
- layouts/commands/single.html
Fixes #351. The `<section>` for the commands pages already has the `w-full` class but the containing div did not, meaning the central content of each page would not take up the full width available. This commit fixes this issue by adding the `w-full` class to the containing div.
These changes were tested to function on Firefox on Linux and Chrome on macOS, with additional verification that the pages looked the same on Safari on iOS and Chrome on Android.
> fix: commands pages take up full width available

- config.toml
Fixes redis/node-redis#2780.
This PR fixes a bug in the config.toml file that prevented Node.js TCEs from displaying.
> SITE-WIDE: fix bug that prevented Node.js examples from displaying

- content/develop/reference/modules/modules-api-ref.md
Update to modules-api-ref.md from redis/redis source code.
**Note to reviewers**: This document is generated by software, so any language anomalies or incorrect links will need to be fixed in the redis/redis source code, not here.
> DEV: update modules-api-ref.md for 7.4-rc2

- content/integrate/redis-data-integration/ingest/data-pipelines/data-pipelines.md
- content/integrate/redis-data-integration/ingest/installation/_index.md
New config properties for MySQL/MariaDB, PostgreSQL, and Oracle. I'll add any extra props for SQL Server if/when they become available.
> Doc 3910 db specific connect properties

- content/integrate/redis-data-integration/ingest/installation/_index.md
- content/integrate/redis-data-integration/ingest/reference/cli/redis-di-install.md
Added docs about the [silent install config file](https://redislabs.atlassian.net/wiki/spaces/RED/pages/4348903466/Configuration+file+for+the+silent+mode+installation).
> DOC-3917 added silent install docs

- content/operate/oss_and_stack/management/replication.md
Fix typos in `replication.md`: story -> history and many others
> Fix replication.md typo

- content/develop/interact/search-and-query/query/exact-match.md
Removed reference to DIALECT 5 and added example of new feature for exact matching of TAG with special chars.
> add explanation of double quotes for TAG special chars

- content/integrate/redis-data-integration/rdi-archive.md
Updated the RDI archive page to point to the correct link on the redis.com site (which is still available for now).
> DOC-3942 fixed archive link and text

- content/operate/rs/references/client_references/_index.md
Fixes one of the issues in [DOC-3830](https://redislabs.atlassian.net/browse/DOC-3830) (separate Jedis/Lettuce links). The other issue (reinstate Go links) was already fixed separately.
[DOC-3830]: https://redislabs.atlassian.net/browse/DOC-3830?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DOC-3830 fixed links to Jedis/Lettuce

- content/develop/interact/search-and-query/advanced-concepts/escaping.md
- content/develop/interact/search-and-query/advanced-concepts/query_syntax.md
- content/develop/interact/search-and-query/advanced-concepts/tags.md
[DOC-3909](https://redislabs.atlassian.net/browse/DOC-3909) mentions several confusing bits of text about tag fields and the situations where you need to escape characters when using them. This PR addresses these issues.
[DOC-3909]: https://redislabs.atlassian.net/browse/DOC-3909?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Doc 3909 improve tag query syntax docs

- content/develop/data-types/timeseries/clients.md
[DOC-3749](https://redislabs.atlassian.net/browse/DOC-3749) refers to several issues in this page that seems to have carried over some details from the recently-replaced docs site (and some over-complicated Markdown). The page is possibly worth keeping for now because the features for Go are in a separate library, not the usual Go client, so this should be noted somewhere.
[DOC-3749]: https://redislabs.atlassian.net/browse/DOC-3749?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DOC-3749 updated time series client lib list

- content/integrate/redis-data-integration/ingest/data-pipelines/data-denormalization.md
Update the RDI [data denormalisation](https://redis.io/docs/latest/integrate/redis-data-integration/ingest/data-pipelines/data-denormalization/) docs in line with a code bug fix. The new info is probably correct but still some confirmation required before merging.
> DOC-3957 update RDI nesting config example

- content/develop/connect/clients/java/lettuce.md
Added a section to the documentation of the Lettuce driver that specifically deals with timeouts.
The example given is of setting a socket timeouts that a few of our clients have requested recently to deal with connectivity issues. To give examples about all the timeouts would have perhaps been too verbose and some of them are very specific.
> Provide additional information for setting timeout settings when configuring the Lettuce driver

- content/develop/interact/search-and-query/query/exact-match.md
DIALECT 5 never materialized, so all references to it should point to DIALECT 2.
> DEV: fix remaining occurrences of DIALECT 5

- content/commands/expire/index.md
I removed the outdated description of the expiration algorithm, but I left in place the simpler explanation.
> DEV: remove outdated key expiration info

- content/develop/connect/insight/release-notes/v2.0.md
- content/operate/oss_and_stack/stack-with-enterprise/gears-v1/_index.md
- content/operate/oss_and_stack/stack-with-enterprise/gears-v1/jvm/classes/gearsbuilder/config-get.md
- content/operate/oss_and_stack/stack-with-enterprise/gears-v1/jvm/classes/readers/commandoverrider.md
- content/operate/oss_and_stack/stack-with-enterprise/gears-v1/jvm/commands/_index.md
- content/operate/oss_and_stack/stack-with-enterprise/gears-v1/jvm/recipes/write-behind.md
- content/operate/oss_and_stack/stack-with-enterprise/gears-v1/python/_index.md
- content/operate/oss_and_stack/stack-with-enterprise/gears-v1/python/quickstart.md
- content/operate/oss_and_stack/stack-with-enterprise/gears-v1/register-events.md
- content/operate/oss_and_stack/stack-with-enterprise/release-notes/redisgears/redisgears-1.0-release-notes.md
- content/operate/oss_and_stack/stack-with-enterprise/release-notes/redisgears/redisgears-1.2-release-notes.md
Here, I'm removing a bunch of bad links related to long deleted RedisGears v1 content (former redis.io). In some cases, particularly the Gears v1.2 release notes, I removed links, but left the link text. In other cases, I removed entire sentences.
> OP: remove more 404s related to RedisGears

- content/develop/reference/modules/modules-api-ref-frontmatter.patch
This patch will be used to add frontmatter content to the modules-api-ref.md file generated by redis
> Add frontmatter patch for modules-api-ref.md

- content/develop/connect/insight/_index.md
- layouts/develop/list.html
While reading the Redis Insight page, I noticed that the list page links at the bottom of the page were squished together on a single line. This PR applies the same patch that was made to the Operate and Integrate list view layouts.
> DEV: fix dev list page link squish bug

- content/commands/ft.create/index.md
[DOC-3343](https://redislabs.atlassian.net/browse/DOC-3343) basically just suggests a better page for the vector field "more info" to link to.
[DOC-3343]: https://redislabs.atlassian.net/browse/DOC-3343?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DOC-3343 fixed link to vector page

- content/commands/json.merge/index.md
[DOC-3043](https://redislabs.atlassian.net/browse/DOC-3043)
As well as the typo noted in the JIRA issue, there were a few other small glitches that were quick to fix while I was at it.
[DOC-3043]: https://redislabs.atlassian.net/browse/DOC-3043?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DOC-3043 fixed typo plus a few other small issues

- content/develop/data-types/json/path.md
[DOC-2606](https://redislabs.atlassian.net/browse/DOC-2606)
Default values of start, end, and step for an array slice.
[DOC-2606]: https://redislabs.atlassian.net/browse/DOC-2606?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DOC-2606 added info about JSON array slice defaults

- content/commands/expire/index.md
- content/develop/data-types/json/developer.md
- content/develop/data-types/probabilistic/bloom-filter.md
- content/develop/data-types/probabilistic/count-min-sketch.md
- content/develop/data-types/probabilistic/cuckoo-filter.md
- content/develop/interact/search-and-query/administration/design.md
- content/develop/interact/search-and-query/administration/extensions.md
- content/develop/interact/search-and-query/administration/gc.md
- content/develop/interact/search-and-query/administration/overview.md
- content/develop/interact/search-and-query/advanced-concepts/chinese.md
- content/develop/interact/search-and-query/advanced-concepts/highlight.md
- content/develop/interact/search-and-query/advanced-concepts/phonetic_matching.md
- content/develop/interact/search-and-query/advanced-concepts/scoring.md
- content/develop/interact/search-and-query/advanced-concepts/sorting.md
- content/develop/interact/search-and-query/advanced-concepts/spellcheck.md
- content/develop/interact/search-and-query/advanced-concepts/stemming.md
- content/develop/interact/search-and-query/advanced-concepts/stopwords.md
- content/develop/interact/search-and-query/advanced-concepts/synonyms.md
- content/develop/interact/search-and-query/deprecated/development.md
- content/develop/interact/search-and-query/deprecated/payloads.md
- content/develop/reference/modules/_index.md
- content/integrate/redis-data-integration/write-behind/installation/install-redis-gears.md
- content/integrate/redis-data-integration/write-behind/reference/config-yaml-reference.md
- content/operate/oss_and_stack/management/optimization/benchmarks/index.md
- content/operate/oss_and_stack/reference/internals/rdd.md
- content/operate/oss_and_stack/stack-with-enterprise/deprecated-features/triggers-and-functions/Configuration.md
- content/operate/redisinsight/proxy.md
DOC-3962
H1 elements that are not the article's title break our search and copilot. I went in and got as many as I could find.
> Remove/replace H1 elements in article body

- content/commands/wait/index.md
[DOC-1999](https://redislabs.atlassian.net/browse/DOC-1999)
The argument spec under Syntax seems to have been fixed already.
[DOC-1999]: https://redislabs.atlassian.net/browse/DOC-1999?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DOC-1999 improve argument description

- content/commands/geodist/index.md
- content/commands/georadius/index.md
- content/commands/georadius_ro/index.md
- content/commands/georadiusbymember/index.md
- content/commands/georadiusbymember_ro/index.md
- content/commands/geosearch/index.md
- content/commands/geosearchstore/index.md
[DOC-1993](https://redislabs.atlassian.net/browse/DOC-1993)
Some of these commands say in the history that they now support uppercase units but it seemed reasonable to change the syntax docs to keep things consistent.
Also, I assume that the M, KM, etc, in the `token` metadata doesn't need to change just to update the Syntax section?
[DOC-1993]: https://redislabs.atlassian.net/browse/DOC-1993?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DOC-1993 switched to lowercase for geo units

- content/develop/connect/clients/dotnet.md
- content/develop/connect/clients/java/_index.md
- content/develop/connect/clients/nodejs.md
- content/develop/connect/clients/python.md
[DOC-1103](https://redislabs.atlassian.net/browse/DOC-1103)
The only part of the JIRA issue still relevant is the links from the ordinary client pages to the OM pages. It only asks for Node.js but it makes sense to have similar links for the other clients too.
[DOC-1103]: https://redislabs.atlassian.net/browse/DOC-1103?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DOC-1103 added links from client pages to OM pages

- content/commands/ft.info/index.md
Field definitions are [here](https://redislabs.atlassian.net/wiki/spaces/DX/pages/3832414265/FT.INFO+Interpretation+Guide).
@joeywhelan Would it be possible for you to provide a definition for `cleaning`, one of the return values? Right now, I just have a placeholder where its definition should be, "DWD need def'n".
> DEV: flesh out FT.INFO page

- content/develop/data-types/json/_index.md
- content/develop/data-types/probabilistic/_index.md
- content/develop/data-types/timeseries/_index.md
- content/develop/interact/search-and-query/_index.md
[DOC-3479](https://redislabs.atlassian.net/browse/DOC-3479)
The [current JSON page](https://redis.io/docs/latest/develop/data-types/json/#enable-redis-json) goes into much more detail than the other pages for "optional" modules about how to obtain and install the module. But apparently, the extra info is actually misleading because some people try to jump through hoops installing the module when they probably just wanted to install Redis Stack in the first place.
I've modified the existing pages/sections for JSON and the module features to simply point to the Stack/Enterprise install pages. I've also added some extra description to the probabilistic and time series index pages so that the install info hangs a bit better on the page.
Any other ideas about how to clarify/expand this stuff …
> Doc 3479 json obtain redis stack

- content/develop/data-types/_index.md
[DOC-3992](https://redislabs.atlassian.net/browse/DOC-3992)
The page had two similar lists and the main one didn't list all the available data types.
[DOC-3992]: https://redislabs.atlassian.net/browse/DOC-3992?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DOC-3992 added missing types to datatype landing page

- content/operate/rs/references/rest-api/objects/user.md
The current documentation doesn't explain how to hash a password when creating or updating a user. This is a lot to put in a small space, so a shorter explanation might be better.
> Update REST API password documentation 

- content/commands/hdel/index.md
Since the summary isn't displayed on the [detailed page](https://redis.io/docs/latest/commands/hdel/), add this detail to the usual information.
> HDEL: Add "delete if empty" in information

- content/commands/ft.search/index.md
[DOC-1984](https://redislabs.atlassian.net/browse/DOC-1984)
Not sure if there's a standard style we normally use for this.
[DOC-1984]: https://redislabs.atlassian.net/browse/DOC-1984?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DOC-1984 added deprecation details for filter and geofilter args

- content/operate/rc/resilient-apps.md
This PR corrects a few warnings that were introduced by this PR:
https://github.com/redis/docs/pull/288
It's important to pay attention to Hugo warnings, as they usually point to some unwanted behavior. In this case, the affected links, when clicked, took you to the top of the page, not to the command pages.
Also, in general, it's better to get into the habit of using `[<CMD>]({{< baseurl >}}/commands/<cmd>)` for links to command pages. If you try to use relref with a command that has a dot in the name (e.g., FT.SEARCH), relref will tip over.
> OP: fix a few Hugo warnings

- layouts/partials/meta-links.html
This fixes the following warning:
> WARN .Path when the page is backed by a file is deprecated and will be removed in a future release. We plan to use Path for a canonical source path and you probably want to check the source is a file. To get the current behaviour, you can use a construct similar to the one below:
{{ $path := "" }}
{{ with .File }}
{{ $path = .Path }}
{{ else }}
{{ $path = .Path }}
{{ end }}
> DOC-2020 Fix hugo warning

- content/develop/connect/clients/go.md
This was briefly discussed with @mortensi , but let me know what changes you would like to see.
> chore: add observability section

- content/operate/oss_and_stack/install/install-stack/linux.md
This PR updates a steps required to run a Redis-Stack instance on Ubuntu using Snap
> Updated Redis-stack guide On Ubuntu with Snap

- content/develop/get-started/vector-database.md
- content/operate/kubernetes/reference/supported_k8s_distributions.md
- content/operate/rc/changelog/2023/march-2023.md
- content/operate/rs/references/compatibility/commands/cluster.md
- content/operate/rs/references/compatibility/commands/connection.md
- content/operate/rs/references/compatibility/commands/generic.md
- content/operate/rs/references/compatibility/commands/pub-sub.md
- content/operate/rs/references/compatibility/commands/scripting.md
- content/operate/rs/references/compatibility/commands/server.md
- content/operate/rs/references/compatibility/commands/transactions.md
This PR eliminates more double-slashes in URLs issue.
It also fixes a Hugo warning that was introduced in a recent merge.
> SITE: eliminate more double-slashes

- content/operate/oss_and_stack/stack-with-enterprise/release-notes/redisearch/redisearch-2.6-release-notes.md
- content/operate/oss_and_stack/stack-with-enterprise/release-notes/redisearch/redisearch-2.8-release-notes.md
New RediSearch release notes: v2.6.20 and v2.8.15.
> DEV: update RediSearch release notes

- content/integrate/prometheus-with-redis-cloud/_index.md
- content/integrate/prometheus-with-redis-enterprise/_index.md
The  links that point to redis-enterprise-observability were updated to reflect the changes in directory structure following the creation separate folders for Grafana versions and the suffixing of the dashboard file names with version.
> fix redis-enterprise-observability links

- content/develop/data-types/sorted-sets.md
Improve clarity by changing "but" to "so" in sorted sets documentation
the previous sentence used "but" to contrast two related facts about sorted sets, which could be misleading as it implies a contradiction. Replaced "but" with "so" to better reflect the causal relationship between the operations described, improving the overall clarity of the documentation.
> Improve clarity by changing "but" to "so" in sorted sets documentation

- content/develop/data-types/hashes.md
Just a spurious character at the end of the link URL.
> DOC-4134 fixed broken link

- content/operate/oss_and_stack/stack-with-enterprise/search/scalable-search.md
added a warning about the 'upgrade' procedure overwriting any existing search module parameters.
> Add note regarding overwrite of search param.

- .github/workflows/redis_docs_sync.yaml
This workflow will be triggered from the `redis/redis` repo on releases. This workflow generates the `modules-api-ref.md` file and pushes it to this repo.
> DOC-3970 Add redis_docs_sync workflow

- layouts/commands/list.html
Very minor - just removed the extra "Commands" tile from the commands home page (it just linked back to the top of the same page).
Staging link: https://redis.io/docs/staging/DOC-4163-spurious-commands-tile/commands/?alpha=c
> DOC-4163 removed Commands tile from home page

- content/develop/connect/clients/java/_index.md
- content/develop/connect/clients/java/jedis.md
- content/develop/connect/clients/java/lettuce.md
- content/embeds/r7.2-migration-guides.md
- content/operate/rs/references/compatibility/resp.md
- content/operate/rs/release-notes/rs-7-2-4-releases/rs-7-2-4-52.md
[DOC-4167](https://redislabs.atlassian.net/browse/DOC-4167)
[DOC-4167]: https://redislabs.atlassian.net/browse/DOC-4167?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DOC-4167 update Lettuce links and basic info

- content/operate/oss_and_stack/stack-with-enterprise/search/query-performance-factor.md
changed 'scalable seach' to new name - Query performance factor
> update naming to query performance factor

- content/integrate/redis-data-integration/ingest/quick-start-guide.md
[DOC-4206](https://redislabs.atlassian.net/browse/DOC-4206)
[DOC-4206]: https://redislabs.atlassian.net/browse/DOC-4206?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DOC-4206 add section about contexts

- layouts/partials/tabs/wrapper.html
After several attempts, the issue seemed to be with the exact format for the absURL path.
> DOC-4210 added baseURL to client quickstart links

- content/operate/rs/clusters/add-node.md
- content/operate/rs/clusters/new-cluster-setup.md
- content/operate/rs/databases/auto-tiering/quickstart.md
- content/operate/rs/databases/create.md
> RS: Remove /new from CM UI URLs

- content/operate/rs/databases/active-active/create.md
- content/operate/rs/databases/active-active/manage.md
- content/operate/rs/databases/active-active/planning.md
> RS: Clarify limitation for mixed RAM/flash A-A clusters

- content/integrate/redis-data-integration/ingest/architecture.md
- content/integrate/redis-data-integration/ingest/installation/_index.md
- content/integrate/redis-data-integration/ingest/observability.md
- content/integrate/redis-data-integration/ingest/troubleshooting.md
[DOC-4214](https://redislabs.atlassian.net/browse/DOC-4214)
Also moved some of the detail about `redis-di dump-support-package` from Observability to the new page.
[DOC-4214]: https://redislabs.atlassian.net/browse/DOC-4214?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DOC-4214 added troubleshooting page

- content/develop/reference/protocol-spec.md
Fixed the typo in the code comment: 
Previously mentioned 'bulk_len' which was incorrect.  The length is actually stored in the 'len' variable
> Update protocol-spec.md to fix a typo in code comment.

- content/commands/ttl/index.md
This PR corrects a typo on the [TTL command page](https://redis.io/docs/latest/commands/ttl/).
> ![image](https://github.com/user-attachments/assets/c0713f9e-3327-49d0-a5d2-cd1723a7675c)
The red rectangle annotation was added to the screenshot for illustration.
> ![image](https://github.com/user-attachments/assets/27f0a69f-03ad-4191-b0af-fe92b14a581d)
> Fix typo: "exist" --> "exists"

- content/integrate/redis-data-integration/ingest/installation/_index.md
The fact that the example was a TOML file wasn't explicitly stated, so I added adjectives to make it clear what the example file is.
> Update _index.md reinforcing that the example is a TOML file.

- content/operate/oss_and_stack/management/replication.md
This PR removes the extra `mode.` in replication.md
> Remove redundant word in replication.md

- content/embeds/cluster-setup.md
DOC-4139
Fixing a URL instance I missed in my previous PR #625.
> RS: Remove /new from CM UI URL in embeds

- content/commands/del/index.md
- content/commands/expire/index.md
- content/commands/hget/index.md
- content/commands/hset/index.md
- content/commands/incr/index.md
- content/commands/scan/index.md
- content/commands/ttl/index.md
- content/commands/zadd/index.md
- content/commands/zrange/index.md
[DOC-4040](https://redislabs.atlassian.net/browse/DOC-4040)
[DOC-4040]: https://redislabs.atlassian.net/browse/DOC-4040?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DEV: Add TCEs to select command pages

- content/operate/rs/references/rest-api/requests/nodes/status.md
> RS: Add maintenance_snapshot to /nodes/status REST API reference

- content/operate/rs/references/rest-api/requests/cluster/actions.md
> RS: Add change_master to /cluster/actions REST API reference

- content/develop/interact/search-and-query/query/range.md
[DOC-4195](https://redislabs.atlassian.net/browse/DOC-4195)
[DOC-4195]: https://redislabs.atlassian.net/browse/DOC-4195?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DEV: add TCEs to query > range page

- content/develop/interact/search-and-query/query/full-text.md
[DOC-4196](https://redislabs.atlassian.net/browse/DOC-4196)
[DOC-4196]: https://redislabs.atlassian.net/browse/DOC-4196?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DEV: add TCEs to query > full-text page

- content/develop/interact/search-and-query/query/geo-spatial.md
[DOC-4197](https://redislabs.atlassian.net/browse/DOC-4197)
[DOC-4197]: https://redislabs.atlassian.net/browse/DOC-4197?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DEV: add TCEs to query > geospatial page

- content/integrate/redis-data-integration/installation/_index.md
[DOC-4285](https://redislabs.atlassian.net/browse/DOC-4285)
[DOC-4285]: https://redislabs.atlassian.net/browse/DOC-4285?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DOC-4285 added info about iptables versions

- content/commands/ft.search/index.md
added warning regarding LIMIT behavior
> add note regarding LIMIT behavior

- content/develop/interact/search-and-query/query/vector-search.md
[DOC-4198](https://redislabs.atlassian.net/browse/DOC-4198)
[DOC-4198]: https://redislabs.atlassian.net/browse/DOC-4198?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DEV: add TCEs to query > vector page

- content/operate/kubernetes/deployment/openshift/openshift-operatorhub.md
DOC-3883
https://github.com/redis/docs/issues/123
> K8s: changed wording of SCC note

- layouts/home.html
Noticed these links went to 404s.
> Fix Ingest and Write-behind link 404s on home page

- content/operate/rs/databases/migrate-shards.md
- content/operate/rs/references/cli-utilities/rladmin/migrate.md
- content/operate/rs/references/rest-api/objects/statistics/_index.md
- content/operate/rs/references/rest-api/requests/bdbs/shards.md
- content/operate/rs/references/rest-api/requests/shards/_index.md
- content/operate/rs/references/rest-api/requests/shards/actions/_index.md
- content/operate/rs/references/rest-api/requests/shards/actions/migrate.md
- content/operate/rs/references/rest-api/requests/shards/stats/_index.md
- content/operate/rs/references/rest-api/requests/shards/stats/last.md
> RS: Add GET shards and migrate shards REST API references

- content/operate/rs/references/rest-api/objects/bdb/_index.md
> RS: Add new syncer connection alert attributes to BDB object REST API reference

- content/operate/rs/clusters/logging/log-security.md
DOC-1595 add a link to rsyslog info from the log security page
> add link to rsyslog logging

- content/commands/json.strlen/index.md
DOC-2172 change array to string
> Update JSON.STRLEN index.md

- content/operate/rs/databases/active-active/planning.md
#DOC-2229 add limitation to limitations section about UNLINK being blocking
> add limitation to a-a doc

- content/develop/reference/protocol-spec.md
[DOC-4224](https://redislabs.atlassian.net/browse/DOC-4224)
[DOC-4224]: https://redislabs.atlassian.net/browse/DOC-4224?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DEV: add attribute type to the RESP3 spec.

- content/develop/interact/programmability/lua-api.md
[DOC-4343](https://redislabs.atlassian.net/browse/DOC-4343)
Nav was using `<a.../a>` anchors instead of {#...}, causing the right-side nav to bug out.
[DOC-4343]: https://redislabs.atlassian.net/browse/DOC-4343?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DEV: fix Lua API right-side nav

- content/integrate/redis-data-integration/data-pipelines/transform-examples/redis-opcode-example.md
Basically [this example](https://redislabs.atlassian.net/wiki/spaces/~6318b461316bbc56c425f7f9/pages/4026335402/RDI+Ingest+Examples#Adding-the-Opcode-to-the-Redis-Key) plus a bit of explanatory text.
> DOC-4305 added opcode example

- content/integrate/redis-data-integration/faq.md
[DOC-4352](https://redislabs.atlassian.net/browse/DOC-4352)
I'm pretty sure it was only mentioned by mistake in the FAQ.
[DOC-4352]: https://redislabs.atlassian.net/browse/DOC-4352?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DOC-4352 removed mention of DB2

- content/operate/oss_and_stack/install/install-redis/install-redis-on-linux.md
[DOC-4356](https://redislabs.atlassian.net/browse/DOC-4356)
Fixes #739 .
[DOC-4356]: https://redislabs.atlassian.net/browse/DOC-4356?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DEV: amend Ubuntu install docs

- content/develop/interact/search-and-query/query/aggregation.md
[DOC-4200](https://redislabs.atlassian.net/browse/DOC-4200)
[DOC-4200]: https://redislabs.atlassian.net/browse/DOC-4200?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DEV: add TCEs to query > aggregation page

- content/operate/oss_and_stack/stack-with-enterprise/release-notes/redisce/_index.md
- content/operate/oss_and_stack/stack-with-enterprise/release-notes/redisce/redisce-7.4-release-notes.md
[DOC-4363](https://redislabs.atlassian.net/browse/DOC-4363)
As this is the first time that CE relnotes have appeared on redis.io, I'm not sure I put these in the correct place.
[DOC-4363]: https://redislabs.atlassian.net/browse/DOC-4363?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DEV: add Redis CE 7.4.x relnotes to site

- content/develop/data-types/sorted-sets.md
[DOC-4360](https://redislabs.atlassian.net/browse/DOC-4360)
Fixes #748. `XD`
[DOC-4360]: https://redislabs.atlassian.net/browse/DOC-4360?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DEV: replace hackers with racers on sorted sets page

- content/develop/connect/clients/_index.md
There are two ways to use Redis with PHP. One is with a library (written in PHP) and the other one is with a PHP extension (written in C). 
The extension is faster but the library is easier to install, especially if you are on shared hosts.
> Add PHP Redis extension

- content/commands/info/index.md
- content/commands/memory-usage/index.md
[DOC-4310](https://redislabs.atlassian.net/browse/DOC-4310)
Note to reviewers: I pulled some information from the RS command compat. docs to include with these changes. Over time, all of that command compat. information will be added to the individual command pages.
[DOC-4310]: https://redislabs.atlassian.net/browse/DOC-4310?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DEV: doc changes per RED-137284

- content/operate/oss_and_stack/install/install-redis/install-redis-on-linux.md
I'm not sure if `redis-server` should also be used in the "Install on Red Hat/Rocky" section.
> Fix redis service name on installation page

- assets/css/index.css
- insert_url_frontmatter.bash
- layouts/operate/list.html
- layouts/operate/single.html
- layouts/partials/docs-nav.html
- layouts/partials/scripts.html
These changes enable version dropdown for Kubernetes and RS, provided that their linkTitles are respectively `Redis for Kubernetes` and `Redis Software`.
Preview link: https://redis.io/docs/staging/DOC-4272/operate/ . The dropdowns are not shown since the linkTitles are not correct yet
> DOC-4272 Add support for versioned products

- content/develop/interact/search-and-query/advanced-concepts/vectors.md
**Describe the changes in the pull request**
1. In the documentation, `__vec_scores` was used to demonstrate the SORTBY capabilities for `FT.SEARCH` when working with vectors.
2. If execute the documentation suggested with `__vec_scores` field, an error will be thrown: ``Property `__vec_scores` not loaded nor in schema``
3. Update the documentation to `__vec_score`
**Which issues this PR fixes**
1. Typo of extra `s` present in the documentation.
2. PR is already opened at https://github.com/RediSearch/RediSearch/pull/5117
**Main objects this PR modified**
1. Documentation of `content/develop/interact/search-and-query/advanced-concepts/vectors.md`
> DOC: typo for __vec_score sortby field

- content/commands/flushall/index.md
- content/commands/flushdb/index.md
Added a note: functions are not deleted.
> FLUSH commands and functions

- content/operate/oss_and_stack/stack-with-enterprise/release-notes/redisgears/redisgears-1.2-release-notes.md
[DOC-4375](https://redislabs.atlassian.net/browse/DOC-4375)
[DOC-4375]: https://redislabs.atlassian.net/browse/DOC-4375?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OP: update RedisGears release notes for 1.2.10

- content/develop/interact/search-and-query/query/combined.md
[DOC-4199](https://redislabs.atlassian.net/browse/DOC-4199)
[DOC-4199]: https://redislabs.atlassian.net/browse/DOC-4199?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DEV: add TCEs to query > combined page

- content/develop/connect/clients/go.md
I've edited the text of the page and added some JSON and hash search examples, so it now looks more like the equivalent pages for redis-py, etc. Vector search was suggested as a possible extra example but we don't currently have any vector search code samples and none of the other client "home" pages refer to it. However, it is one of my tasks for this quarter to improve our vector docs, so I'll address this matter separately.
> DOC-4303 updated Go landing page

- content/glossary/_index.md
- content/integrate/write-behind/data-transformation/data-transformation-pipeline.md
- content/operate/kubernetes/release-notes/previous-releases/k8s-5-4-10-8.md
- content/operate/rs/release-notes/rs-7-2-4-releases/rs-7-2-4-52.md
> Fix broken links

- content/integrate/redis-data-integration/data-pipelines/prepare-dbs/oracle.md
[DOC-4384](https://redislabs.atlassian.net/browse/DOC-4384)
[DOC-4384]: https://redislabs.atlassian.net/browse/DOC-4384?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DOC-4384 removed spurious info on RDI Oracle prep page

- content/operate/rs/_index.md
- content/operate/rs/installing-upgrading/_index.md
> RS: Mention/link to Redis Cloud free trial

- content/develop/reference/protocol-spec.md
[DOC-4389](https://redislabs.atlassian.net/browse/DOC-4389)
Changed `<CR><LF>` to` \r\n` .
[DOC-4389]: https://redislabs.atlassian.net/browse/DOC-4389?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DEV: fix attribute type examples on the protocol page

- .github/workflows/redis_modules_docs_sync.yaml
The workflow will run daily at midnight but can also be triggered manually.
> DOC-4386 Create github workflow for fetching command json files from module repositories

- .github/workflows/redis_modules_docs_sync.yaml
This fixes a bug in the workflow
> Add missing checkout action in redis_modules_docs_sync workflow

- content/develop/connect/clients/_index.md
[DOC-4383](https://redislabs.atlassian.net/browse/DOC-4383)
[DOC-4383]: https://redislabs.atlassian.net/browse/DOC-4383?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DOC-4383 added Boost.redis to community client table

- content/integrate/redis-data-integration/ingest/data-pipelines/transform-examples/redis-string-example.md
First attempt...
I've tried to keep it simple like the other data type examples, but maybe it's a bit boring? (Maybe the others need a bit of work, if so.)
Any suggestions are welcome :-)
> DOC-4014 added RDI string job config example

- content/integrate/redis-data-integration/data-pipelines/transform-examples/redis-string-example.md
- content/integrate/write-behind/data-transformation/data-transformation-pipeline.md
- content/operate/kubernetes/release-notes/6-2-18-releases/k8s-6-2-18-3.md
- content/operate/kubernetes/release-notes/6-2-18-releases/k8s-6-2-18-41-jan-2023.md
- content/operate/kubernetes/release-notes/6-2-18-releases/k8s-6-2-18-41.md
- content/operate/kubernetes/release-notes/7-4-6-releases/7-4-6-2-oct24.md
- content/operate/rs/release-notes/rs-7-2-4-releases/rs-7-2-4-52.md
Fixing relrefs found when serving the site on main.
> Fix Relrefs

- content/operate/oss_and_stack/stack-with-enterprise/release-notes/redisce/redisce-7.4-release-notes.md
- content/operate/oss_and_stack/stack-with-enterprise/release-notes/redisstack/_index.md
- content/operate/oss_and_stack/stack-with-enterprise/release-notes/redisstack/redisstack-7.4-release-notes.md
[DOC-4407](https://redislabs.atlassian.net/browse/DOC-4407)
[DOC-4407]: https://redislabs.atlassian.net/browse/DOC-4407?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OP: add Redis Stack v7.4.x release notes

- content/develop/connect/clients/client-side-caching.md
[DOC-4369](https://redislabs.atlassian.net/browse/DOC-4369)
[DOC-4369]: https://redislabs.atlassian.net/browse/DOC-4369?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DOC-4369 changed HGETALL to HRANDFIELD in CSC docs

- content/operate/rs/networking/multi-ip-ipv6.md
> RS: Fix contradictory statements about internal IP changes

- content/operate/rs/references/cli-utilities/rladmin/tune.md
> RS: Fix rladmin tune db typo & describe replica buffer options

- content/operate/rc/api/get-started/manage-api-keys.md
@cmilesb suggestion to add viewer (read-only) role support to the cloud API.
> Add CAPI viewer role

- content/develop/reference/eviction/index.md
[DOC-4380](https://redislabs.atlassian.net/browse/DOC-4380)
The requested info is now added and some others bits are rewritten for clarity.
Closes #580 
[DOC-4380]: https://redislabs.atlassian.net/browse/DOC-4380?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DOC-4380 more info about key eviction

- content/operate/oss_and_stack/stack-with-enterprise/release-notes/redisstack/redisstack-7.2-release-notes.md
[DOC-4420](https://redislabs.atlassian.net/browse/DOC-4420)
**Note to reviewers**: little (if any) copy-editing was done to this page. The release notes were copied directly from the redis-stack/redis-stack repo and stuffed into this page mostly as-is.
[DOC-4420]: https://redislabs.atlassian.net/browse/DOC-4420?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OP: add Redis Stack v7.2.x release notes

- content/apis/_index.md
fix two incorrect links in API landing page doc
> Update API _index.md

- content/develop/data-types/probabilistic/bloom-filter.md
[DOC-4437](https://redislabs.atlassian.net/browse/DOC-4437)
[DOC-4437]: https://redislabs.atlassian.net/browse/DOC-4437?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DEV: fix link on Bloom data structure page

- content/develop/connect/insight/release-notes/v.2.60.0.md
> Create v.2.60.0.md for Redis Insight

- content/operate/rs/references/rest-api/requests/bdbs/actions/_index.md
- content/operate/rs/references/rest-api/requests/bdbs/actions/rebalance.md
> RS: Add rebalance database shards REST API reference

- content/operate/kubernetes/release-notes/6-4-2-releases/6-4-2-8-oct24.md
- content/operate/kubernetes/release-notes/7-2-4-releases/7-2-4-12-10-24.md
- content/operate/kubernetes/release-notes/7-4-6-releases/7-4-6-2-october24.md
> K8s: update CSV and add note about replacements

- content/operate/oss_and_stack/install/install-redis/install-redis-on-linux.md
Corrected spelling of 'an' to 'can' in content/operate/oss_and_stack/install/install-redis/install-redis-on-linux.md
> install-redis-on-linux spelling mistake correction

- .github/workflows/main.yml
Every versioned folder will be built separately and synched to the right location on the bucket
> DOC-4274 Add support for versioned products in prod bucket

- content/develop/connect/clients/dotnet.md
[DOC-4345](https://redislabs.atlassian.net/browse/DOC-4345)
This is mainly to make the JSON examples testable, but it also offers the eye widget to let the user see the whole search example as a file. There are a few format changes - I'm basically trying to get the JSON examples aligned across all the client home pages.
[DOC-4345]: https://redislabs.atlassian.net/browse/DOC-4345?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DOC-4345 replaced JSON home page examples with testable versions

- content/operate/rs/databases/import-export/flush.md
> RS: New CM UI instructions to flush Active-Active DB

- content/operate/rs/references/rest-api/requests/bdbs/actions/_index.md
- content/operate/rs/references/rest-api/requests/bdbs/actions/resume_traffic.md
- content/operate/rs/references/rest-api/requests/bdbs/actions/stop_traffic.md
> RS: Add DB stop_traffic & resume_traffic REST API request references

- content/develop/connect/clients/_index.md
- content/develop/connect/clients/om-clients/_index.md
- content/develop/connect/clients/php.md
[DOC-4520](https://redislabs.atlassian.net/browse/DOC-4520)
New client page for PHP. Note that we probably can't add examples for testing and we won't be supporting the full range of tabbed samples for PHP just yet.
[DOC-4520]: https://redislabs.atlassian.net/browse/DOC-4520?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DOC-4520 added PHP client page

- .github/workflows/update_command_pages.yaml
Whenever `data/commands_core.json` is updated on the `main` branch, this workflow will run automatically. It runs `python3 build/update_cmds.py` and, if any command pages have changed, it creates a pull request with the updated files.
> Add update_command_pages workflow

- content/develop/interact/search-and-query/basic-constructs/configuration-parameters.md
Added explanation of this new search configuration parameter.
> DOC-4513 add INDEX_CURSOR_LIMIT

- content/commands/ft.create/index.md
[DOC-4546](https://redislabs.atlassian.net/browse/DOC-4546)
[DOC-4546]: https://redislabs.atlassian.net/browse/DOC-4546?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DEV: correct errant FILTER on FT.CREATE page

- content/develop/clients/nodejs/_index.md
Good save by David - the name was changed from Node.js to JavaScript in the client index page but not in the sidebar :-( This fixes it.
> DOC-4553 fixed JavaScript name in sidebar

- content/develop/clients/go/queryjson.md
- content/develop/clients/jedis/queryjson.md
- layouts/commands/list.html
[DOC-4345](https://redislabs.atlassian.net/browse/DOC-4345)
Still a bit of conversation going on about JS and Python but we can add Go and the completely absent Java examples for now. Also, fixed a small error ("Server managment") in the Commands page menu.
[DOC-4345]: https://redislabs.atlassian.net/browse/DOC-4345?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DOC-4345 more JSON query examples

- content/develop/data-types/json/ram.md
> Fixed a typo

- content/commands/ft.search/index.md
[DOC-4552])(https://redislabs.atlassian.net/browse/DOC-4552)
[DOC-4552]: https://redislabs.atlassian.net/browse/DOC-4552?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DEV: add definition for NOSTOPWORDS to FT.SEARCH command page

- content/integrate/redis-data-integration/installation/install-k8s.md
[DOC-4561](https://redislabs.atlassian.net/browse/DOC-4561)
Let me know if this needs more emphasis or explanation, and if you have a better value for `JWT_SECRET_KEY` than `yourKey`, I'll add it in.
[DOC-4561]: https://redislabs.atlassian.net/browse/DOC-4561?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DOC-4561 fixes for RDI Helm docs

- content/integrate/redis-data-integration/data-pipelines/transform-examples/map-example.md
[DOC-4568](https://redislabs.atlassian.net/browse/DOC-4568)
Two examples of `map` transforms. Any suggestions for improvements are welcome :-) 
[DOC-4568]: https://redislabs.atlassian.net/browse/DOC-4568?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DOC-4568 added map transform example page

- content/operate/oss_and_stack/stack-with-enterprise/install/upgrade-module.md
DOC-4566 DOC-4567
Note: Underscores are not allowed in RS DB names, but hyphens are allowed.
> RS: Fix DB names in rladmin upgrade examples to correctly follow DB naming rules

- content/integrate/redis-data-integration/installation/install-vm.md
[DOC-4579](https://redislabs.atlassian.net/browse/DOC-4579)
[DOC-4579]: https://redislabs.atlassian.net/browse/DOC-4579?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DOC-4579 RDI: improve hardware sizing info

- content/commands/flushall/index.md
- content/commands/flushdb/index.md
Added notes: `FLUSHDB` and `FLUSHALL` are identical on a Redis cluster.
(following https://redis.slack.com/archives/CLZCLHWQ0/p1731468610504539)
> flush-commands-docs

- content/operate/rs/databases/durability-ha/_index.md
> RS: Fix replication description

- content/integrate/prometheus-with-redis-enterprise/prometheus-metrics-v1-to-v2.md
- content/operate/rs/release-notes/rs-7-8-releases/_index.md
- content/operate/rs/release-notes/rs-7-8-releases/rs-7-8-2-34.md
> RS: Clarify Prometheus v1 metrics are still available

- content/integrate/redis-data-integration/data-pipelines/deploy.md
[DOC-4586](https://redislabs.atlassian.net/browse/DOC-4586)
I've written the commands out in full because they are a bit complicated. Just thinking, should we have the corresponding `redis-di set-secret` command lines in full too? They are simpler, but easy copy/paste might be useful?
[DOC-4586]: https://redislabs.atlassian.net/browse/DOC-4586?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DOC-4586 added K8s commands to set secrets

- layouts/home.html
- layouts/partials/tabs/wrapper.html
[DOC-4588](https://redislabs.atlassian.net/browse/DOC-4588)
Also found some links to Redis Insight in the layouts that were pointing to the wrong place. The links still worked OK, btw, but making use of alias redirects rather than linking to the right place.
[DOC-4588]: https://redislabs.atlassian.net/browse/DOC-4588?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DOC-4588 fixed layout links to old develop/connect section

- content/operate/oss_and_stack/management/optimization/benchmarks/index.md
Just fixing a typo of 'do deliver' to be 'to deliver'
> Fix typo in benchmark docs

- content/integrate/redis-data-integration/installation/install-k8s.md
- content/integrate/redis-data-integration/installation/install-vm.md
- content/integrate/redis-data-integration/quick-start-guide.md
[DOC-4597](https://redislabs.atlassian.net/browse/DOC-4597)
There were also some other obsolete references to the installer creating the RDI DB automatically, which I've removed.
[DOC-4597]: https://redislabs.atlassian.net/browse/DOC-4597?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DOC-4597 removed obsolete bits about automatic RDI DB creation

- content/integrate/redis-data-integration/installation/install-k8s.md
[DOC-4605](https://redislabs.atlassian.net/browse/DOC-4605)
I actually added the new stuff after the section about `values.yaml` (because I figured you would add the new values there) but let me know if the new info should be emphasised by moving it further up the page. Content is basically the same as suggested with a few extra links. 
[DOC-4605]: https://redislabs.atlassian.net/browse/DOC-4605?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DOC-4605 added ingress controller details

- content/integrate/redis-data-integration/data-pipelines/data-pipelines.md
[DOC-4607](https://redislabs.atlassian.net/browse/DOC-4607)
[DOC-4607]: https://redislabs.atlassian.net/browse/DOC-4607?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DOC-4607 added debezium_lob_encoded_placeholder prop to config.yaml

- layouts/partials/tabbed-clients-example.html
[DOC-4608](https://redislabs.atlassian.net/browse/DOC-4608)
Tried using the client name rather than the language name to identify the tabs in the layout file.
Tested a few TCEs (including the [Strings](https://redis.io/docs/staging/DOC-4608-lettuce-breaks-code-tabs/develop/data-types/strings/) page, which is the only one that currently has Lettuce tabs) and it seems to work OK.
[DOC-4608]: https://redislabs.atlassian.net/browse/DOC-4608?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DOC-4608 can't switch Java tabs in published build

- content/operate/rs/release-notes/rs-7-8-releases/_index.md
- content/operate/rs/release-notes/rs-7-8-releases/rs-7-8-2-34.md
> Revert "RS: Add Sentinel known issue to 7.8.2-34 release notes"

- build/components/example.py
- config.toml
- data/components/jedis.json
- data/components/lettuce_async.json
- data/components/lettuce_reactive.json
- layouts/partials/tabbed-clients-example.html
- layouts/partials/tabs/wrapper.html
[DOC-4623](https://redislabs.atlassian.net/browse/DOC-4623)
The tabs appear to be "sticky" again and you can now select the Java clients for individual code examples (use Java-Sync, etc). Also, I'm trying out a smaller text size in the tab bar to prevent it from wrapping when all the clients are present (eg, compare [current](https://redis.io/docs/latest/develop/data-types/strings/#strings-as-counters) with [new](https://redis.io/docs/staging/DOC-4623-java-code-tab-issues/develop/data-types/strings/#strings-as-counters)).
Any thoughts about the tab formatting, client names with hyphens, etc, are most welcome :-) 
[DOC-4623]: https://redislabs.atlassian.net/browse/DOC-4623?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DOC-4623 attempted fix for tab issues

- content/commands/bf.reserve/index.md
- content/develop/data-types/probabilistic/bloom-filter.md
> Fix Bloom documented formulas

- content/commands/ft.search/index.md
[DOC-4616](https://redislabs.atlassian.net/browse/DOC-4616)
[DOC-4616]: https://redislabs.atlassian.net/browse/DOC-4616?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DEV: fix FT.SEARCH syntax

- content/develop/data-types/probabilistic/cuckoo-filter.md
missing "an" before 80 %
"-" should be yields
> Typo of cuckoo-filter.md

- content/develop/clients/jedis/transpipe.md
- content/develop/clients/redis-py/transpipe.md
[DOC-4560](https://redislabs.atlassian.net/browse/DOC-4560)
[DOC-4560]: https://redislabs.atlassian.net/browse/DOC-4560?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DOC-4560 added testable Python and Jedis pipe/transaction examples

- content/integrate/redis-data-integration/installation/install-k8s.md
[DOC-4610](https://redislabs.atlassian.net/browse/DOC-4610)
[DOC-4610]: https://redislabs.atlassian.net/browse/DOC-4610?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DOC-4610 updated K8s install instructions

- content/integrate/redis-data-integration/installation/install-k8s.md
- content/integrate/redis-data-integration/installation/install-vm.md
- content/integrate/redis-data-integration/quick-start-guide.md
[DOC-4643](https://redislabs.atlassian.net/browse/DOC-4643)
Added the warning in the two install pages and the quickstart page.
[DOC-4643]: https://redislabs.atlassian.net/browse/DOC-4643?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DOC-4643 added warnings about clustered RDI DBs

- content/operate/rs/installing-upgrading/install/customize-install-directories.md
- content/operate/rs/installing-upgrading/install/plan-deployment/_index.md
> RS: Recommend different mount points for data & log files

- content/integrate/prometheus-with-redis-enterprise/observability.md
- content/operate/oss_and_stack/stack-with-enterprise/release-notes/redisgears/redisgears-1.2-release-notes.md
[DOC-4662](https://redislabs.atlassian.net/browse/DOC-4662)
- Add RedisGears v1.2.12 release notes
- Fix link warning
[DOC-3661]: https://redislabs.atlassian.net/browse/DOC-3661?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DOC-4662]: https://redislabs.atlassian.net/browse/DOC-4662?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OP: add gears v1.2.12 rns & fix link warning

- content/commands/latency-histogram/index.md
[DOC-4652](https://redislabs.atlassian.net/browse/DOC-4652)
[DOC-4652]: https://redislabs.atlassian.net/browse/DOC-4652?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DEV: correct latency range

- content/embeds/rdi-supported-source-versions.md
- content/integrate/redis-data-integration/_index.md
- content/integrate/redis-data-integration/architecture.md
I got the details of the supported AWS RDS databases from the existing pages - please check if they're all correct. Also, I got the supported version of Aurora/PostgreSQL from [this screenshot](https://redislabs.atlassian.net/wiki/spaces/~6318b461316bbc56c425f7f9/pages/4753588337/RDI+with+AWS+Aurora+and+PostgreSQL#Create-Aurora-PostgreSQL-DB-cluster) in George's original document - please let me know if we need to add any other supported versions here.
> DOC-4647 updated supported sources table with AWS RDS details

- content/commands/client-list/index.md
[DOC-4671](https://redislabs.atlassian.net/browse/DOC-4671)
Fixes #984.
[DOC-4671]: https://redislabs.atlassian.net/browse/DOC-4671?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DEV: Add missing field definitions to CLIENT LIST page

- content/commands/bitpos/index.md
[DOC-4678](https://redislabs.atlassian.net/browse/DOC-4678)
Replace interactive examples with static examples. The interactive console is bugged.
Fixes #993.
[DOC-4678]: https://redislabs.atlassian.net/browse/DOC-4678?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DEV: fix bug on BITPOS command page

- content/develop/tools/insight/release-notes/v.2.64.0.md
> Release notes for Redis Insight v.2.64.0.md

- content/integrate/redis-data-integration/installation/install-vm.md
See https://redislabs.atlassian.net/browse/DOC-4619, https://redislabs.atlassian.net/browse/RDSC-2973
> DOC-4619 Improve RDI silent install example and properties

- content/develop/tools/redis-for-vscode/release-notes/v1.2.0.md
> Release notes for Redis for VS Code v1.2.0.md

- content/operate/rc/subscriptions/view-essentials-subscription/essentials-plan-details.md
> RC: Clarify that monthly network cap applies over all databases in the plan

- content/operate/rs/installing-upgrading/upgrading/upgrade-os.md
> RS: Add step to avoid removing a primary node last during rolling upgrade

- content/operate/rs/clusters/logging/redis-slow-log.md
> RS: Add more info about viewing & managing slow log

- content/operate/oss_and_stack/stack-with-enterprise/release-notes/redisearch/redisearch-2.10-release-notes.md
- content/operate/oss_and_stack/stack-with-enterprise/release-notes/redisstack/redisstack-7.4-release-notes.md
- content/operate/rs/release-notes/rs-7-8-releases/_index.md
- content/operate/rs/release-notes/rs-7-8-releases/rs-7-8-2-34.md
- content/operate/rs/release-notes/rs-7-8-releases/rs-7-8-2-60.md
[DOC-4670](https://redislabs.atlassian.net/browse/DOC-4670)
@rrelledge: I added a note in both the Redis Stack 7.4 and RediSearch 2.10 release notes.
[DOC-4670]: https://redislabs.atlassian.net/browse/DOC-4670?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DEV+RS: hash field limitation in RediSearch v2.10

- content/operate/rs/references/rest-api/requests/redis_acls/_index.md
- content/operate/rs/release-notes/rs-7-8-releases/rs-7-8-4-18.md
> RS: Add dry_run option for Redis ACL REST API to reference & 7.8.4 release notes

- content/operate/rs/references/rest-api/objects/bdb/dataset_import_sources.md
- content/operate/rs/references/rest-api/requests/bdbs/actions/import.md
> RS: Add missing filename option & examples to import DB REST API references

- content/operate/rs/7.4/references/rest-api/objects/bdb/_index.md
- content/operate/rs/7.4/references/rest-api/objects/crdb/database_config.md
- content/operate/rs/references/rest-api/objects/bdb/_index.md
- content/operate/rs/references/rest-api/objects/crdb/database_config.md
> RS: Fix shard_key_regex format in REST API reference

- content/operate/rs/release-notes/rs-7-8-releases/rs-7-8-2-34.md
> RS: Add Prometheus v1 metrics issues resolved by v2 to release notes

- content/operate/oss_and_stack/stack-with-enterprise/gears-v1/python/quickstart.md
[DOC-4689](https://redislabs.atlassian.net/browse/DOC-4689)
Fixes #1015.
[DOC-4689]: https://redislabs.atlassian.net/browse/DOC-4689?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DEV: fix code example

- content/operate/redisinsight/install/install-on-k8s.md
[DOC-4667](https://redislabs.atlassian.net/browse/DOC-4667)
The main affected area is the `LivenessProbe` section, lines 242 - 248, which was incorrectly formatted.
[DOC-4667]: https://redislabs.atlassian.net/browse/DOC-4667?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DEV: correct Redis Insight on K8s instructions

- content/integrate/prometheus-with-redis-cloud/_index.md
> RC: Specify internal IP standard for Prometheus on Redis Cloud

- content/integrate/redis-data-integration/data-pipelines/data-pipelines.md
[DOC-4603](https://redislabs.atlassian.net/browse/DOC-4603) (relating to [RDSC-2937](https://redislabs.atlassian.net/browse/RDSC-2937))
I've added the description as comments in `config.yaml` but let me know if this is important enough to mention in the main text as well. Also, the value for `redis.wait.retry.delay.ms` is currently not specified - please let me know what it should be.
[DOC-4603]: https://redislabs.atlassian.net/browse/DOC-4603?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[RDSC-2937]: https://redislabs.atlassian.net/browse/RDSC-2937?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DOC-4603 added missing sink HA properties

- content/operate/redisinsight/install/install-on-desktop.md
[DOC-4683](https://redislabs.atlassian.net/browse/DOC-4683)
[DOC-4683]: https://redislabs.atlassian.net/browse/DOC-4683?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DEV: add details to RI supported platforms page

- content/operate/rc/api/examples/audit-system-logs.md
- content/operate/rc/api/examples/back-up-and-import-data.md
- content/operate/rc/api/examples/dryrun-cost-estimates.md
> RC API: Minor fixes to least-viewed example pages

- content/commands/cluster-forget/index.md
Update CLUSTER FORGET docs for changes in https://github.com/redis/redis/pull/10869
> Update forget docs for ban-list propagation

- .gitignore
- Makefile
[DOC-4730](https://redislabs.atlassian.net/browse/DOC-4730)
Summary:
- The `make.py` file that builds the docs has a `--stack` option that specifies where to locate the `index.json` file for the client repos. Currently, we don't specify any option, so it uses the default.
- I've added a new build target (`localserve`) that works the same as `make serve` but sets the `--stack` option of `make.py` to `data/components_local/index.json` instead of the default `data/components/index.json`. The `data/components_local` folder is just a copy of `data/components` to begin with, but you can change the individual client repo files (`redis-py.json`, etc) to reference your local clones of the repos instead of the ones on Github.
- I've also added `data/components_local` to `.gitignore`.
The theory, …
> DOC-4730 experimental build target that uses local client repos

- content/operate/rs/security/access-control/create-cluster-roles.md
- content/operate/rs/security/access-control/create-combined-roles.md
- content/operate/rs/security/access-control/create-db-roles.md
> RS: Add REST API examples for creating & associating roles and ACLs with databases

- content/develop/interact/search-and-query/advanced-concepts/vectors.md
[DOC-4020 (backlog)](https://redislabs.atlassian.net/browse/DOC-4020)
> DEV: add BFLOAT16 and FLOAT16 vector examples

- content/develop/interact/search-and-query/best-practices/dev-to-prod-best-practices.md
[DOC-4717](https://redislabs.atlassian.net/browse/DOC-4717)
[DOC-4717]: https://redislabs.atlassian.net/browse/DOC-4717?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DEV: add RQE dev to prod page

- content/commands/auth/index.md
- content/commands/flushall/index.md
- content/commands/hgetall/index.md
- content/commands/hvals/index.md
- content/commands/info/index.md
- content/commands/llen/index.md
- content/commands/lpop/index.md
- content/commands/lpush/index.md
- content/commands/lrange/index.md
- content/commands/rpop/index.md
- content/commands/rpush/index.md
- content/commands/sadd/index.md
- content/commands/smembers/index.md
[DOC-4423](https://redislabs.atlassian.net/browse/DOC-4423)
Python and JavaScript tabbed code examples for the above ticket. N.B. this PR will sit until at least one of the client repo PRs is merged.
[DOC-4423]: https://redislabs.atlassian.net/browse/DOC-4423?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DOC-4423: add TCEs for various command pages

- data/components/lettuce_async.json
- data/components/lettuce_reactive.json
Up until now we were using the doctests branch to prepare the integration of Lettuce.
Switching to main to make sure we are up-to-date with the latest development.
> Use the main integration branch for documentation

- content/develop/interact/search-and-query/indexing/geoindex.md
[DOC-4731](https://redislabs.atlassian.net/browse/DOC-4731) (I used the wrong ticket number for the branch - 4732 is actually the Jedis ticket :-( )
Markup for geo indexing TCEs.
As usual, we shouldn't merge this until we get at least one client's worth of examples merged to their repo.
[DOC-4731]: https://redislabs.atlassian.net/browse/DOC-4731?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DOC-4732 added TCE markup to geo index page

- content/develop/clients/dotnet/queryjson.md
- content/develop/clients/go/queryjson.md
- content/develop/clients/jedis/queryjson.md
- content/develop/clients/php/queryjson.md
- content/develop/clients/redis-py/queryjson.md
[DOC-4345](https://redislabs.atlassian.net/browse/DOC-4345)
Also changed the link titles for the JSON query example pages (previous ones were considered a bit "boring').
[DOC-4345]: https://redislabs.atlassian.net/browse/DOC-4345?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DOC-4345 added testable JSON index/query examples for Python

- content/operate/oss_and_stack/reference/cluster-spec.md
[DOC-4747](https://redislabs.atlassian.net/browse/DOC-4747)
Fixes #1074.
[DOC-4747]: https://redislabs.atlassian.net/browse/DOC-4747?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DEV: fix typo on cluster spec page

- content/commands/incrbyfloat/index.md
Reverts redis/docs#1056
Now that the CLI is sane again, I'm reverting this PR.
> Revert "DEV: fix code example on INCRBYFLOAT command page"

- layouts/home.html
Modified design with updated text and links https://redis.io/docs/staging/home-pg-new/
> Home pg new

- content/develop/clients/_index.md
[DOC-4746](https://redislabs.atlassian.net/browse/DOC-4746)
Also put the community-supported clients into alphabetical order.
[DOC-4746]: https://redislabs.atlassian.net/browse/DOC-4746?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DOC-4746 added Dart to third party clients list

- content/develop/clients/go/transpipe.md
[DOC-4560](https://redislabs.atlassian.net/browse/DOC-4560)
Also fixed a typo in the corresponding Jedis page.
[DOC-4560]: https://redislabs.atlassian.net/browse/DOC-4560?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DOC-4560 added Go trans/pipe examples

- content/operate/oss_and_stack/stack-with-enterprise/gears-v1/installing-redisgears.md
> RS: Fix RedisGears dependencies path for offline install for later RS versions

- content/develop/get-started/data-store.md
- content/develop/get-started/document-database.md
- content/develop/get-started/rag.md
- content/develop/get-started/redis-in-ai.md
- content/develop/get-started/vector-database.md
- content/operate/rc/databases/monitor-performance.md
- content/operate/rc/rc-quickstart.md
- content/operate/rc/security/_index.md
- content/operate/rc/security/aws-transit-gateway.md
- content/operate/rc/security/cidr-whitelist.md
- content/operate/rc/security/database-security/_index.md
- content/operate/rc/security/encryption-at-rest.md
- content/operate/rc/security/private-service-connect.md
- content/operate/rc/security/shared-responsibility-model.md
- content/operate/rc/security/vpc-peering.md
- content/operate/rs/_index.md
- content/operate/rs/databases/connect/_index.md
- content/operate/rs/databases/create.md
- content/operate/rs/databases/import-export/import-data.md
- content/operate/rs/installing-upgrading/quickstarts/redis-enterprise-software-quickstart.md
> RU: add links to redis university courses/learning paths

- config.toml
- content/integrate/redis-data-integration/installation/install-vm.md
[DOC-4772](https://redislabs.atlassian.net/browse/DOC-4772) (which basically just references [RDSC-3174](https://redislabs.atlassian.net/browse/RDSC-3174) and [RDSC-3175](https://redislabs.atlassian.net/browse/RDSC-3175)).
Note that I've assumed it's only the `ufw disable` that needs `sudo`, but let me know if the other `ufw` commands do too and I'll add it in.
[DOC-4772]: https://redislabs.atlassian.net/browse/DOC-4772?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[RDSC-3174]: https://redislabs.atlassian.net/browse/RDSC-3174?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[RDSC-3175]: https://redislabs.atlassian.net/browse/RDSC-3175?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJw …
> DOC-4772 added latest RDI version variable and updated a command line

- content/embeds/rs-upgrade-paths.md
- content/operate/rs/installing-upgrading/upgrading/upgrade-database.md
DOC-4780
Staged preview: https://redis.io/docs/staging/DOC-4780/operate/rs/installing-upgrading/upgrading/upgrade-cluster/
> RS: Fix potentially misleading entries in supported upgrade paths table

- content/operate/rs/databases/durability-ha/_index.md
> RS: Edit Active-Active description on durability and HA index page

- content/operate/rs/references/compatibility/resp.md
> RS: Fix misleading note about sharded pub/sub & RESP3

- content/integrate/redis-data-integration/installation/_index.md
- content/integrate/redis-data-integration/installation/upgrade.md
[DOC-4753](https://redislabs.atlassian.net/browse/DOC-4753) (based on [this Confluence page](https://redislabs.atlassian.net/wiki/spaces/RED/pages/4856348718/Upgrading+RDI+GA+draft)).
Is there any more to add to this before merging? Also, the K8s installation section says that you should download `redis-di` - can you actually download this separately?
[DOC-4753]: https://redislabs.atlassian.net/browse/DOC-4753?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DOC-4753 added RDI upgrade guide

- config.toml
- content/integrate/redis-data-integration/reference/data-transformation/lookup.md
- content/integrate/redis-data-integration/release-notes/rdi-1-6-0.md
[DOC-4787](https://redislabs.atlassian.net/browse/DOC-4787)
Don't merge until the actual release.
[DOC-4787]: https://redislabs.atlassian.net/browse/DOC-4787?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DOC-4787 RDI release notes v1.6.0

- content/develop/interact/search-and-query/best-practices/index-mgmt-best-practices.md
> DEV: quick fix to TOC for index mgmt page

- content/develop/clients/_index.md
[DOC-4831](https://redislabs.atlassian.net/browse/DOC-4831)
The Dart client developer prefers to have the docs link point to the Github README, as noted [in this issue](https://github.com/RedisJSON/RedisJSON/issues/1323).
[DOC-4831]: https://redislabs.atlassian.net/browse/DOC-4831?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DOC-4831 updated link to Dart docs

- content/operate/kubernetes/reference/supported_k8s_distributions.md
DOC-4806
Related to RED-148786
> K8s: add container runtime note

- content/operate/oss_and_stack/stack-with-enterprise/release-notes/redisearch/redisearch-2.10-release-notes.md
- content/operate/oss_and_stack/stack-with-enterprise/release-notes/redisearch/redisearch-2.6-release-notes.md
- content/operate/oss_and_stack/stack-with-enterprise/release-notes/redisearch/redisearch-2.8-release-notes.md
[DOC-4612](https://redislabs.atlassian.net/browse/DOC-4612)
[DOC-4612]: https://redislabs.atlassian.net/browse/DOC-4612?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OP: add known limitations notes to search release notes

- content/operate/rc/rc-quickstart.md
> RC: Add links to develop quick starts to cloud quick start

- layouts/commands/list.html
- layouts/commands/single.html
[DOC-4874](https://redislabs.atlassian.net/browse/DOC-4874)
This PR changes the grouping and sorting order of the command **Filter by group...** menu and also removes the word "Stack" from each module command page. For example,
Available in: Stack / Bloom 1.0.0
becomes
Available in: Redis CE / Bloom 1.0.0
[DOC-4874]: https://redislabs.atlassian.net/browse/DOC-4874?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DEV: collapse cmd categories and remove Stack from layouts and cmd pages

- content/operate/kubernetes/re-clusters/expand-pvc.md
> K8s: add resource quota warning

- assets/css/index.css
- layouts/partials/docs-toc.html
Team,
Here, for your consideration, is a nice quality of life change. Thanks to @kaitlynmichael for the suggestion, and to @rrelledge for help thinking through and testing the CSS changes (she used her brain, I used ChatGPT :) ).
Please take some time to test out these changes on the staged preview:
https://redis.io/docs/staging/DOC-4882
> UI: provide for level indents in right side TOC

- content/integrate/redis-data-integration/installation/install-k8s.md
- content/integrate/redis-data-integration/installation/install-vm.md
- content/integrate/redis-data-integration/quick-start-guide.md
[DOC-4876](https://redislabs.atlassian.net/browse/DOC-4876)
The ticket mentions the quickstart guide but the install pages also need an update. (BTW, the info is slightly different in each page, which is why we don't just use an included snippet for this.)
[DOC-4876]: https://redislabs.atlassian.net/browse/DOC-4876?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DOC-4876 added info about how to set eviction policy and data persistence

- content/develop/interact/search-and-query/administration/configuration.md
- content/develop/interact/search-and-query/advanced-concepts/dialects.md
[DOC-4861](https://redislabs.atlassian.net/browse/DOC-4861)
[DOC-4861]: https://redislabs.atlassian.net/browse/DOC-4861?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DEV: deprecate dialogs 1, 3, and 4; config. changes

- content/operate/rs/databases/configure/proxy-policy.md
I noticed a typo on the RS proxy policy page. The REST API path for the create/POST DB request should not include a DB ID.
> RS: Fix create DB REST API path for proxy policy example

- content/integrate/redis-data-integration/reference/config-yaml-reference.md
[DOC-4852](https://redislabs.atlassian.net/browse/DOC-4852) (refers to [RDSC-3207](https://redislabs.atlassian.net/browse/RDSC-3207)).
I've tried to find out a bit about Oracle SCNs to help the explanation. Let me know if I've got any details wrong or if this is too much information. Also, are we OK with this info in the config reference or is there a better place for it?
[DOC-4852]: https://redislabs.atlassian.net/browse/DOC-4852?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[RDSC-3207]: https://redislabs.atlassian.net/browse/RDSC-3207?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DOC-4852 added RDI heartbeat mechanism info

- content/integrate/redis-data-integration/installation/upgrade.md
[DOC-4887](https://redislabs.atlassian.net/browse/DOC-4887)
[DOC-4887]: https://redislabs.atlassian.net/browse/DOC-4887?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DOC-4887 added detail about RDI password for upgrade script

- content/embeds/cluster-setup.md
DOC-2773
I changed the main Cluster Manager UI URL example from localhost to name/IP, but I thought it might be worth keeping the localhost example as an option too.
1. https://redis.io/docs/staging/DOC-2773/operate/rs/installing-upgrading/quickstarts/redis-enterprise-software-quickstart/#set-up-a-cluster
2. https://redis.io/docs/staging/DOC-2773/operate/rs/installing-upgrading/quickstarts/docker-quickstart/#set-up-a-cluster
> RS: Change localhost to name/IP in the Cluster Manager UI URL in quick starts

- content/operate/rs/installing-upgrading/upgrading/upgrade-cluster.md
- content/operate/rs/installing-upgrading/upgrading/upgrade-database.md
> RS: Add prerequisite to upgrade to a supported DB version before upgrading the cluster version

- content/operate/kubernetes/release-notes/7-8-4-releases/7-8-4-8-feb25.md
- content/operate/kubernetes/upgrade/_index.md
- content/operate/kubernetes/upgrade/openshift-cli.md
- content/operate/kubernetes/upgrade/upgrade-olm.md
> K8s: upgrade article fixes

- content/develop/reference/key-specs.md
> DEV: quick fixes to key-specs page

- content/develop/clients/jedis/produsage.md
- content/develop/clients/jedis/transpipe.md
- content/develop/clients/jedis/vecsearch.md
[DOC-4837](https://redislabs.atlassian.net/browse/DOC-4837)
Note: although this is similar to the [redis-py](https://redis.io/docs/latest/develop/clients/redis-py/vecsearch/), it's not a direct mapping. It uses a different embedding model and the preparatory steps for Jedis are a bit different in some places.
[DOC-4837]: https://redislabs.atlassian.net/browse/DOC-4837?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DOC-4837 jedis vector query example

- content/commands/hgetdel/index.md
- content/commands/hgetdel/syntax.svg
- content/commands/hgetex/index.md
- content/commands/hgetex/syntax.svg
- content/commands/hsetex/index.md
- content/commands/hsetex/syntax.svg
- data/resp2_replies.json
- data/resp3_replies.json
[DOC-4873](https://redislabs.atlassian.net/browse/DOC-4873)
[DOC-4873]: https://redislabs.atlassian.net/browse/DOC-4873?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DEV: add new HFE commands

- content/develop/clients/nodejs/vecsearch.md
[DOC-4838](https://redislabs.atlassian.net/browse/DOC-4838)
[DOC-4838]: https://redislabs.atlassian.net/browse/DOC-4838?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DOC-4838 added node-redis vector query example

- content/integrate/redis-data-integration/data-pipelines/deploy.md
- content/integrate/redis-data-integration/installation/install-k8s.md
[DOC-4833](https://redislabs.atlassian.net/browse/DOC-4833)
Clarifies that you need Redis Insight to configure/deploy RDI on K8s.
[DOC-4833]: https://redislabs.atlassian.net/browse/DOC-4833?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DOC-4833 updated deploy instructions for K8s

- content/develop/interact/search-and-query/basic-constructs/field-and-type-options.md
- content/develop/interact/search-and-query/query/full-text.md
[DOC-4855](https://redislabs.atlassian.net/browse/DOC-4855)
[DOC-4855]: https://redislabs.atlassian.net/browse/DOC-4855?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DEV: document Unicode limitations

- content/integrate/redis-data-integration/observability.md
[DOC-4912](https://redislabs.atlassian.net/browse/DOC-4912)
Basically `redis-di config-rdi` is now called `redis-di configure-rdi`, so the link to the old page name was broken.
[DOC-4912]: https://redislabs.atlassian.net/browse/DOC-4912?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DOC-4912 fix broken link to RDI configure command

- content/develop/clients/nodejs/produsage.md
- content/develop/clients/nodejs/queryjson.md
- content/develop/clients/nodejs/transpipe.md
- content/develop/clients/nodejs/vecsearch.md
[DOC-4345](https://redislabs.atlassian.net/browse/DOC-4345)
Aside from the main page, the weights of some other pages are changed to order them the same as for Jedis, etc.
[DOC-4345]: https://redislabs.atlassian.net/browse/DOC-4345?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DOC-4345 node.js JSON examples

- content/develop/interact/search-and-query/advanced-concepts/autocomplete.md
- layouts/commands/list.html
[DOC-4913](https://redislabs.atlassian.net/browse/DOC-4913)
[DOC-4913]: https://redislabs.atlassian.net/browse/DOC-4913?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DEV: add new autocomplete page

- content/develop/interact/search-and-query/administration/overview.md
[DOC-4679](https://redislabs.atlassian.net/browse/DOC-4679)
This PR doesn't address SEO for the autocomplete term, but a new page added today does. This PR now addresses the other comments in the ticket.
[DOC-4679]: https://redislabs.atlassian.net/browse/DOC-4679?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DEV: correct autocomplete usage on tech. overview page

- content/develop/clients/go/transpipe.md
- content/develop/clients/go/vecsearch.md
[DOC-4911](https://redislabs.atlassian.net/browse/DOC-4911)
[DOC-4911]: https://redislabs.atlassian.net/browse/DOC-4911?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DOC-4911 added Go vector query example

- content/develop/interact/search-and-query/advanced-concepts/escaping.md
[DOC-4910](https://redislabs.atlassian.net/browse/DOC-4910)
[DOC-4910]: https://redislabs.atlassian.net/browse/DOC-4910?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DEV: enhance tokenization docs with more references

- content/integrate/redis-data-integration/reference/api-reference/openapi.json
- content/integrate/redis-data-integration/reference/cli/redis-di-delete-all-contexts.md
- content/integrate/redis-data-integration/reference/cli/redis-di-delete-context.md
- content/integrate/redis-data-integration/reference/cli/redis-di-get-rejected.md
- content/integrate/redis-data-integration/reference/cli/redis-di-reset.md
- content/integrate/redis-data-integration/reference/cli/redis-di-upgrade.md
- content/integrate/redis-data-integration/reference/config-yaml-reference.md
This pull request updates the autogenerated docs.
> release.1.6-update-autogenerated-docs: Auto generated

- content/develop/clients/redis-py/_index.md
[DOC-4950](https://redislabs.atlassian.net/browse/DOC-4950)
Fixes #1259.
[DOC-4950]: https://redislabs.atlassian.net/browse/DOC-4950?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DEV: fix a couple of redis-py links

- content/operate/rs/security/audit-events.md
> RS: Add external listener examples to audit connection events

- content/operate/rs/installing-upgrading/upgrading/upgrade-cluster.md
> RS: Promote the first new node during rolling upgrade

- content/develop/interact/search-and-query/advanced-concepts/geo.md
- content/develop/interact/search-and-query/advanced-concepts/vectors.md
- content/develop/interact/search-and-query/basic-constructs/field-and-type-options.md
- content/develop/interact/search-and-query/indexing/geoindex.md
[DOC-4965](https://redislabs.atlassian.net/browse/DOC-4965)
Per Alon Reshef, "_We do not recommend using dialect 4 currently, prefer dialect 2._"
[DOC-4965]: https://redislabs.atlassian.net/browse/DOC-4965?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DEV: change DIALECT 4 to DIALECT 2 on adv. vector search page

- content/commands/xadd/index.md
There is a small typo error in `XADD` command doc [page](https://redis.io/docs/latest/commands/xadd/#capped-streams).
In the description of **Capped streams**, the sentence:
> due to the internal representation of steams
is using incorrect spelling "**steams**" instead of "**streams**".
> Fix typo error of the word streams

- content/integrate/redis-data-integration/installation/install-vm.md
- content/integrate/redis-data-integration/quick-start-guide.md
[DOC-4982](https://redislabs.atlassian.net/browse/DOC-4982)
[DOC-4982]: https://redislabs.atlassian.net/browse/DOC-4982?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DOC-4982 updated supported Ubuntu versions

- content/integrate/redis-data-integration/data-pipelines/prepare-dbs/oracle.md
[DOC-4985](https://redislabs.atlassian.net/browse/DOC-4985)
The info in the new "Limiting privileges" and "Revoking existing privileges" sections mainly comes from George's [technical note](https://redislabs.atlassian.net/wiki/spaces/~6318b461316bbc56c425f7f9/pages/4399136793/RDI+Notes#Improved-Security-for-Oracle), but I've also attempted to tie the new content in with the existing example.
Hopefully this works OK, but let me know if are any errors or possible improvements. In particular, Yaron's comments on the technical note mention privileges for the `signals` table and the `V_$XXX` tables. Maybe in the main example, we should set privileges on `signals` explicitly, like we do with the `V_$XXX` tables?
[DOC-4985]: https://redislabs.atlassian.net/browse/DOC-4985?atlOrigin=eyJpIjoiNWRkNT …
> DOC-4985 added section about restricting privileges

- content/operate/oss_and_stack/stack-with-enterprise/release-notes/redisearch/redisearch-2.10-release-notes.md
[DOC-4991](https://redislabs.atlassian.net/browse/DOC-4991)
[DOC-4991]: https://redislabs.atlassian.net/browse/DOC-4991?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OP: add RediSearch v2.10.14 release notes

- content/develop/interact/search-and-query/advanced-concepts/vectors.md
- static/resources/redisuniversity.yaml
> Doc 4905, add uni link to vector doc

- content/integrate/redis-data-integration/data-pipelines/deploy.md
See https://redislabs.atlassian.net/browse/RDSC-3469
> RDSC-3469 Improve documentation for PostgreSQL with mTLS

- content/develop/clients/lettuce/connect.md
- content/develop/clients/lettuce/produsage.md
Current documentation for the Lettuce client is missing important sections on how to connect and configure the client for OSS Cluster API. This PR fixes that.
> Lettuce: how to connect and configure Cluster connections

- content/develop/clients/redis-py/scaniter.md
[DOC-4952](https://redislabs.atlassian.net/browse/DOC-4952)
I'll add similar pages for the other clients also. The main reason for making this a separate page is to help with the separate ioredis migration docs and also because this is useful info for PHP, but we don't have any TCEs where we could add this stuff in.
[DOC-4952]: https://redislabs.atlassian.net/browse/DOC-4952?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DOC-4952 Python scan iterators page

- config.toml
- content/integrate/redis-data-integration/installation/install-k8s.md
- content/integrate/redis-data-integration/installation/install-vm.md
[DOC-5011](https://redislabs.atlassian.net/browse/DOC-5011)
[DOC-5011]: https://redislabs.atlassian.net/browse/DOC-5011?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DOC-5011 improved download links

- content/operate/rs/7.4/databases/configure/proxy-policy.md
- content/operate/rs/7.4/networking/configuring-aws-route53-dns-redis-enterprise.md
- content/operate/rs/7.4/networking/mdns.md
- content/operate/rs/7.4/networking/multi-ip-ipv6.md
- content/operate/rs/7.4/networking/private-public-endpoints.md
- content/operate/rs/7.4/references/cli-utilities/rladmin/node/addr.md
DOC-5045
The missing docs should have already been in the RS 7.4 version but were accidentally omitted.
> RS: Added missing networking docs back to 7.4 version

- content/operate/oss_and_stack/reference/internals/internals-vm.md
VM was deprecated in 2.4 and removed in 2.6, as  seen in the links below: 
http://oldblog.antirez.com/post/redis-2.6-is-near.html
https://raw.githubusercontent.com/antirez/redis/2.4/00-RELEASENOTES
https://raw.githubusercontent.com/antirez/redis/2.6/00-RELEASENOTES
> Correcting information about when Redis VM was deprecated

- content/operate/rs/7.4/security/encryption/tls/ciphers.md
- content/operate/rs/security/encryption/tls/ciphers.md
[DOC-4977](https://redislabs.atlassian.net/browse/DOC-4977)
[DOC-4977]: https://redislabs.atlassian.net/browse/DOC-4977?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> RS: Fixed DHE/ECDHE ciphers support note

- content/operate/oss_and_stack/install/build-stack/almalinux-rocky-8.md
- content/operate/oss_and_stack/install/build-stack/almalinux-rocky-9.md
- content/operate/oss_and_stack/install/build-stack/debian-bookworm.md
- content/operate/oss_and_stack/install/build-stack/debian-bullseye.md
- content/operate/oss_and_stack/install/build-stack/macos-13-14.md
- content/operate/oss_and_stack/install/build-stack/macos-15.md
- content/operate/oss_and_stack/install/build-stack/ubuntu-focal.md
- content/operate/oss_and_stack/install/build-stack/ubuntu-jammy.md
- content/operate/oss_and_stack/install/build-stack/ubuntu-noble.md
[DOC-5055](https://redislabs.atlassian.net/browse/DOC-5055)
@LiorKogan: please have a look at this single modified page. If you like the changes, just approve this PR and I will post additional commits for the other pages.
[DOC-5055]: https://redislabs.atlassian.net/browse/DOC-5055?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DEV: point to GitHub for source downloads

- content/develop/clients/hiredis/_index.md
- content/develop/clients/hiredis/connect.md
- content/develop/clients/hiredis/int-examples/_index.md
- content/develop/clients/hiredis/int-examples/libevent-integration.md
- content/develop/clients/hiredis/int-examples/qt-integration.md
- content/develop/clients/hiredis/issue-commands.md
[DOC-4997](https://redislabs.atlassian.net/browse/DOC-4997)
This adds info about async connections and commands and also examples of using Qt and libevent in your app.
I'm wondering if it would also be a good idea to have an example of a simple RAII C++ class (connects to Redis synchronously in the constructor, disconnects in the destructor, couple of command methods, etc). I'm happy to add this if it would be useful, but it might not be a good idea if we've got plans for a proper C++ integration in the near future. Best not to confuse people :-) 
[DOC-4997]: https://redislabs.atlassian.net/browse/DOC-4997?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DOC-4997 hiredis async API and integration examples

- content/develop/clients/nodejs/transpipe.md
The current docs omit this, and I think it's very important to know about. There are several Stack Overflow issues where people have run into problems because they weren't using executeIsolated.
> Add executeIsolated recommendation to node-redis docs

- content/develop/data-types/vector-sets/_index.md
[DOC-5073](https://redislabs.atlassian.net/browse/DOC-5073)
The examples are already merged to the redis-py repo, so these are good to go.
[DOC-5073]: https://redislabs.atlassian.net/browse/DOC-5073?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DOC-5073 added TCE markup

- content/operate/kubernetes/security/manage-rec-credentials.md
> K8s: Simplify the update REC credential step

- .github/workflows/cleanup_pr_folders.yaml
This workflow will run when pull requests are merged. It cleans up the hugo build associated with the pull request from `docs-staging-learn-redis-com/staging/`. This workflow uses Workload Identity Federation to authenticate with gcloud, which is the recommended approach.
Once tested, I'll update the workflow to also cleanup the paths on the production bucket.
> Add workflow for cleaning up pr folders

- content/develop/clients/redis-py/connect.md
- content/develop/clients/redis-py/queryjson.md
- content/develop/clients/redis-py/scaniter.md
- content/develop/clients/redis-py/transpipe.md
- content/develop/clients/redis-py/vecsearch.md
- content/develop/clients/redis-py/vecsets.md
[DOC-5073](https://redislabs.atlassian.net/browse/DOC-5073)
All feedback welcome. When we are happy with this, I'll use it as a model for similar pages in the other client sections, as soon as they add support for vector sets.
[DOC-5073]: https://redislabs.atlassian.net/browse/DOC-5073?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DOC-5073 added client-specific vector sets example for redis-py

- content/operate/oss_and_stack/install/archive/install-redis/_index.md
- content/operate/oss_and_stack/install/archive/install-redis/install-redis-from-source.md
- content/operate/oss_and_stack/install/archive/install-redis/install-redis-on-linux.md
- content/operate/oss_and_stack/install/archive/install-redis/install-redis-on-mac-os.md
- content/operate/oss_and_stack/install/archive/install-redis/install-redis-on-windows.md
- content/operate/oss_and_stack/install/install-stack/homebrew.md
[DOC-5091](https://redislabs.atlassian.net/browse/DOC-5091)
[DOC-5091]: https://redislabs.atlassian.net/browse/DOC-5091?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OP: add aliases for moved files

- content/develop/data-types/vector-sets/memory.md
- content/develop/data-types/vector-sets/performance.md
[DOC-5073](https://redislabs.atlassian.net/browse/DOC-5073)
Python code examples are also in review. I'll merge this after the Python stuff is merged.
[DOC-5073]: https://redislabs.atlassian.net/browse/DOC-5073?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DOC-5073 added quantization and reduction examples

- content/develop/clients/nodejs/connect.md
- content/develop/clients/nodejs/migration.md
- content/develop/clients/nodejs/transpipe.md
[DOC-4942](https://redislabs.atlassian.net/browse/DOC-4942)
Currently a work in progress - all suggestions welcome :-)
In particular:
- Is "migration" the right word to use here?
- Is the basic format OK with the summary table and expanded explanations?
- Are the existing items important enough to mention?
- Which other items should we have on this page?
- Do we want an explicit migration instruction emphasised for each step? (For example, just under the Pipelining section heading, we could say "**To migrate:** search for instances of `pipeline()` and replace them with `multi()...execAsPipeline()`).
[DOC-4942]: https://redislabs.atlassian.net/browse/DOC-4942?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DOC-4942 ioredis migration docs

- content/develop/clients/go/queryjson.md
[DOC-5102](https://redislabs.atlassian.net/browse/DOC-5102)
Added at the request of the Go developers.
[DOC-5102]: https://redislabs.atlassian.net/browse/DOC-5102?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DOC-5102 added Go CountOnly search example

- content/develop/get-started/vector-database.md
- content/integrate/amazon-bedrock/_index.md
This is a new PR for the existing https://github.com/redis/docs/pull/1343 because that fork doesn't build locally for me for some reason.
> Ventures fix

- content/operate/oss_and_stack/install/_index.md
- content/operate/oss_and_stack/install/archive/_index.md
- content/operate/oss_and_stack/install/build-stack/_index.md
- content/operate/oss_and_stack/install/install-stack/windows.md
- content/operate/oss_and_stack/install/upgrade/_index.md
- content/operate/oss_and_stack/install/upgrade/cluster.md
- content/operate/oss_and_stack/install/upgrade/standalone.md
[DOC-4987](https://redislabs.atlassian.net/browse/DOC-4987)
[DOC-4987]: https://redislabs.atlassian.net/browse/DOC-4987?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DEV: add upgrade instructions for Redis 8

- layouts/partials/header.html
- layouts/partials/header/products-dropdown.html
- layouts/partials/header/products-mobile.html
- layouts/partials/header/resources-dropdown.html
- layouts/partials/header/resources-mobile.html
- tailwind.config.js
Preview link:
https://redis.io/docs/staging/DOC-5086/
> Update css for header buttons

- content/develop/clients/php/connect.md
- content/develop/clients/php/queryjson.md
- content/develop/clients/php/vecsearch.md
[DOC-4544](https://redislabs.atlassian.net/browse/DOC-4544)
[DOC-4544]: https://redislabs.atlassian.net/browse/DOC-4544?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DOC-4544 added PHP vector query example

- content/develop/ai/index.md
Updates listed on the doc here: https://docs.google.com/document/d/1DYKD_9h_7yKfRoYTEgeWbwKhE7NgxVj2SOdL_FUJknU/edit?tab=t.0
> Update index.md to include updates from redis-ai-resources repo

- data/resp2_replies.json
- data/resp3_replies.json
[DOC-5118](https://redislabs.atlassian.net/browse/DOC-5118). Also removed duplicate entries.
Fixes #1445.
[DOC-5118]: https://redislabs.atlassian.net/browse/DOC-5118?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DEV: fix reply info for the HGETEX command page

- content/operate/kubernetes/release-notes/7-8-6-releases/7-8-6-1-april2025.md
- content/operate/kubernetes/upgrade/openshift-cli.md
- content/operate/kubernetes/upgrade/upgrade-olm.md
- content/operate/kubernetes/upgrade/upgrade-redis-cluster.md
> K8s: Clarify REAADB upgrade databases section

- content/develop/interact/search-and-query/administration/configuration.md
[DOC-5121](https://redislabs.atlassian.net/browse/DOC-5121)
[DOC-5121]: https://redislabs.atlassian.net/browse/DOC-5121?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DEV: fix bug on RQE>Admin>Config page

- content/operate/rc/databases/migrate-databases.md
> RC: Add safest steps to migrate data with Replica Of

- content/develop/clients/jedis/connect.md
- content/develop/clients/redis-py/connect.md
[DOC-5122](https://redislabs.atlassian.net/browse/DOC-5122)
[DOC-5122]: https://redislabs.atlassian.net/browse/DOC-5122?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DOC-5122 added info about unsupported CSC modes

- content/develop/clients/go/queryjson.md
[DOC-5111](https://redislabs.atlassian.net/browse/DOC-5111)
This basically just extends the existing JSON examples to show the differences with hashes. The code is already merged to the Go repo.
[DOC-5111]: https://redislabs.atlassian.net/browse/DOC-5111?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DOC-5111 Go hash query example

- content/develop/interact/search-and-query/administration/gc.md
Replaced "containin" with the correct verb form "contains" in the sentence:
> fix: typo in GC documentation

- content/integrate/redis-data-integration/data-pipelines/deploy.md
Updates RDI -> Deploy a pipeline documentation to include information how to use the newly added `scripts/rdi-secret.sh` shell script that will be used to set target and source database secrets.
> RDSC-3487: Update RDI -> Deploy a pipeline documentation

- content/operate/rc/security/private-service-connect.md
Update to reflect reduction of 40 to a single endpoint. Removing reference to minimal support Redis version that is now outdated.
> Reduction of 40 to a single PSC endpoint

- content/develop/data-types/_index.md
[DOC-5127](https://redislabs.atlassian.net/browse/DOC-5127)
Correcting an oversight from my CE8-rc1 work.
[DOC-5127]: https://redislabs.atlassian.net/browse/DOC-5127?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DEV: add vector set to the data type landing page

- content/develop/clients/nodejs/queryjson.md
- content/develop/clients/php/queryjson.md
[DOC-5108](https://redislabs.atlassian.net/browse/DOC-5108) and [DOC-5112](https://redislabs.atlassian.net/browse/DOC-5112)
Double deja vu!
[DOC-5108]: https://redislabs.atlassian.net/browse/DOC-5108?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DOC-5112]: https://redislabs.atlassian.net/browse/DOC-5112?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DOC-5108 and DOC-5112 hash query examples for JS and PHP

- content/operate/rc/databases/import-data.md
> RC: Import data issue

- content/develop/clients/go/vecsearch.md
- content/develop/clients/redis-py/vecsearch.md
[DOC-5149](https://redislabs.atlassian.net/browse/DOC-5149) and [DOC-5153](https://redislabs.atlassian.net/browse/DOC-5153)
For the vector pages, it's the JSON info that is missing rather than hash.
[DOC-5149]: https://redislabs.atlassian.net/browse/DOC-5149?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DOC-5153]: https://redislabs.atlassian.net/browse/DOC-5153?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DOC-5149 and DOC-5153 added Python and Go vector JSON examples

- content/integrate/redis-data-integration/data-pipelines/data-denormalization.md
[DOC-5126](https://redislabs.atlassian.net/browse/DOC-5126)
Slight emphasis of an important detail and fixes to typos in attribute names.
[DOC-5126]: https://redislabs.atlassian.net/browse/DOC-5126?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DOC-5126 small fixes to RDI denormalisation page

- content/develop/interact/search-and-query/advanced-concepts/query_syntax.md
The escaping logic is implemented [here](https://github.com/RediSearch/RediSearch/blob/d988bde19385cd4e6aeec7987d344819eda66ab4/src/wildcard.c#L136) and it doesn't treat `'` as an escaping symbol.
> [RediSearch] `\` is the only valid symbol for escaping in wildcard matching

- content/develop/clients/dotnet/vecsearch.md
- content/develop/clients/nodejs/vecsearch.md
[DOC-5150](https://redislabs.atlassian.net/browse/DOC-5150) and [DOC-5151](https://redislabs.atlassian.net/browse/DOC-5151)
For the C# examples, I'm not sure if it's clearer to define the `GetEmbedding` and `GetFloatEmbedding` functions the way I have, or if it would be better to have the `GetFloatEmbedding` as it is with another function to convert the result to a binary string. I guess it doesn't make much difference but I'd be happy to hear any thoughts about whether one approach is better than the other.
[DOC-5150]: https://redislabs.atlassian.net/browse/DOC-5150?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DOC-5151]: https://redislabs.atlassian.net/browse/DOC-5151?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l …
> DOC-5150 and DOC-5151 JavaScript and C# vector json examples

- content/operate/oss_and_stack/stack-with-enterprise/release-notes/redisbloom/redisbloom-2.4-release-notes.md
- content/operate/oss_and_stack/stack-with-enterprise/release-notes/redisbloom/redisbloom-2.6-release-notes.md
- content/operate/oss_and_stack/stack-with-enterprise/release-notes/redisbloom/redisbloom-2.8-release-notes.md
- content/operate/oss_and_stack/stack-with-enterprise/release-notes/redisjson/redisjson-2.4-release-notes.md
- content/operate/oss_and_stack/stack-with-enterprise/release-notes/redisjson/redisjson-2.6-release-notes.md
- content/operate/oss_and_stack/stack-with-enterprise/release-notes/redisjson/redisjson-2.8-release-notes.md
- content/operate/oss_and_stack/stack-with-enterprise/release-notes/redistimeseries/redistimeseries-1.10-release-notes.md
- content/operate/oss_and_stack/stack-with-enterprise/release-notes/redistimeseries/redistimeseries-1.12-release-notes.md
- content/operate/oss_and_stack/stack-with-enterprise/release-notes/redistimeseries/redistimeseries-1.8-release-notes.md
[DOC-5157](https://redislabs.atlassian.net/browse/DOC-5157)
[DOC-5157]: https://redislabs.atlassian.net/browse/DOC-5157?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OP: add module release notes

- content/develop/clients/php/vecsearch.md
[DOC-5154](https://redislabs.atlassian.net/browse/DOC-5154)
[DOC-5154]: https://redislabs.atlassian.net/browse/DOC-5154?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DOC-5154 added JSON vector search examples for PHP

- content/develop/clients/lettuce/produsage.md
Document that Netty Native transports should be installed in order to set TCP-level timeouts.
> Lettuce: Improve guidelines on timeouts

- content/operate/rs/references/rest-api/objects/bootstrap/_index.md
- content/operate/rs/release-notes/rs-7-8-releases/_index.md
- content/operate/rs/release-notes/rs-7-8-releases/rs-7-8-6-60.md
DOC-5100
- [RS 7.8.6-60 release notes](https://redis.io/docs/staging/DOC-5100/operate/rs/release-notes/rs-7-8-releases/rs-7-8-6-60/)
TODO:
1. I still need to add the Ubuntu 22 checksum after it becomes available.
> RS 7.8.6 end of April maintenance release docs

- content/commands/hsetex/index.md
Pretty sure this is a typo, the options should be for `HSETEX` not `HGETEX`. Gave me pause while reading the docs...
> Fix small typo in HSETEX index.md

- content/develop/clients/dotnet/transpipe.md
[DOC-4560](https://redislabs.atlassian.net/browse/DOC-4560)
Not a major change -same examples, but they're now testable examples on the NRedisStack repo.
[DOC-4560]: https://redislabs.atlassian.net/browse/DOC-4560?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DOC-4560 made C# trans/pipe examples testable

- config.toml
- content/integrate/redis-data-integration/installation/install-k8s.md
- content/integrate/redis-data-integration/installation/install-vm.md
- content/integrate/redis-data-integration/installation/upgrade.md
- content/integrate/redis-data-integration/release-notes/rdi-1-6-7.md
[DOC-5201](https://redislabs.atlassian.net/browse/DOC-5201)
I've taken a guess that the word "scheme" in the release note headline should have been "schema", but let me know if this is incorrect. Assuming it should be "schema", I'll update the release notes in the RDI repo with the same change.
[DOC-5201]: https://redislabs.atlassian.net/browse/DOC-5201?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DOC-5201 added release notes for RDI v1.6.7

- content/integrate/redis-data-integration/data-pipelines/data-denormalization.md
- content/integrate/redis-data-integration/data-pipelines/data-pipelines.md
[DOC-5197](https://redislabs.atlassian.net/browse/DOC-5197)
Only used in a couple of places, as it turns out.
[DOC-5197]: https://redislabs.atlassian.net/browse/DOC-5197?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DOC-5197 remove mentions of Debezium `application.config` in RDI config docs

- content/operate/rs/installing-upgrading/upgrading/_index.md
- content/operate/rs/installing-upgrading/upgrading/upgrade-cluster.md
- content/operate/rs/installing-upgrading/upgrading/upgrade-database.md
- content/operate/rs/installing-upgrading/upgrading/upgrade-os.md
> RS: Emphasize upgrade prerequisites

- content/operate/kubernetes/active-active/_index.md
- content/operate/kubernetes/active-active/create-aa-crdb-cli.md
- content/operate/kubernetes/active-active/create-reaadb.md
- content/operate/kubernetes/active-active/edit-clusters.md
- content/operate/kubernetes/active-active/global-db-secret.md
- content/operate/kubernetes/active-active/prepare-clusters.md
- content/operate/kubernetes/architecture/_index.md
- content/operate/kubernetes/architecture/deployment-options.md
- content/operate/kubernetes/deployment/container-images.md
- content/operate/kubernetes/deployment/helm.md
- content/operate/kubernetes/deployment/openshift/_index.md
- content/operate/kubernetes/deployment/quick-start.md
- content/operate/kubernetes/networking/_index.md
- content/operate/kubernetes/networking/ingress.md
- content/operate/kubernetes/networking/ingressorroutespec.md
- content/operate/kubernetes/networking/istio-ingress.md
- content/operate/kubernetes/re-clusters/cluster-recovery.md
- content/operate/kubernetes/re-clusters/connect-prometheus-operator.md
- content/operate/kubernetes/re-clusters/multi-namespace.md
- content/operate/kubernetes/re-databases/db-controller.md
- content/operate/kubernetes/recommendations/persistent-volumes.md
- content/operate/kubernetes/recommendations/sizing-on-kubernetes.md
- content/operate/kubernetes/upgrade/_index.md
Removed /content from one relref
Removed .md from all others
> K8s: relref fixes

- content/operate/rc/subscriptions/bring-your-own-cloud/iam-resources/aws-console.md
- content/operate/rc/subscriptions/bring-your-own-cloud/iam-resources/cloudformation.md
- content/operate/rc/subscriptions/bring-your-own-cloud/iam-resources/terraform.md
- content/operate/rc/subscriptions/view-pro-subscription.md
- static/code/rv/terraformIAMTemplate.json
> RC BYOC: Fix IAM credential steps and relref

- layouts/shortcodes/external-json.html
Example usage:
```
{{< external-json "https://raw.githubusercontent.com/Redislabs-Solution-Architects/cloudformation-aws-Redislabs-Cloud-Account-IAM-Resources/refs/heads/master/RedisLabsInstanceRolePolicy.json" >}}
```
> Create hugo shortcode for embedding external json files

- content/develop/clients/nodejs/connect.md
- content/develop/clients/nodejs/queryjson.md
- content/develop/clients/nodejs/transpipe.md
- content/develop/clients/nodejs/vecsearch.md
[DOC-5219](https://redislabs.atlassian.net/browse/DOC-5219)
[DOC-5219]: https://redislabs.atlassian.net/browse/DOC-5219?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DOC-5219 implemented suggested node-redis updates for v5.0.0

- content/develop/clients/redis-py/produsage.md
- layouts/shortcodes/checklist-item.html
- layouts/shortcodes/checklist.html
[DOC-5065](https://redislabs.atlassian.net/browse/DOC-5065)
This is loosely based on the [Jedis](https://redis.io/docs/latest/develop/clients/jedis/produsage/) production page, but the advice is, of course, slightly different for redis-py.
All feedback welcome. In particular, are there any more good bits of advice or common exception types we should add here?
[DOC-5065]: https://redislabs.atlassian.net/browse/DOC-5065?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DOC-5065 Python production usage page

- content/develop/clients/nodejs/produsage.md
[DOC-5193](https://redislabs.atlassian.net/browse/DOC-5193)
Only change so far is adding the checklist, but all suggestions are welcome :-) 
[DOC-5193]: https://redislabs.atlassian.net/browse/DOC-5193?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DOC-5193 reviewed node-redis production usage page

- content/develop/clients/dotnet/condexec.md
- content/develop/clients/dotnet/connect.md
- content/develop/clients/dotnet/produsage.md
- content/develop/clients/dotnet/queryjson.md
- content/develop/clients/dotnet/transpipe.md
- content/develop/clients/dotnet/vecsearch.md
[DOC-5192](https://redislabs.atlassian.net/browse/DOC-5192)
This is intended to give recommendations for production usage like the [Jedis page](https://redis.io/docs/latest/develop/clients/jedis/produsage/), but it's actually quite difficult to find any advice for NRedisStack :-) (Client-side caching isn't implemented, and most of the stuff recommended for Jedis either happens by default or is handled automatically.)
I'd love to hear ideas - if we can't think of any more recommendations, then maybe this page isn't necessary for NRedisStack and we should just have a short section about this stuff in the landing page.
[DOC-5192]: https://redislabs.atlassian.net/browse/DOC-5192?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DOC-5192 added C# production usage page

- content/embeds/rdi-db-reqs.md
- content/embeds/rdi-vm-reqs.md
- content/integrate/redis-data-integration/installation/_index.md
- content/integrate/redis-data-integration/installation/install-k8s.md
- content/integrate/redis-data-integration/installation/install-vm.md
- content/integrate/redis-data-integration/installation/upgrade.md
- content/integrate/redis-data-integration/quick-start-guide.md
See https://redislabs.atlassian.net/browse/RDSC-3533
> RDSC-3533 Update RDI documentation, part 1

- content/integrate/redis-data-integration/data-pipelines/data-pipelines.md
- content/integrate/redis-data-integration/reference/api-reference/openapi.json
1. The first commit is just reformatting the `openapi.json`. It makes reviewing the following changes much simpler.
2. This second one contains the actual changes that synchronise the spec here with the one from the API
3. The third just adds a single note on how to test the jobs and refers to the API spec.
>  RDSC-3587 Update public docs on how to test transformations

- config.toml
- content/integrate/redis-data-integration/installation/install-k8s.md
- content/integrate/redis-data-integration/installation/install-vm.md
- content/integrate/redis-data-integration/installation/upgrade.md
- content/integrate/redis-data-integration/release-notes/rdi-1-8-0.md
- layouts/shortcodes/rdi-version.html
[DOC-5223](https://redislabs.atlassian.net/browse/DOC-5223)
Also included the fixes for the version numbers in links, etc. 
[DOC-5223]: https://redislabs.atlassian.net/browse/DOC-5223?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DOC-5223 RDI release notes for v1.8.0

- content/develop/reference/protocol-spec.md
[DOC-5236](https://redislabs.atlassian.net/browse/DOC-5236)
[DOC-5236]: https://redislabs.atlassian.net/browse/DOC-5236?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DEV: update RESP2/3 annotation

- content/operate/oss_and_stack/install/upgrade/cluster.md
[DOC-5237](https://redislabs.atlassian.net/browse/DOC-5237)
[DOC-5237]: https://redislabs.atlassian.net/browse/DOC-5237?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OP: add annotation re. cluster upgrade and RQE

- content/operate/oss_and_stack/stack-with-enterprise/release-notes/redisce/redisos-8.0.1-release-notes.md
[DOC-5242](https://redislabs.atlassian.net/browse/DOC-5242)
[DOC-5242]: https://redislabs.atlassian.net/browse/DOC-5242?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OP: add ROS 8.0.1 release notes

- content/operate/rs/release-notes/rs-7-8-releases/rs-7-8-6-60.md
> RS: Added shard migration status resolved issue to the RS 7.8.6-60 release notes

- content/develop/_index.md
- layouts/develop/list.html
- layouts/develop/single.html
[DOC-5244](https://redislabs.atlassian.net/browse/DOC-5244)
Add a Redis CLI widget to the top of the Develop page, kind of like the former IO page.
The changes to layouts/develop/list.html can go either before or after the `{{ .Content }}` line. For any other placement, we'd need a custom (one-off) partial.
[DOC-5244]: https://redislabs.atlassian.net/browse/DOC-5244?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DEV: beginning of Develop landing page redesign

- content/integrate/redis-data-integration/architecture.md
- content/integrate/redis-data-integration/data-pipelines/data-pipelines.md
- content/integrate/redis-data-integration/data-pipelines/deploy.md
See https://redislabs.atlassian.net/browse/RDSC-3533
> RDSC-3533 Update RDI documentation, part 2

- content/operate/rc/databases/configuration/active-active-redis.md
- content/operate/rc/databases/configuration/high-availability.md
- content/operate/rc/databases/create-database/create-active-active-database.md
> RC: Active-Active Limitations and High Availability changes

- content/operate/rs/installing-upgrading/upgrading/upgrade-cluster.md
- content/operate/rs/installing-upgrading/upgrading/upgrade-os.md
> RS: Added DNS record update step to cluster and OS upgrade instructions

- content/operate/rs/databases/import-export/import-data.md
> RS: Added REST API examples to import databases

- content/operate/rs/installing-upgrading/install/customize-user-and-group.md
> RS: All nodes in a cluster should use the same user/group during install

- content/operate/rs/references/rest-api/requests/users/authorize.md
- content/operate/rs/references/rest-api/requests/users/password.md
- content/operate/rs/release-notes/rs-7-8-releases/_index.md
- content/operate/rs/release-notes/rs-7-8-releases/rs-7-8-2-34.md
- content/operate/rs/security/access-control/manage-passwords/rotate-passwords.md
> RS: Fixed outdated password rotation and authorize user docs

- assets/css/index.css
- layouts/commands/list.html
- layouts/commands/single.html
- layouts/develop/list.html
- layouts/develop/single.html
- layouts/integrate/list.html
- layouts/integrate/single.html
- layouts/integration/list.html
- layouts/integration/single.html
- layouts/partials/scripts.html
Staging link: https://redis.io/docs/staging/DOC-5217/
> Add copy to clipboard for code snippets

- content/develop/clients/jedis/amr.md
[DOC-4816](https://redislabs.atlassian.net/browse/DOC-4816)
I think I've figured this out OK from the source code and the [README](https://github.com/redis/jvm-redis-authx-entraid) but I wasn't able to run the code, so please be alert for mistakes :-)
Note: I've assumed that SSL is required because that was stated in the [redis-py-entraid README](https://github.com/redis/redis-py-entraid), so I've added some SSL details for the Jedis example too.
[DOC-4816]: https://redislabs.atlassian.net/browse/DOC-4816?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DOC-4816 added Jedis AMR connection page

- content/develop/clients/nodejs/amr.md
[DOC-4989](https://redislabs.atlassian.net/browse/DOC-4989)
I've worked from the repo [README](https://github.com/redis/node-redis/blob/master/packages/entraid/README.md) file and also incorporated some stuff from the other clients' AMR pages. Any suggestions or corrections are most welcome :-) 
[DOC-4989]: https://redislabs.atlassian.net/browse/DOC-4989?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DOC-4989 added node-js AMR page

- content/develop/clients/lettuce/amr.md
[DOC-4819](https://redislabs.atlassian.net/browse/DOC-4819)
I'm assuming this can basically be the same as the [Jedis page](https://github.com/redis/docs/pull/1166) except for the different connection example code at the end.
I've attempted to figure out the example by looking at the source code, but I haven't been able to run it, so it probably contains some mistakes :-) Also, I'm not sure if the async test command at the end is overkill for this.
[DOC-4819]: https://redislabs.atlassian.net/browse/DOC-4819?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DOC-4819 added Lettuce AMR example

- content/develop/interact/search-and-query/advanced-concepts/scoring.md
Just a correction as it has been forgotten to change the documentation about BM25 being the default scoring mechanism now.
Maybe you may also want to change the order
> BM25 is now the default scoring mechanism

- content/develop/clients/redis-py/amr.md
Minor fix - AMR docs were recently added but specifically for Python, the weighting of the AMR page put it above the basic Connect page in the listing (we definitely want basic connect to be first).
> DOC-4815 changed ordering of Python AMR page

- layouts/develop/single.html
- layouts/integration/list.html
- layouts/integration/single.html
- layouts/operate/list.html
- layouts/operate/single.html
[DOC-5262](https://redislabs.atlassian.net/browse/DOC-5262)
These changes:
1. Allow the right side, in-page TOC to be hidden if more horizontal space is needed on a list or single page.
To trigger, use the following frontmatter:
`hideTOC: true`
2. Make is possible for pages in OP and (individual) Integrate to take up all the horizontal space in the current view frame.
[DOC-5262]: https://redislabs.atlassian.net/browse/DOC-5262?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DEV/OP: make is possible to hide in-page TOC with frontmatter

- content/develop/clients/nodejs/connect.md
[DOC-5218](https://redislabs.atlassian.net/browse/DOC-5218)
[DOC-5218]: https://redislabs.atlassian.net/browse/DOC-5218?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DOC-5218 node-js client-side caching docs

- content/operate/rs/release-notes/rs-7-8-releases/_index.md
- content/operate/rs/release-notes/rs-7-8-releases/rs-7-8-4-18.md
- content/operate/rs/release-notes/rs-7-8-releases/rs-7-8-4-66.md
- content/operate/rs/release-notes/rs-7-8-releases/rs-7-8-4-95.md
- content/operate/rs/release-notes/rs-7-8-releases/rs-7-8-6-13.md
- content/operate/rs/release-notes/rs-7-8-releases/rs-7-8-6-36.md
> RS: Added known issue and workaround for import RDB file in RHEL 8/9 to RS 7.8.4 release notes

- content/develop/clients/redis-py/prob.md
- content/develop/data-types/probabilistic/t-digest.md
[DOC-5225](https://redislabs.atlassian.net/browse/DOC-5225)
...and as a bonus feature, it fixes a small issue with the headings in the main t-digest page.
A few points:
- I thought it was best to cover all these types fairly briefly in one page, but it has turned out to be quite a long page. I think it's just about comfortable to read, but let me know if you think it should be split into two or more pages.
- I've kept the examples brief to introduce these types rather than cover them in detail (we already have reference pages for them all). Do the examples need any more info or is there anything major missing from them?
- Does the breakdown of set operations and stats basically make sense?
[DOC-5225]: https://redislabs.atlassian.net/browse/DOC-5225?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDl …
> DOC-5225 Python probabilistic data type examples

- content/operate/rs/databases/active-active/syncer.md
- Add troubleshooting section for unrecoverable syncer errors
- Document exit code 4 behavior and DMC response
- Provide recovery procedures for regular and Active-Active databases
- Include REST API and crdb-cli recovery methods
- Add clear examples with placeholder values
Resolves DOC-1554
> Add syncer error recovery troubleshooting documentation

- layouts/commands/list.html
[DOC-5296](https://redislabs.atlassian.net/browse/DOC-5296)
Just a bit of tidying up in preparation for a larger set of changes to the commands page structure and adding versioning. See the [governing epic](https://redislabs.atlassian.net/browse/DOC-5297).
[DOC-5296]: https://redislabs.atlassian.net/browse/DOC-5296?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DEV: simplify commands list layout

- content/operate/rs/databases/auto-tiering/_index.md
> RS: Added key/value size limits for flash storage

- content/operate/rs/7.4/clusters/maintenance-mode.md
- content/operate/rs/7.8/clusters/maintenance-mode.md
- content/operate/rs/clusters/maintenance-mode.md
> RS: Clarified quorum loss check and warning when activating maintenance mode

- content/embeds/port-53.md
DOC-3595
Staged preview: https://redis.io/docs/staging/DOC-3595/operate/rs/installing-upgrading/install/prepare-install/port-availability/#os-conflicts-with-port-53
> RS: Prevent dnsmasq from using port 53

- config.toml
- layouts/_default/section.md
- layouts/_default/single.md
https://redis.io/docs/staging/DOC-5280/
> Add markdown output in preparation for llms.txt

- content/develop/clients/client-side-caching.md
- content/develop/clients/jedis/_index.md
- content/develop/clients/lettuce/_index.md
[DOC-5306](https://redislabs.atlassian.net/browse/DOC-5306)
As a bonus fix, I also added a line for node-redis to the table of clients supporting CSC.
[DOC-5306]: https://redislabs.atlassian.net/browse/DOC-5306?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DOC-5306 updated Jedis and Lettuce versions and added node-redis CSC

- content/operate/kubernetes/deployment/container-images.md
> K8s: update example to use 7.22.0-7

- layouts/partials/header/products-dropdown.html
- layouts/partials/header/products-mobile.html
- Reorganize Products section from 3 columns to 2 columns layout
- Remove Redis for AI from Products section (now separate top-level menu)
- Move Redis Data Integration from Products to Tools section
- Add Redis LangCache to Tools section
- Update Redis Open Source link to point to /open-source/ instead of /docs/latest/get-started/
- Update Clients link text to 'Clients & Connectors' for consistency
- Apply changes to both desktop dropdown and mobile menu
Products section now contains:
- Redis Cloud
- Redis Software
- Redis Open Source
Tools section now contains:
- Redis LangCache
- Redis Insight
- Redis Data Integration
- Clients & Connectors
Matches the current structure on redis.io main site
> Update Products menu to match main site structure (DOC-5305)

- content/develop/clients/nodejs/migration.md
Below are some findings and suggestions for improving the [ioredis migration docs](https://redis.io/docs/latest/develop/clients/nodejs/migration/)
The below `await` in the node-redis section is redundant
```js
const client = await createClient();
```
`node-redis` supports callbacks via Legacy Mode
`node-redis` has a [SETNX command](https://github.com/redis/node-redis/blob/master/packages/client/lib/commands/SETNX.ts)
> ioredis migration docs suggestions

- content/develop/clients/go/amr.md
- content/develop/clients/go/connect.md
- content/develop/clients/go/produsage.md
- content/develop/clients/go/queryjson.md
- content/develop/clients/go/transpipe.md
- content/develop/clients/go/vecsearch.md
[DOC-4990](https://redislabs.atlassian.net/browse/DOC-4990)
This (hopefully) gives Go about the same level of detail as the [Jedis AMR docs](https://redis.io/docs/latest/develop/clients/jedis/amr/).
All feedback is welcome, but a few things to note:
- The other clients' docs/API refer to service principals explicitly, but the Go README doesn't. I'm assuming this is covered by [client secret authentication](https://github.com/redis/go-redis-entraid?tab=readme-ov-file#client-secret-authentication), but let me know if this is not the case.
- I've given the values for some of the constants (eg, `AuthorityTypeMultiTenant` = "multi-tenant") but let me know if it's better not to do this.
- The Go examples roughly match the equivalent examples for Jedis, but let me know if there is anything extra …
> DOC-4990 AMR connection page for Go

- content/integrate/redis-data-integration/installation/install-k8s.md
[DOC-5311](https://redislabs.atlassian.net/browse/DOC-5311)
The download links were OK, btw.
[DOC-5311]: https://redislabs.atlassian.net/browse/DOC-5311?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DOC-5311 fixed filename in Helm install examples

- content/operate/rs/clusters/logging/diagnostic-logging.md
> RS: Fixed broken link to diagnostic logging API reference

- content/develop/whats-new/8-0.md
a Note: this (new) version of the What's new for Redis 8 does not mention RQE, JSON, etc. as new features since this section describes feature sets. And these capabilities existed in the previous feature sets
> Updating what's new for Redis 8

- content/operate/kubernetes/networking/_index.md
> K8s: OSS Cluster API limitation

- content/operate/rs/7.4/references/metrics/database-operations.md
- content/operate/rs/7.8/references/metrics/database-operations.md
- content/operate/rs/references/metrics/database-operations.md
These links were broken by the following commit:
76fdf8b0 (SITE-WIDE: double-slash (//) correction (#363), 2024-06-27)
> Fix broken links in metrics documentation.

- content/integrate/redis-data-integration/installation/install-vm.md
[DOC-5337](https://redislabs.atlassian.net/browse/DOC-5337)
[DOC-5337]: https://redislabs.atlassian.net/browse/DOC-5337?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DOC-5337 added warning about /var mounted with noexec

- content/develop/clients/redis-py/amr.md
Fix typo in pip install command for redis-py entraid extension
> Fix typo in install for redis-py entraid extension

- content/commands/bf.add.md
- content/commands/bf.card.md
- content/commands/bf.exists.md
- content/commands/bf.info.md
- content/commands/bf.insert.md
- content/commands/bf.loadchunk.md
- content/commands/bf.madd.md
- content/commands/bf.mexists.md
- content/commands/bf.reserve.md
- content/commands/bf.scandump.md
[DOC-5317](https://redislabs.atlassian.net/browse/DOC-5317)
The return information is at the bottom of each page.
[DOC-5317]: https://redislabs.atlassian.net/browse/DOC-5317?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DEV: add RESP2/3 return information to the Bloom filter commands

- content/operate/rc/rc-quickstart.md
> RC: Quickstart changes

- content/commands/cf.add.md
- content/commands/cf.addnx.md
- content/commands/cf.count.md
- content/commands/cf.del.md
- content/commands/cf.exists.md
- content/commands/cf.info.md
- content/commands/cf.insert.md
- content/commands/cf.insertnx.md
- content/commands/cf.loadchunk.md
- content/commands/cf.mexists.md
- content/commands/cf.reserve.md
- content/commands/cf.scandump.md
[DOC-5318](https://redislabs.atlassian.net/browse/DOC-5318)
The return information is at the bottom of each page.
[DOC-5318]: https://redislabs.atlassian.net/browse/DOC-5318?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add RESP2/3 return information to the Cuckoo filter commands

- content/commands/ft.search.md
[DOC-5346](https://redislabs.atlassian.net/browse/DOC-5346)
[DOC-5346]: https://redislabs.atlassian.net/browse/DOC-5346?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DEV: add deprecation notice for NOSTOPWORDS

- content/operate/oss_and_stack/stack-with-enterprise/release-notes/redisearch/redisearch-2.10-release-notes.md
[DOC-5345](https://redislabs.atlassian.net/browse/DOC-5345)
[DOC-5345]: https://redislabs.atlassian.net/browse/DOC-5345?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OP: add RediSearch v2.10.19 release notes

- content/develop/tools/insight/rdi-connector.md
- content/integrate/redis-data-integration/data-pipelines/prepare-dbs/oracle.md
- content/integrate/redis-data-integration/installation/install-k8s.md
- content/integrate/redis-data-integration/installation/install-vm.md
- content/integrate/redis-data-integration/observability.md
- content/integrate/redis-data-integration/quick-start-guide.md
[DOC-5347](https://redislabs.atlassian.net/browse/DOC-5347)
[DOC-5347]: https://redislabs.atlassian.net/browse/DOC-5347?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DOC-5347 fixed links broken by RDI restructure

- content/develop/clients/dotnet/prob.md
[DOC-5226](https://redislabs.atlassian.net/browse/DOC-5226)
C# equivalent to [this page](https://redis.io/docs/latest/develop/clients/redis-py/prob/) for Python.
[DOC-5226]: https://redislabs.atlassian.net/browse/DOC-5226?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DOC-5226 C# probabilistic data type examples

- content/develop/clients/go/prob.md
[DOC-5229](https://redislabs.atlassian.net/browse/DOC-5229)
Go equivalent of [this page](https://redis.io/docs/latest/develop/clients/redis-py/prob/)
[DOC-5229]: https://redislabs.atlassian.net/browse/DOC-5229?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DOC-5229 Go probabilistic data type examples

- content/develop/interact/search-and-query/indexing/_index.md
[DOC-5357](https://redislabs.atlassian.net/browse/DOC-5357)
Change:
"You cannot index JSON objects. If the JSONPath expression returns an object, it will be ignored."
to:
"You cannot index JSON objects. If the JSONPath expression returns an object, an indexing error will be returned."
[DOC-5357]: https://redislabs.atlassian.net/browse/DOC-5357?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DEV: fix bug on indexing page

- content/operate/oss_and_stack/stack-with-enterprise/release-notes/redisearch/redisearch-2.10-release-notes.md
- content/operate/oss_and_stack/stack-with-enterprise/release-notes/redisearch/redisearch-2.6-release-notes.md
- content/operate/oss_and_stack/stack-with-enterprise/release-notes/redisearch/redisearch-2.8-release-notes.md
[DOC-5358](https://redislabs.atlassian.net/browse/DOC-5358)
2.6.31
2.8.28
2.10.20
[DOC-5358]: https://redislabs.atlassian.net/browse/DOC-5358?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DEV: add RediSearch release notes

- content/commands/cms.incrby.md
- content/commands/cms.info.md
- content/commands/cms.initbydim.md
- content/commands/cms.initbyprob.md
- content/commands/cms.merge.md
- content/commands/cms.query.md
[DOC-5319](https://redislabs.atlassian.net/browse/DOC-5319)
The return information is at the bottom of each page.
[DOC-5319]: https://redislabs.atlassian.net/browse/DOC-5319?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DEV: add RESP2/3 return information to the CMS commands

- content/commands/topk.add.md
- content/commands/topk.count.md
- content/commands/topk.incrby.md
- content/commands/topk.info.md
- content/commands/topk.list.md
- content/commands/topk.query.md
- content/commands/topk.reserve.md
[DOC-5323](https://redislabs.atlassian.net/browse/DOC-5323)
The return info is at the bottom of each page.
[DOC-5323]: https://redislabs.atlassian.net/browse/DOC-5323?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DEV: add RESP2/3 info to the top-k commands

- content/commands/tdigest.add.md
- content/commands/tdigest.byrank.md
- content/commands/tdigest.byrevrank.md
- content/commands/tdigest.cdf.md
- content/commands/tdigest.create.md
- content/commands/tdigest.info.md
- content/commands/tdigest.max.md
- content/commands/tdigest.merge.md
- content/commands/tdigest.min.md
- content/commands/tdigest.quantile.md
- content/commands/tdigest.rank.md
- content/commands/tdigest.reset.md
- content/commands/tdigest.revrank.md
- content/commands/tdigest.trimmed_mean.md
[DOC-5322](https://redislabs.atlassian.net/browse/DOC-5322)
The return info is at the bottom of each page.
[DOC-5322]: https://redislabs.atlassian.net/browse/DOC-5322?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DEV: add RESP2/3 return information to the t-digest commands

- content/develop/clients/redis-py/_index.md
Will make the link work once PR is approved
> Add link to binderhub environment for Python client example

- content/operate/rc/subscriptions/bring-your-own-cloud/iam-resources/aws-console.md
- content/operate/rc/subscriptions/bring-your-own-cloud/iam-resources/terraform.md
- layouts/shortcodes/line-limit.html
- layouts/shortcodes/scrollable-code.html
Usage:
{{< scrollable-code lines="10" >}}
Content with many lines here...
{{< /scrollable-code >}}
Ideally used for just code blocks. In theory, you could use this for any content, but I think that would require a lot of re-tooling.
> Implement scrollable code

- content/commands/bitop.md
- content/develop/data-types/bitmaps.md
[DOC-5367](https://redislabs.atlassian.net/browse/DOC-5367)
[DOC-5367]: https://redislabs.atlassian.net/browse/DOC-5367?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DOC-5367: update bitmap docs for ROS8.2

- content/develop/reference/protocol-spec.md
This appeared in the table as just a backtick in the [protocol spec page](https://redis.io/docs/latest/develop/reference/protocol-spec/) so it confused me for a bit. I think in a markdown table, using `|` is pretty risky. This fix seems to render the `|` correctly in a markdown preview:
> Fix Attribute's first byte in protocol spec

- content/integrate/redis-data-integration/observability.md
I used some AI magic and a few sources - Example metrics from a running RDI instance, the codebase, Debezium docs, etc.
I think the format is good, but the alerting recommendations I'm not sure if the alerting recommendations are correct.
> DOC-5338: RDI enchance observability page with more metrics information

- assets/css/index.css
- layouts/partials/tabbed-clients-example.html
[DOC-4638](https://redislabs.atlassian.net/browse/DOC-4638) and [DOC-5396](https://redislabs.atlassian.net/browse/DOC-5396)
Both changes are mainly to accommodate Lettuce examples: they have long lines and big indents, and also each Lettuce snippet typically needs two examples (async and reactive). 
[DOC-4638]: https://redislabs.atlassian.net/browse/DOC-4638?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DOC-5396]: https://redislabs.atlassian.net/browse/DOC-5396?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DOC-4638 DOC-5396 TCE box improvements

- content/develop/use/patterns/distributed-locks.md
Fixed grammatical mistake on the sentence use it as a starting point for the implementations `or` more complex or alternative designs. to use it as a starting point for the implementations `of` more complex or alternative designs.
> Update grammar on  distributed-locks.md

- content/operate/rc/databases/configuration/data-eviction-policies.md
- content/operate/rc/databases/migrate-databases.md
- Document that writing to destination (passive) replica causes data inconsistency
- Explain eviction/expiration only operates on active replica
- Detail memory management conflicts and replication failures
- Provide proper steps for transitioning passive to active database
- Include warning about syncer exit due to command failures
Addresses DOC-824
> Add Active-Passive replication warnings to data eviction policies

- content/integrate/redis-data-integration/installation/upgrade.md
- content/integrate/redis-data-integration/release-notes/rdi-1-8-0.md
See https://redislabs.atlassian.net/browse/RDSC-3785
> RDSC-3785: Document known issue for RDI upgrade from < 1.8.0 to >= 1.8.0

- content/develop/use/keyspace-notifications.md
[DOC-5412](https://redislabs.atlassian.net/browse/DOC-5412)
Per Misha's [original PR](https://github.com/redis/docs/pull/1781), which I totally messed up. :(
[DOC-5412]: https://redislabs.atlassian.net/browse/DOC-5412?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DOC-5412: update KSN page for ROS8.2

- assets/css/index.css
- layouts/_default/_markup/render-heading.html
- layouts/partials/docs-toc.html
- static/js/index.js
DOC-5370
Suggestion from #ask-docs https://redis.slack.com/archives/C02QBGV0LUS/p1750859040153789
> add link icon to section headers

- content/operate/kubernetes/deployment/container-images.md
> K8s: private images - mention admission controller

- content/develop/ai/search-and-query/_index.md
- content/develop/ai/search-and-query/administration/_index.md
- content/develop/ai/search-and-query/administration/configuration.md
- content/develop/ai/search-and-query/advanced-concepts/_index.md
- content/develop/ai/search-and-query/best-practices/_index.md
- content/develop/ai/search-and-query/best-practices/index-mgmt-best-practices.md
- content/develop/ai/search-and-query/deprecated/_index.md
- content/develop/ai/search-and-query/indexing/_index.md
- content/develop/ai/search-and-query/indexing/field-and-type-options.md
- content/develop/ai/search-and-query/indexing/schema-definition.md
- content/develop/ai/search-and-query/query/_index.md
- content/develop/ai/search-and-query/vectors.md
- field-and-type-options.md: Fixed alias to point to correct interact paths
- schema-definition.md: Fixed alias to point to correct interact paths
- configuration.md: Added missing interact aliases and fixed format
- Added trailing slash variants for all directory aliases
- Fixed indexing/ and query/ URLs that were redirecting to home page
- Updated: _index.md, indexing/_index.md, query/_index.md, advanced-concepts/_index.md, administration/_index.md, best-practices/_index.md, deprecated/_index.md
- index-mgmt-best-practices.md: Added missing interact alias
- aggregations-syntax.md: Added missing interact alias
- Aliases were incorrectly pointing to /ai/ paths instead of /interact/ paths
- Directory aliases needed both with/without trailing slash variants
- Some files missing interact …
> DOC-5428 Fix search-and-query documentation aliases 

- content/operate/oss_and_stack/stack-with-enterprise/release-notes/redisce/redisos-8.0-release-notes.md
- content/operate/oss_and_stack/stack-with-enterprise/release-notes/redisce/redisos-8.2-release-notes.md
[DOC-5420](https://redislabs.atlassian.net/browse/DOC-5420)
Release notes for:
- ROS 8.0.3
- ROS 8.2-RC1
[DOC-5420]: https://redislabs.atlassian.net/browse/DOC-5420?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DEV: add 8.0.3 and 8.2-RC1 release notes

- content/operate/oss_and_stack/stack-with-enterprise/release-notes/redisce/redisce-7.4-release-notes.md
[DOC-5440](https://redislabs.atlassian.net/browse/DOC-5440)
[DOC-5440]: https://redislabs.atlassian.net/browse/DOC-5440?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OP: add Redis 7.4.5 release notes

- content/develop/pubsub/keyspace-notifications.md
In recent [PR](https://github.com/redis/docs/pull/1789) about adding docs for new KSN types I forgot to add some docs, so this PR fixes that
> Fix docs about the A param of KSN config

- content/embeds/supported-platforms-embed.md
- content/operate/rs/security/certificates/updating-certificates.md
- Document that FUTURE crypto policy rejects certificates with keys < 3072 bits
- Explain impact on users with custom 2048-bit certificates
- Provide guidance to change policy from FUTURE to DEFAULT
- Include reference to Red Hat crypto policy documentation
Addresses DOC-1629
> Add RHEL 8 crypto policy limitation for certificate key sizes

- content/operate/oss_and_stack/stack-with-enterprise/release-notes/redisce/redisos-8.0-release-notes.md
- content/operate/oss_and_stack/stack-with-enterprise/release-notes/redisce/redisos-8.2-release-notes.md
No JIRA ticket, just a quick fix.
> DEV: fix 8.2-RC1 release notes section title

- content/integrate/redis-mcp/_index.md
- content/integrate/redis-mcp/ciient-conf.md
- content/integrate/redis-mcp/client-conf.md
- content/integrate/redis-mcp/install.md
[DOC-5254](https://redislabs.atlassian.net/browse/DOC-5254)
Currently just a starting point, so all suggestions welcome. In particular:
- Is "Libraries and tools" the best place for this? I think it probably does belong here, but maybe it would most commonly be used a bit like Redis Insight and it should therefore go under `develop/tools`?
- Do we want a puny banner in the page to state that this is a preview, or is it effectively GA now?
- Any other info to add? Is the API solid enough now to add code examples directly in the page or is it better just to point to Github for now?
[DOC-5254]: https://redislabs.atlassian.net/browse/DOC-5254?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DOC-5254 starter docs for Redis MCP

- content/integrate/redis-data-integration/architecture.md
[DOC-5348](https://redislabs.atlassian.net/browse/DOC-5348)
I think the info is OK, but I'll ping Greg for the info from his course if we need more detail here.
[DOC-5348]: https://redislabs.atlassian.net/browse/DOC-5348?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DOC-5348 RDI: info about at-least-once delivery and checkpointing

- content/develop/clients/redis-py/prob.md
[DOC-5225](https://redislabs.atlassian.net/browse/DOC-5225)
The code is now merged in the redis-py repo, so we can enable the testable examples now.
[DOC-5225]: https://redislabs.atlassian.net/browse/DOC-5225?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DOC-5225 enabled testable Python prob examples

- content/develop/ai/search-and-query/indexing/field-and-type-options.md
- content/develop/ai/search-and-query/vectors.md
- static/resources/redisuniversity.yaml
[DOC-5457](https://redislabs.atlassian.net/browse/DOC-5457)
Note to reviewers: there were no applicable changes to the FT.CREATE command page; it refers to the main vector indexing page for all vector-related parameters. This is where the lion's share of the changes were made.
[DOC-5457]: https://redislabs.atlassian.net/browse/DOC-5457?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DOC-5457: add the new SVS-VAMANA vector algorithm type

- content/operate/rs/7.4/references/rest-api/requests/ldap_mappings/_index.md
- content/operate/rs/7.8/references/rest-api/requests/ldap_mappings/_index.md
- content/operate/rs/references/rest-api/requests/ldap_mappings/_index.md
Fixes https://github.com/redis/docs/issues/1829 and DOC-5464
> DOC-5464 RS: Fixed role_uids type in LDAP mapping REST API examples

- content/develop/data-types/timeseries/_index.md
[DOC-5424](https://redislabs.atlassian.net/browse/DOC-5424)
Just add TCE markup to existing CLI examples. Python code has already been merged and will appear in this page in the build.
[DOC-5424]: https://redislabs.atlassian.net/browse/DOC-5424?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DOC-5424 enabled TCEs in time series page

- data/components/node_redis.json
No ticket. Just a quick fix to point the build code at the node-redis master branch instead of the emb-examples branch.
> DEV: patch node_redis.json branch to match repo

- content/develop/ai/search-and-query/advanced-concepts/tags.md
[DOC-3346](https://redislabs.atlassian.net/browse/DOC-3346)
Tags doc updated with more emphasis on their use in exact match scenarios.
[DOC-3346]: https://redislabs.atlassian.net/browse/DOC-3346?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DEV: update RQE tags doc

- .gitignore
No ticket. Just a quick update to `.gitignore`, telling it to ignore all occurrences of `__pycache__` directories.
> Quick .gitignore update

- content/commands/vismember.md
- content/commands/vrem.md
- content/commands/vsim.md
- content/develop/data-types/vector-sets/_index.md
[DOC-5495](https://redislabs.atlassian.net/browse/DOC-5495)
[DOC-5495]: https://redislabs.atlassian.net/browse/DOC-5495?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DOC-5495: modify vector set docs for 8.2 (initial commit)

- content/commands/json.arrappend.md
- content/commands/json.arrindex.md
- content/commands/json.arrinsert.md
- content/commands/json.arrlen.md
- content/commands/json.arrpop.md
- content/commands/json.arrtrim.md
- content/commands/json.clear.md
- content/commands/json.debug-help.md
- content/commands/json.debug-memory.md
- content/commands/json.del.md
- content/commands/json.get.md
- content/commands/json.merge.md
- content/commands/json.mget.md
- content/commands/json.mset.md
- content/commands/json.numincrby.md
- content/commands/json.nummultby.md
- content/commands/json.objkeys.md
- content/commands/json.objlen.md
- content/commands/json.resp.md
- content/commands/json.set.md
- content/commands/json.strappend.md
- content/commands/json.strlen.md
- content/commands/json.toggle.md
- content/commands/json.type.md
[DOC-5321](https://redislabs.atlassian.net/browse/DOC-5321)
[DOC-5321]: https://redislabs.atlassian.net/browse/DOC-5321?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DEV: add RESP2/3 return information to the JSON commands

- content/operate/rs/clusters/optimize/disk-sizing-heavy-write-scenarios.md
> RS: Clarified formula and examples for disk sizing for heavy write scenarios

- content/operate/kubernetes/re-clusters/auto-tiering.md
- content/operate/kubernetes/re-clusters/expand-pvc.md
- content/operate/kubernetes/release-notes/7-22-0-releases/_index.md
- content/operate/kubernetes/release-notes/7-4-2-releases/7-4-2-12.md
- content/operate/kubernetes/release-notes/7-4-6-releases/7-4-6-2.md
- content/operate/kubernetes/release-notes/7-8-2-releases/7-8-2-6-nov24.md
> K8s: PVC expansion-RoF limitation

- content/develop/ai/langcache/api-examples.md
- layouts/partials/tabbed-clients-example.html
- layouts/shortcodes/clients-example.html
- local_examples/langcache/langcache_sdk.js
- local_examples/langcache/langcache_sdk.py
Also adds a "footer=hide" option to the client examples to hide the footer, since I couldn't figure out how to hide the footer for specific tabs.
> Langcache: Change examples from multitab to local client examples

- content/develop/ai/_index.md
- layouts/shortcodes/image-card.html
[DOC-5539](https://redislabs.atlassian.net/browse/DOC-5539)
Fixes #1911.
Adds new`image-card` shortcode.
[DOC-5539]: https://redislabs.atlassian.net/browse/DOC-5539?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DEV: fix image links on AI landing page

- content/embeds/rs-prometheus-metrics-v2.md
DOC-5467
Staged preview: https://redis.io/docs/staging/DOC-5467/operate/rs/references/metrics/prometheus-metrics-v2/#database-metrics
> RS: Added connection rate throttling metrics

- content/operate/rs/7.4/references/rest-api/objects/bdb/backup_location.md
- content/operate/rs/7.4/references/rest-api/objects/bdb/dataset_import_sources.md
- content/operate/rs/7.8/references/rest-api/objects/bdb/backup_location.md
- content/operate/rs/7.8/references/rest-api/objects/bdb/dataset_import_sources.md
- content/operate/rs/references/rest-api/objects/bdb/backup_location.md
- content/operate/rs/references/rest-api/objects/bdb/dataset_import_sources.md
> RS: Added S3 compatible storage info to REST API DB import/export sources references

- config.toml
- data/components/index.json
- data/components/php.json
- layouts/partials/tabs/wrapper.html
- local_examples/php/DtStringTest.php
This:
- Enables the config for PHP examples
- Squeezes the tab buttons a bit closer together to make room for the PHP button
- Adds a first PHP example (strings datatype page)
> DOC-5544 enable PHP tabbed code examples

- content/operate/rc/security/access-control/saml-sso/_index.md
> RC: SAML linking must be performed by same user

- content/embeds/supported-platforms-embed.md
DOC-5549 and fixes https://github.com/redis/docs/issues/1933
Staged preview: https://redis.io/docs/staging/DOC-5549/operate/rs/references/supported-platforms/
> RS: Added that 7.22.0 uses RHEL 9.6 to the RHEL version vs. Redis Enterprise version table

- content/develop/clients/go/vecsearch.md
- content/develop/clients/go/vecsets.md
- local_examples/client-specific/home_query_vec.go
- local_examples/client-specific/home_vecsets.go
Go equivalent to the [vector sets example](https://redis.io/docs/latest/develop/clients/redis-py/vecsets/) for Python.
Bonus feature! I've also updated the existing Go query engine vector example to use the same embeddings library ([`Hugot`](https://github.com/knights-analytics/hugot)) as the vector sets example. This is better for consistency, but also Hugot doesn't require you to obtain an API key to generate the embeddings.
> DOC-5533 Go vector set embeddings example

- content/operate/rs/7.4/security/encryption/tls/enable-tls.md
- content/operate/rs/7.8/security/encryption/tls/enable-tls.md
- content/operate/rs/security/encryption/tls/enable-tls.md
> RS: Added crdb-cli and REST API examples to enable TLS after Active-Active database creation

- content/operate/kubernetes/recommendations/node-selection.md
> K8s: RZA limitation

- content/develop/reference/modules/_index.md
A "known limitation", which were actually a bug, was fixed because of this commit (see propagate.tcl):
When using a mix of RM_Call with ! and RM_Replicate, the command would propagate out-of-order: first all the commands from RM_Call, and then the ones from RM_Replicate
click [here](https://github.com/redis/redis/pull/9890)
> fix-content

- content/integrate/redisom-for-node-js/_index.md
> INT: update Redis OM Node.js page per #1952

- content/commands/vadd.md
- content/commands/vemb.md
- content/commands/vlinks.md
- content/commands/vsim.md
- content/develop/data-types/vector-sets/_index.md
Fixes #1967.
Fixes #1972.
Also includes updates to the return information for the VLINKS command page.
Tests used to confirm the correct return information for the VLINKS command:
```
RESP2
vlinks vs element1
*1
*2
$8
element2
$8
element3
vlinks vs element1 withscores
*1
*4
$8
element2
$17
0.996941864490509
$8
element3
$3
0.5
vlinks foo
-ERR wrong number of arguments for 'VLINKS' command
vlinks vs foo
$-1
vlinks foo bar
$-1
RESP3
vlinks vs element1
*1
*2
$8
element2
$8
element3
vlinks vs element1 withscores
*1
%2
$8
element2
,0.996941864490509
$8
element3
,0.5
vlinks foo
-ERR wrong number of arguments for 'VLINKS' command
vlinks vs foo
_
vlinks foo bar
_
```
> DEV: FP32 (vectorsets) should explicitly document endianness

- content/commands/info.md
Update the index's memory after the fix in https://github.com/RediSearch/RediSearch/pull/6613
Also, point out that this field is a "best-effort" estimation rather than an accurate one.
> DEV: update search memory info

- content/develop/clients/nodejs/connect.md
- content/develop/clients/nodejs/migration.md
Uses the latest info from the `node-redis` repo [here](https://github.com/redis/node-redis/blob/master/docs/client-configuration.md#reconnect-strategy).
Closes #1988
> DOC-5585 fix node-redis reconnection details

- content/develop/clients/lettuce/vecsearch.md
- local_examples/client-specific/lettuce-async/HomeQueryVecExample.java
- local_examples/client-specific/lettuce-reactive/HomeQueryVecExample.java
Lettuce versions of the [index/query vectors](https://redis.io/docs/latest/develop/clients/redis-py/vecsearch/) page. It's a bit more complicated than the others due to the advanced options that Lettuce offers, but hopefully still basically makes sense.
> DOC-5557 Lettuce vector index/query page

- content/operate/kubernetes/re-clusters/expand-pvc.md
> K8s: add info on default PVC size

- content/embeds/rdi-supported-source-versions.md
- content/integrate/redis-data-integration/data-pipelines/prepare-dbs/spanner.md
- content/integrate/redis-data-integration/installation/install-k8s.md
Reworking our internal [Confluence doc](https://redislabs.atlassian.net/wiki/spaces/RED/pages/5313036492/RDI+Installation+guide+with+Spanner) for setting up Spanner as official documentation on how RDI works with Spanner.
> RDSC-3972: RDI now supports Google Spanner public docs

- .github/workflows/main-staging.yml
- .github/workflows/main.yml
- layouts/partials/docs-nav.html
This change removes the need to manually update the version picker. The content of the picker is based on the versioned folders on the filesystem.
> Update docs-nav to dynamically create version dropdown for products

- content/develop/ai/search-and-query/vectors/_index.md
small fix for the changes done in the API, instead `LEANVEC_DIM`to `REDUCE`
> fix the LEANVEC_DIM to REDUCE _index.md

- content/commands/xackdel.md
The title says it all. Had to be done, because ACLs on the instance of Redis that drives the CLI widget specifically exclude the `XINFO`, `XGROUP`, `XREAD`, and `XREADGROUP` commands. 🤷🏻‍♂️
> DEV: remove interactive example from XACKDEL command page

- content/develop/ai/search-and-query/vectors/_index.md
- content/develop/ai/search-and-query/vectors/svs-compression.md
Update the SVS compression documentation to focus on the feature of compression and quantization, using the technique names LVQ and LeanVec, as these are directly reflected in the API and implementation. Remove generic references and ensure all sections and examples use LVQ and LeanVec terminology, as well as their respective naming conventions for configuration. The rewritten content should clarify the function and benefit of each variant, the role of multi-level compression, and practical considerations for parameter learning and data drift, while maintaining warning about hardware dependency and proprietary optimizations.
> refactor focus on feature not the techniques svs-compression.md

- content/develop/ai/search-and-query/advanced-concepts/tags.md
- content/develop/ai/search-and-query/indexing/_index.md
Maybe a bit overboard, but repetition is a sound pedagogical technique, right? 🤣
> DEV: enhance TAG docs per GH issues

- assets/css/index.css
Open to all suggestions about the colour to use for the namespaces, but it should probably not be the same as the surrounding keywords :-) 
Staging: [Python](https://redis.io/docs/staging/DOC-5654-python-import-css/develop/clients/redis-py/amr/), [Java](https://redis.io/docs/staging/DOC-5654-python-import-css/develop/clients/jedis/queryjson/#initialize), [C#](https://redis.io/docs/staging/DOC-5654-python-import-css/develop/clients/dotnet/queryjson/#initialize). Other languages already look OK.
> DOC-5654 changed namespace name highlighting

- local_examples/php/DtHashTest.php
PHP examples for the [hash data type page](https://redis.io/docs/latest/develop/data-types/hashes/).
Staging: https://redis.io/docs/staging/DOC-5670-php-hash-examples/develop/data-types/hashes/
> DOC-5670 added PHP hash examples

- local_examples/php/DtSetsTest.php
PHP examples for the [sets data type page](https://redis.io/docs/latest/develop/data-types/sets/).
Staging: https://redis.io/docs/staging/DOC-5671-php-sets-example/develop/data-types/sets/
> DOC-5671 added PHP sets examples

- content/develop/ai/search-and-query/_index.md
There is an in-product link that refers to https://redis.io/docs/latest/interact/search-and-query/, so I've added an alias for that.
> Update S&Q _index.md with another alias

- content/operate/kubernetes/active-active/prepare-clusters.md
> K8s: Add username password formatting note

- local_examples/php/DtVecSetsTest.php
PHP versions of the examples in [this page](https://redis.io/docs/latest/develop/data-types/vector-sets/).
Staging:
https://redis.io/docs/staging/DOC-5675-php-vec-set-examples/develop/data-types/vector-sets/
https://redis.io/docs/staging/DOC-5675-php-vec-set-examples/develop/data-types/vector-sets/performance/
https://redis.io/docs/staging/DOC-5675-php-vec-set-examples/develop/data-types/vector-sets/memory/
> DOC-5675 added PHP vector set examples

- local_examples/php/CmdListTest.php
- local_examples/php/CmdSetTest.php
PHP command examples (staging links):
- [SADD](https://redis.io/docs/staging/DOC-4423-add-php-set-list-cmd-examples/commands/sadd/)
- [SMEMBERS](https://redis.io/docs/staging/DOC-4423-add-php-set-list-cmd-examples/commands/smembers/)
- [LLEN](https://redis.io/docs/staging/DOC-4423-add-php-set-list-cmd-examples/commands/llen/)
- [LPOP](https://redis.io/docs/staging/DOC-4423-add-php-set-list-cmd-examples/commands/lpop/)
- [LPUSH](https://redis.io/docs/staging/DOC-4423-add-php-set-list-cmd-examples/commands/lpush/)
- [LRANGE](https://redis.io/docs/staging/DOC-4423-add-php-set-list-cmd-examples/commands/lrange/)
- [RPOP](https://redis.io/docs/staging/DOC-4423-add-php-set-list-cmd-examples/commands/rpop/)
- [PUSH](https://redis.io/docs/staging/DOC-4423-add-php-set-list-cmd-examples/commands/rpu …
> DOC-5690 DOC-5689 DOC-5691 DOC-5692 DOC-5693 DOC-5694 DOC-5695 DOC-5696 PHP list and set cmd examples

- content/integrate/redis-mcp/install.md
Fix to say that Redis Cloud MCP is for admin only - you still need the main MCP server to interact with a database on Cloud.
> DOC-5698 corrected info about Redis Cloud MCP

- content/integrate/redis-data-integration/data-pipelines/deploy.md
A long command line example inside a `{{< note >}}` shortcode was causing the rest of the text in the note to overflow. Fixed by wrapping the command line with backslashes.
> DOC-5709 fixed dodgy note formatting

- content/operate/rs/7.4/databases/auto-tiering/storage-engine.md
- content/operate/rs/7.8/databases/auto-tiering/storage-engine.md
Copies the fixes from #2087 to the RS 7.8 and 7.4 versions.
> RS: Copied storage engine description/link fixes to 7.8 and 7.4 versions

- content/operate/oss_and_stack/stack-with-enterprise/release-notes/redisearch/redisearch-2.10-release-notes.md
- content/operate/oss_and_stack/stack-with-enterprise/release-notes/redisearch/redisearch-2.8-release-notes.md
There may yet be one more set of release notes for 2.6.x.
> OP: update RediSearch release notes (multiple)

- content/develop/clients/jedis/failover.md
- content/develop/clients/jedis/produsage.md
- static/images/failover/failover-client-failback.svg
- static/images/failover/failover-client-reconnect.svg
- static/images/failover/failover-sliding-window.svg
All feedback welcome on this rather complicated page, including:
- Is it too long? Maybe some of the content could be moved elsewhere.
- Do the diagrams make sense?
- Is the basic breakdown of presentation OK?
> DOC-5665 Jedis failover docs

- content/develop/clients/jedis/failover.md
The feature isn't quite ready to go, so we should hide the docs page with `draft: true` for now.
> DOC-5742 hide Jedis failover page for now

- content/operate/rs/security/encryption/tls/_index.md
- content/operate/rs/troubleshooting.md
> RS: Added troubleshooting index with links to knowledge base

- content/develop/ai/search-and-query/advanced-concepts/geo.md
- content/operate/kubernetes/re-databases/modules.md
Also fixes a bad link in the K8s docs.
> DEV: add precision info to GEO search ref. page

- assets/css/index.css
- content/operate/rs/7.8/clusters/change-node-role.md
- content/operate/rs/clusters/change-node-role.md
- static/js/index.js
Also cherry-picked the img fix/workaround that allows screenshots within the multitabs shortcode.
> RS: Added rladmin commands to change node roles

- content/integrate/redis-data-integration/installation/install-k8s.md
- content/integrate/redis-data-integration/installation/install-vm.md
We've had some feedback saying that the [RDI K8s install page](https://redis.io/docs/latest/integrate/redis-data-integration/installation/install-k8s/#deploy-a-pipeline) mentions using Redis Insight to deploy but doesn't explain how to do this. We have a [RDI in Redis Insight page](https://redis.io/docs/latest/develop/tools/insight/rdi-connector/) (which seems to have the relevant info), and links to it from the installer pages, but the text around the links doesn't emphasise that this is where you should go if you want to use Redis Insight.
I've improved the text on the installer pages to suggest following the links to the RDI/RI page. However, if any more detail would be helpful here, then let me know and I'll add it.
> DOC-5750 clearer pointers about using RDI in Redis Insight

- content/embeds/rc-heroku-add-on.md
- content/integrate/heroku-redis/_index.md
- content/operate/rc/_index.md
- content/operate/rc/cloud-integrations/heroku.md
Depends on #2165 - duplicating the Heroku page into the RC docs and adding Heroku mentions to the top-level page.
> RC: Add Heroku mention to RC docs

- content/operate/rs/security/encryption/internode-encryption.md
> RS: Added link to update/renew INE certs

- build/components/example.py
- local_examples/client-specific/rust-async/landing.rs
- local_examples/client-specific/rust-sync/landing.rs
Proposed improvement is to structure Rust example files as [test modules](https://doc.rust-lang.org/rust-by-example/testing/unit_testing.html) so that we can add the usual asserts and run them with the standard Rust testing system. Also, if you enable the "Test Explorer" option in the rust-analyzer extension in VSCode, you get the usual test arrows, etc, in the editor for test modules.
Staging: https://redis.io/docs/staging/DOC-5785-rust-example-format/develop/clients/rust/
> DOC-5785 added Rust examples in updated format

- content/develop/data-types/strings.md
- local_examples/rust-async/dt-hash.rs
- local_examples/rust-async/dt-string.rs
- local_examples/rust-sync/dt-hash.rs
- local_examples/rust-sync/dt-string.rs
Also fixed a dodgy heading in the strings page.
Staging for hashes: https://redis.io/docs/staging/DOC-5790-rust-dt-tces/develop/data-types/hashes/
> DOC-5791 DOC-5792 Rust string and hash data type TCEs

- content/develop/ai/search-and-query/vectors/svs-compression.md
I thought it made more sense to include the build instructions at the bottom of the existing quant. page.
> DOC-5799: search: document procedure for building with Intel binaries

- content/embeds/rc-rdi-secrets-permissions.md
- content/operate/rc/changelog/september-2025.md
- content/operate/rc/databases/rdi/setup.md
Changes discussed in #rdi-ingenico private slack channel.
> RC RDI: Clarify load balancer security group selection
